### ISSUE TITLE
nicer IGC filenames

### ISSUE THREAD

**Issue by fhorinek** [fhorinek/SkyDrop#100]
by @tomasz13

filenames could be nicer... :) timestamp or something humad readable thing not like current 5AFXDRP5.IGC
151015152501.IGC is much more U.frendly :D

and with directory....

../LOG/%Y/%m%d%H%M.IGC
../LOG/2015/10151541.IGC

the logs shorter like 1min in same minute could be repleaced. (I think they are still useless )

**Comment by fhorinek** [comment]
what about /logs/year/month/day/[flight of the day]-%H%M.IGC/KML ?

**Comment by jarda-manana** [comment]
I like this idea

**Comment by fhorinek** [comment]
implemented in next release
