### ISSUE TITLE
built 1449 Beta usb connection problem

### ISSUE THREAD

**Issue by Kapiness** [fhorinek/SkyDrop#101]
Hi,

after update to built 1449 Beta i cant see skydrop on OS X and also on Windows. Skydrop is in usb mode, but i computer cant see it.

**Comment by fhorinek** [comment]
what is the color of the led?

**Comment by Kapiness** [comment]
blue

**Comment by fhorinek** [comment]
did you use different usb cables before and after the update?

**Comment by Kapiness** [comment]
Yes!, now i use same cable than before update, and its working!!! thanks... i think that cable is wrong... THANKS! good to know that if is blue light that mean connection is bad

**Comment by Kapiness** [comment]
Sorry :D
