### ISSUE TITLE
device turns off after few minutes

### ISSUE THREAD

**Issue by jarda-manana** [fhorinek/SkyDrop#102]
Hw revision 1504, fw 1449beta, fully charged. My device turns off itself 9 times during 25 minutes test drive. If vario beeps, the last tone persists for 2-3s. I noticed, that fTime widget shows 00:16 in last run, that's weird, because device runs for only few minutes in this moment. Now the device lies on the table and runs 20 minutes without problems.

I saw spontaneous  turns off on previous fw versions too, but it was very rare.

I can provide igc files, if you are interested (most of them was logged without gps lock (blinking G)).
Idea: what about log debug into a file (configurable)?

**Comment by fhorinek** [comment]
did you have glide ratio on screen when it failed?

regarding the log: I have already implemented this few days ago :)
so in next release.

**Comment by jarda-manana** [comment]
I guess no. There was default page (bar, vario, avg, alt1, alt2) in most cases, but it occurred in other pages too.

log: :+1: :)

**Comment by jarda-manana** [comment]
Same on 1714beta. After few crashes I arrived to the work and there is a debug file https://www.dropbox.com/s/6y84ceuwgzcpalz/DEBUG.LOG?dl=0
Seems too short - maybe I should open crashed drop and copy the file directly from sd card?
I noticed warning "SD card error" appears in one moment, but this doesn't cause a crash.

**Comment by jarda-manana** [comment]
Here is a log from dead skydrop (I removed card from drop and copy directly from card): https://www.dropbox.com/s/876dop2s3w9ogh9/DEBUG2.LOG?dl=0
I noticed "SD card error" several times.

**Comment by fhorinek** [comment]
Try to reformat the sd card before more investigation

**Comment by jarda-manana** [comment]
reformat done, next test run on lunch break ;) thx

**Comment by ZIRminator** [comment]
same problem here!
skydrop turned off itself during a flight like 3 times in one hour. it was the 22nd of august with the newest fw.
this sunday the device turned off 3 times in 20min with 1449beta. any new solutions?
wich program do you use to read the IGC files? it doesnt work with IGC Flight Replay

thanks!

**Comment by fhorinek** [comment]
on 22nd august may be the glide ratio calculation bug
please update to 1714beta and try again, just remember there is automatic
shut down after 20min of inactivity (not flying). Settings->system->auto
power off.
I am using XContest.org I will look at IGC Flight Replay.

--
František Horínek

2015-11-03 22:04 GMT+01:00 ZIRminator <notifications@github.com>:

**Comment by ZIRminator** [comment]
when I upload a icg file from skydrop on xcontest.org, I get this:
Errors occured during data processing!
with both 1449beta and 1714beta.

last time when skydrop turned off 3 times, it was in the air during a flight with "take off" on display

**Comment by fhorinek** [comment]
Attach debug log and IGC file please

**Comment by jarda-manana** [comment]
Reformatting card looks promising, but I'll see during longer test run.

**Comment by ZIRminator** [comment]
I formated the card yesterday. lets see if this is the solution...

here are log and debug files:
https://dl.dropboxusercontent.com/u/29303320/debug_log.zip

please tell me if you are abel to open the icg files.
thanks a lot!

**Comment by jarda-manana** [comment]
Bad news - reformatting didn't solve the issue. Here is files from crashed skydrop copied from extracted sd card:
https://www.dropbox.com/sh/qgx24onping2rpu/AAAu6J10GSPQSOICmCJ8-5WJa?dl=0
There is two tracklogs, because skydrop detect landing during stop on traffic lights, so I turn it off and on again. The second one contains two valid intervals according to xcontest, so I choose the last one. Here are links to xcontest:
http://www.xcontest.org/cesko/prelety/detail:manana/5.11.2015/03:46
http://www.xcontest.org/cesko/prelety/detail:manana/5.11.2015/03:52
(please take a look at other layers in graph (to activate them click on small orange icon in top right corner of altitude profile area) - they look weird)

**Comment by fhorinek** [comment]
@ZIRminator the igc files are corrupted because you are using 1449 where is the igh H-record bug, please upgrade to 1714

@jarda-manana the log file looks strange lot of timeouts and transfer errors. I need to find proper way to investigate this behavior.

BTW: if you can open skydrop as mass storage then the files are the same, since there is direct connection to sd card through usb (no need to open drop and remove the card)

**Comment by jarda-manana** [comment]
@fhorinek I can send my device to you - no problem (and maybe you will be able to resolve my bluetooth issue ;) ). I know well how hunting bugs that 'worksforme' can be difficult (and annoying) ;)

**Comment by ZIRminator** [comment]
I had a flight today with the new fw and a reformated sd card. I no problems... not even with the log file (kml this time)

what is the difference between igc and kml? are there more information with one of the files?

**Comment by jarda-manana** [comment]
This ride skydrop survive: https://www.dropbox.com/sh/0qevh0vgnrntgjq/AAAG5ZhXJm1BiUCyvc8-cds9a?dl=0 I turned off land detection before.

**Comment by fhorinek** [comment]
update!
http://vps.skybean.eu:8080/repo/updates/1773beta/

**Comment by fhorinek** [comment]
@ZIRminator the new fixed updates are out please try them
@jarda-manana your device is now working without any problems, we will send it back to you, it was very  helpful for debug
