### ISSUE TITLE
Skydrop not recording flights

### ISSUE THREAD

**Issue by flyboy0871** [fhorinek/SkyDrop#103]
after 2 flights with Skydrop , device was not recording. I initiated factory test, and BT: ERR is blinking. Advice?

**Comment by fhorinek** [comment]
what build version do you have?

**Comment by flyboy0871** [comment]
Just received it week ago. I also initiated factory check, all is ok, but
BT:ERR is blinking and can't get out of that mode

Safe landings!   Jaro Krupa    708-935-0177

www.chicagoparagliding.com
www.777glidersusa.com
www.oudie3.com
*Facebook*:  *Chicago Paragliding*



On Tue, Oct 20, 2015 at 9:59 AM, František Horínek <notifications@github.com

**Comment by flyboy0871** [comment]
Safe landings!  Jaro (708)935-0177
www.chicagoparagliding.com
www.777glidersusa.com
www.oudie3.com
Facebook: Chicago Paragliding

**Comment by fhorinek** [comment]
please update to this fw release http://skybean.eu:8080/repo/updates/1278/
here are the instructions
https://www.youtube.com/watch?v=_qffgnJawU0

**Comment by flyboy0871** [comment]
Hi Franto, did that but skydrio is still in factory test. How do i get out
of there? When pressing power button, there is buzzing sound with green
light, right arrow gives no sound with blue light , left arrow gives red
light with lower pitch buzz.

Safe landings!   Jaro Krupa    708-935-0177

www.chicagoparagliding.com
www.777glidersusa.com
www.oudie3.com
*Facebook*:  *Chicago Paragliding*



On Wed, Oct 21, 2015 at 3:49 AM, František Horínek <notifications@github.com

**Comment by fhorinek** [comment]
ok my bad go to 1449beta
in builds from ~900 - 1275 is a bug preventing fc to end correctly

**Comment by flyboy0871** [comment]
ok works, thanx . But display is not working properly , and can't adjust it
with contrast and backlight. Before in factory test it was showing me
different positions of display correctness/sharpness. Do i have to download
previous fix to adjust display and go back to latest update?


Safe landings!   Jaro Krupa    708-935-0177

www.chicagoparagliding.com
www.777glidersusa.com
www.oudie3.com
*Facebook*:  *Chicago Paragliding*



On Wed, Oct 21, 2015 at 9:28 AM, František Horínek <notifications@github.com

**Comment by fhorinek** [comment]
you can reset factory test and set correct min and max contrast values.
place any file called RST_FT on sd card to reset the factory test
make sure you set your min and max values correctly

**Comment by flyboy0871** [comment]
ok Super , funguje !  Diky Franto


Safe landings!   Jaro Krupa    708-935-0177

www.chicagoparagliding.com
www.777glidersusa.com
www.oudie3.com
*Facebook*:  *Chicago Paragliding*

**Comment by fhorinek** [comment]
Som rád :) IGC je už hotové ale čakáme na odpoveď z xcontestu a fai civil

**Comment by flyboy0871** [comment]
Este jedna otazka, mama iphone6. Ktory bluetooth mode robi s iphone??
Digifly,bluefly or lk8ex1. Moj telefon nevidi ani jeden

Safe landings!   Jaro Krupa    708-935-0177

www.chicagoparagliding.com
www.777glidersusa.com
www.oudie3.com
*Facebook*:  *Chicago Paragliding*

**Comment by fhorinek** [comment]
iPhone zatiaľ nie je podporovaný. Bude skoro.

**Comment by fhorinek** [comment]
IGC loggin is enabled in current beta release, validation is pending, closing the issue
