### ISSUE TITLE
buzzer volume reduced, no way to make it audible anymore.

### ISSUE THREAD

**Issue by pturri** [fhorinek/SkyDrop#104]
Today I did a couple of hours flight, after about 1 hour SkyDrop volume decreased on its own to very low level, barely audible. 
Landed, I check volume and sounds, but they were correct (all set to 75%).
I change them to maximum, but buzzer now is barely audible, even if set to 100%, it's about 1/4 - 1/3 of normal volume. 
Please note that device was not sujbect to any shock or impact, it was on my cockpit and I was flying in normal conditions....

**Comment by fhorinek** [comment]
What is the battery level?

**Comment by pturri** [comment]
it was fully charged, at landing it was still more than 50%

**Comment by fhorinek** [comment]
The decrease was sudden or it was slowly decreasing?

**Comment by pturri** [comment]
mmhh.. hard to know, as said I was in flight and the day was very weak, the vario was not buzzing all the time. Anyway, in my opinion it happened suddenly or so.

**Comment by pturri** [comment]
FYI, upgraded to 1714, buzzer volume still too low. 
At this point, I'm afraid it's an hardware issue.

**Comment by pturri** [comment]
Any new on this? The unit is unusable at the moment. 
Shall I send it back for your investigation?

**Comment by fhorinek** [comment]
We were trying to replicate this issue. So far no luck. 
Please write the message to info@skybean.eu and we will arrange replacement for you.
