### ISSUE TITLE
IGC log with constant position

### ISSUE THREAD

**Issue by ganzenmg** [fhorinek/SkyDrop#105]
Hi there,

build 1449 on rev. 1504 gives me IGC files which report a constant position during flight, see example below. I did have a GPS fix at start though. I have four IGC logs from different days -- they all show this problem. Any advice?

With best wishes,
Georg

AXSBDRP:345832313733120B001000
HFDTE2410-208
HFDTEDATE:2410-208,00
HFPLTPILOTINCHARGE:
HFCM2CREW2:
HFGTYFLIDERTYPE:
HFGIDGLIDERID:
HFRFWFIRMWAREVERSION:build 1449
HFRHWHARDWAREVERSION:drop_1504
HFFTYFRTYPE:SkyBean,SkyDrop
HFGPSRECEIVER:Quectel,L80,22cm,18000m
HFPRSPRESSALTSENSOR:Measurement specialties,MS5611,25907m
HFFSP:AL4
HFALGGEO
HFALPISA
B0924324753000N00749000EA0071300791
B0924344753000N00749000EA0070900791
B0924364753000N00749000EA0070700791
B0924384753000N00749000EA0070500791
B0924404753000N00749000EA0070700790
B0924424753000N00749000EA0070300790
B0924444753000N00749000EA0070100789
B0924464753000N00749000EA0070100789
B0924484753000N00749000EA0070200789
B0924494753000N00749000EA0069500789
B0924514753000N00749000EA0069300788
B0924534753000N00749000EA0069700788
B0924554753000N00749000EA0069200787
B0924574752000N00749000EA0068300787
B0924594752000N00749000EA0068400785
B0925014752000N00749000EA0068400785
B0925034752000N00749000EA0067900783
B0925054752000N00749000EA0067400783
B0925074752000N00749000EA0067300779
B0925094752000N00749000EA0067100779
B0925114752000N00749000EA0066800775
B0925134752000N00749000EA0066700775
B0925154752000N00749000EA0066400770
B0925174752000N00749000EA0066000770
B0925194752000N00749000EA0065800764
B0925214752000N00749000EA0065500764
B0925234752000N00749000EA0065300758
B0925254752000N00749000EA0065100758
B0925274752000N00749000EA0064800748
B0925294752000N00749000EA0064600748
B0925314752000N00749000EA0064500741
B0925334752000N00749000EA0064200741
B0925354752000N00749000EA0064100734
B0925374752000N00749000EA0063900734
B0925394752000N00749000EA0063700734
B0925414752000N00749000EA0063500728
B0925424752000N00749000EA0063400728
B0925444752000N00749000EA0063100722
B0925464752000N00749000EA0062700722
B0925484752000N00749000EA0062700715
B0925504752000N00749000EA0062500715
B0925524752000N00749000EA0062000710
B0925544752000N00749000EA0061700710
B0925564752000N00749000EA0061200703
B0925584752000N00749000EA0060900703
B0926004752000N00749000EA0060500696
B0926024752000N00749000EA0060200696
B0926044752000N00749000EA0059600688
B0926064752000N00749000EA0059100688
B0926084752000N00749000EA0058900680
B0926104752000N00749000EA0058400680
B0926124752000N00749000EA0057800675
B0926144752000N00749000EA0057300675
B0926164752000N00749000EA0057300671
B0926184752000N00749000EA0057000671
B0926204752000N00749000EA0056500667
B0926224752000N00749000EA0055900667
B0926244752000N00749000EA0055500658
B0926264752000N00749000EA0055200658
B0926284752000N00749000EA0054600652
B0926304752000N00749000EA0054200652
B0926314752000N00749000EA0054200647
B0926334752000N00749000EA0054000647
B0926354752000N00749000EA0053800644
B0926374752000N00749000EA0053200644
B0926394752000N00749000EA0052800638
B0926414752000N00749000EA0052900638
B0926434752000N00749000EA0052400633
B0926454752000N00749000EA0052100633
B0926474752000N00749000EA0052100629
B0926494752000N00749000EA0051400629
B0926514752000N00749000EA0051500624
B0926534752000N00749000EA0051500624
B0926554752000N00749000EA0050900619
B0926574752000N00749000EA0050700619
B0926594752000N00749000EA0050500613
B0927014752000N00749000EA0050500613
B0927034752000N00749000EA0050100604
B0927054752000N00749000EA0049600604
B0927074752000N00749000EA0049500594
B0927094752000N00749000EA0049500594
B0927114752000N00749000EA0049000588
B0927134752000N00749000EA0048700588
B0927154752000N00749000EA0048300588
B0927174752000N00749000EA0048100582
B0927184752000N00749000EA0047700582
B0927204752000N00749000EA0047500576
B0927224752000N00749000EA0047500576
B0927244752000N00749000EA0047000569
B0927264752000N00749000EA0046500569
B0927284752000N00749000EA0046100563
B0927304752000N00749000EA0045800563
B0927324752000N00749000EA0045700556
B0927344752000N00749000EA0044800556
B0927364752000N00749000EA0044600547
B0927384752000N00749000EA0044900547
B0927404752000N00749000EA0044700540
B0927424752000N00749000EA0044800540
B0927444752000N00749000EA0044800533
B0927464752000N00749000EA0044800533
B0927484752000N00749000EA0044800528
B0927504752000N00749000EA0044800528
B0927524752000N00749000EA0044800527
B0927544752000N00749000EA0044800527
B0927564752000N00749000EA0044800527
B0927584752000N00749000EA0044800527
B0928004752000N00749000EA0044800527
B0928024752000N00749000EA0044800527
B0928034752000N00749000EA0044800527
B0928054752000N00749000EA0044800527
B0928074752000N00749000EA0044800527
B0928094752000N00749000EA0044800527
B0928114752000N00749000EA0044800527
B0928134752000N00749000EA0044800527
B0928154752000N00749000EA0044800527
B0928174752000N00749000EA0044800527
B0928194752000N00749000EA0044800527
B0928214752000N00749000EA0044800527
B0928234752000N00749000EA0044800527
B0928254752000N00749000EA0044800527
B0928274752000N00749000EA0044800527
B0928294752000N00749000EA0044800527
B0928314752000N00749000EA0044800527
B0928334752000N00749000EA0044800527
B0928354752000N00749000EA0044800527
B0928374752000N00749000EA0044800527
B0928394752000N00749000EA0044900527
G900FA2981051FB2128B0A162001A41918CFDF6DB

**Comment by fhorinek** [comment]
duplicate #97 and allready fixed in next release
