### ISSUE TITLE
Reset Factory test - GPS : ERR  

### ISSUE THREAD

**Issue by fbuttolo** [fhorinek/SkyDrop#108]
Hi.  
After update from 0910 to 1278 I get the following problem.  
Reset Factory test GPS : ERR  
GPS doesn't work  
I tried to downgrade to 0910 but gps still doesn't work.  
What can I do? Thanks.

**Comment by fhorinek** [comment]
why did you reset the factory test?

**Comment by fhorinek** [comment]
also update to newest fw version
