### ISSUE TITLE
Battery discharges when turned off

### ISSUE THREAD

**Issue by wrowland** [fhorinek/SkyDrop#109]
Hello, 

I have a New Skydrop that I haven't been able to use! On arrival at the hill, I was unable to turn on the device due to a dead battery! I have since noted that the battery will not maintain after being charged. 

I will plug in and charge the battery to 100% by USB wall charger. I then unplug the vario, confirm it reads 100 on the battery widget and shows a full battery symbol. I then Turn off the device and leave it unplugged. After 8hrs, the battery loses 60-70% of its charge just buy sitting and is often fully discharged at 12hrs. I have repeated this experiment with multiple configurations of the device including; GPS on and off, Bluetooth on and off. 

I have the current "1278" version of firmware installed and I have installed the firm ware once with no resolution. 

Any thoughts?

Thanks

Bill

**Comment by RomanKreisel** [comment]
I can confirm this - the first Release I noticed this bug was 1278. Although I cannot say 100% sure, that the device didn't accidently turn on in my luggage.

**Comment by fhorinek** [comment]
Thank you for the report. I will investigate this issue. Try to downgrade
to lower version.

**Comment by wrowland** [comment]
Thanks for the quick response.

**Comment by RomanKreisel** [comment]
I didn't try to reproduce it with 1278, but I upgraded to 1714 a while ago and tried to reproduce it for the last 2 weeks, but it seems like everything is ok now. Or it's just not easily reproducible.

**Comment by petesy** [comment]
SW 1773 board1504
Battery discard when off within 4 days from 100%  to 0%

**Comment by wrowland** [comment]
I also upgraded to 1714 and the problem seems to be resolved. 

Bill
