### ISSUE TITLE
USB Connection doesn't work on a Mac

### ISSUE THREAD

**Issue by wunderbaresnet** [fhorinek/SkyDrop#11]
Device reboots (blue-green-red-reboot) continuously.

**Comment by fhorinek** [comment]
Can someone post dmesg output for this?

**Comment by tomasz13** [comment]
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff802f96c200](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff8031483a00](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff8031cb1800](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff8031483a00](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff8033f30c00](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff802dbc1000](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff803c0e3000](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff8030f80e00](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff802dbc1000](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff8031cb1800](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff8033f52c00](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff8033f30c00](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff8031861e00](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff802cd5e200](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff8031c9ec00](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff802cd5e200](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff8033f30c00](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff8033fe8200](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1
[0xffffff8031483a00](1)/(5) Device not responding
USBMSC Identifier (non-unique): 13A463532333FFFF60FFD0003000 0x1209 0xd706 0x1, 1

**Comment by tomasz13** [comment]
that was a dmesg from OS X Yosemite 10.10.3

bash-3.2# uname -ap
Darwin MACi.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64 i386

**Comment by fhorinek** [comment]
there were no other messages when you plug the usb?

**Comment by tomasz13** [comment]
nothing else...
I tried it on both USB port...

**Comment by fhorinek** [comment]
I do not get it, I am using standard USB profile. It is working on Win, Linux and even on ChromeOS. I will have to find some mac for this

**Comment by fhorinek** [comment]
Can someone look on Settings->Debug->rst (first item on list) after unsuccessful connection. 
What is the reason of restart?

**Comment by fhorinek** [comment]
Will be fixed in next release
at least a bit. Device still act bit weird under mac
