### ISSUE TITLE
Skydrop dead

### ISSUE THREAD

**Issue by dnngll** [fhorinek/SkyDrop#110]
Hello,

my Skydrop is not working anymore. It was fine ever since, until now. No matter how long I press power, it won't boot. When connected to USB nothing happens, LED is off.

Installed firmware is 0322, I never tried to update or anything.

Please advise. Thanks,

Dennis

**Comment by fhorinek** [comment]
try to charge it for hour or so using different usb cable, if the problem persist we will replace the unit

**Comment by dnngll** [comment]
Hello,

thanks for the quick reply. I tried with several different cables and chargers, nothing happening.

For replacement, do you have a label that I can print?

Regards,



Dennis

**Comment by fhorinek** [comment]
Please send us the message to info@skybea.eu

**Comment by dnngll** [comment]
Hello,

I did send an Email 8 days ago - still no reply!

**Comment by dnngll** [comment]
Thanks for the reply (see below) and the good support. Lookking forward to flying again with Skydrop : )


Dear Dennis,

We are very sorry to not respond. We must have overlook your mail. 
Your device must be send back to us for repair. 
As you had to wait so long I can offer you faster way. We will send you a new one immediately. You send broken one back to us to this address:
SkyBean
Martin daricek
Drobneho 21
84101 Bratislava 42
Slovakia

Is it ok for you?

We are very sorry for such late answer.

Best regards

--
Lýdia Kotríková
