### ISSUE TITLE
Gps speed widget is not accurate

### ISSUE THREAD

**Issue by msaraceno** [fhorinek/SkyDrop#111]
Yesterday I was play around and I noticed the gps widget does not update the speed during flight: It was stuck at 31 kmh, with and without speed bar, heading on any direction (the wind was consistent at 15 kmh...). It was wired. Once back home I reviewed the GPS log and i noticed it showed a 
much more reasonable picture of the situation: Speed varied based on direction and speed bar.
FW 1714 beta
I turned on the skydrop when I was flying 
Thanks

**Comment by fhorinek** [comment]
please attach ee.cfg and flight log

**Comment by msaraceno** [comment]
Here you go:

ee.cfg:
https://dl.dropboxusercontent.com/u/1695127/CFG.EE

Log
https://dl.dropboxusercontent.com/u/1695127/02-1112.IGC

**Comment by fhorinek** [comment]
do you have also the debug.log?
BTW i think that you can attach files directly on GitHub

**Comment by jarda-manana** [comment]
You can't if you don't have write privileges. Only images are allowed..

**Comment by msaraceno** [comment]
Debug log: 
https://dl.dropboxusercontent.com/u/1695127/DEBUG.LOG

I am not able to attach such files inhere.

**Comment by msaraceno** [comment]
Today I tried again. This time the GPS widget did not show any speed at all ...
https://dl.dropboxusercontent.com/u/1695127/8-11.zip

**Comment by fhorinek** [comment]
@msaraceno with 1773beta?

**Comment by fhorinek** [comment]
Fixed using more precise GPS timing.
