### ISSUE TITLE
No reply from your device support / service!?!? 

### ISSUE THREAD

**Issue by pturri** [fhorinek/SkyDrop#112]
As agreed, I sent the device for service (at my charge....), but courier can't find the given address!!   (Drobneho 21 84101 Bratislava), that is also different from contact address on the website (Opalova 5/A 85101 Bratislava).

Furthermore, there are no phone numbers, anywhere. 

I sent you 2 mails asking to confirm a correct address AND a contact phone number for the courier but nobody replied.

A BIG MESS

In 24 hours the courier will return the package back, so I'll get my SkyDrop back unserviced and to i'll have to pay the courier for nothing.....

**Comment by fhorinek** [comment]
I did answer you via email. Did you got the message?
