### ISSUE TITLE
1773beta values stuck after take off detection

### ISSUE THREAD

**Issue by jarda-manana** [fhorinek/SkyDrop#113]
After take off detection the device semi-freeze: you can change pages, but vario related numbers disappears (see picture) 
![2015-11-12 05 59 07](https://cloud.githubusercontent.com/assets/676754/11111253/6b4f7d28-8907-11e5-9cb0-e2de01f50090.jpg)
and the device plays same uninterrupted tone (if there was any in this moment).
Hw rev. 1504, fw 1773. Logs: https://www.dropbox.com/sh/89rpwhy08gk9wf8/AAA5yAKJH1clgXu4d3zMAndwa?dl=0 (Pls take a look on date in logs - the fw was upgraded in 11. 11. afternoon)

**Comment by ZIRminator** [comment]
my device stucks as well in the menu and making strange voices with 1773beta. it is fine with 1714beta.

**Comment by fhorinek** [comment]
@jarda-manana send me your device for autopsy. Write us message to info@skybean.eu

**Comment by jarda-manana** [comment]
message sent, I'll send the device on Monday morning. thanks @fhorinek

**Comment by ZIRminator** [comment]
Skydrop turns off or stucks since 1773beta but the most annoying thing is the sound.
here is a demonstration... especially when you turn it on/off or in the menu:

https://dl.dropboxusercontent.com/u/29303320/IMG_8720.MOV

**Comment by fhorinek** [comment]
@ZIRminator I am confirming this sound bug, using @jarda-manana drop :)

**Comment by ZIRminator** [comment]
@fhorinek is that a bug with some particular devices or just a fw bug? If its only a fw bug, are you going to fix it in the next update? Is it going to be in the next two weeks? thx

**Comment by fhorinek** [comment]
if is fw bug, and I am hunting it right now.

**Comment by ZIRminator** [comment]
good hunting bro! :ok_hand:

**Comment by fhorinek** [comment]
Solved, in next release (both funny sound and invalid values)
