### ISSUE TITLE
Landing detection

### ISSUE THREAD

**Issue by colignym** [fhorinek/SkyDrop#114]
I have two skydrops.  They are configured identically, from the same file.
1 - The one(one of the first drops) detects landing, and shows max values.   The second (one of the latest ones) detects landing and switches off.  - BUG

2 - When landing and showing max values, there is no way to reset flight time, and be ready for next flight, besides switching off the drop.
I suggest, that on new take off detection, it resets flight time to zero, and start new recording. - Enhancement      

3 - IGC logs Greenwich time, does not take my time zone in account, even though it is set correctly on drop. - enhancement/bug?

**Comment by fhorinek** [comment]
1. Does it detect landing and then switches off? There is a auto-poweroff functions in newest beta release
2. For now you can reset flight using Flight Time widget using long press (Ready->Flying->Landed->Ready-> ... )
3. By IGC standard is mandatory using UTC time/date

**Comment by colignym** [comment]
Thanks,
Yes it detects landing, and switches off even before I can check max values.
Please implement the landing reset on new launch.  It will simplify matters tremendously.

**Comment by fhorinek** [comment]
It turns off with the logo or it just turn off  the display?

**Comment by colignym** [comment]
Can't seem to get it to repeat the problem.......eish.  did it on Monday, and Tuesday, now I report and it seems ok.

**Comment by fhorinek** [comment]
...this happens every time you try to locate the bug :)

**Comment by fhorinek** [comment]
Need to know the method to recreate this issue

**Comment by colignym** [comment]
Me and my son flew with the skydrops on Saterday.  I landed after 1 and 1/2 hour.  It detected landing then switched off.  My son landed after 1 hour 45 minutes.  Same thing happened within 2 minutes of landing.   There is some bug.

**Comment by IB0S** [comment]
This happened with one of my SkyDrops also.
It certainly turns off with the animated logo when it detects landing (no max values). Log and everything else seems to be in place and are fine. (It did it with 1773b, now I'm on 2052b and haven't tried it with that.)

**Comment by fhorinek** [comment]
just to be sure, right after the landing?

**Comment by IB0S** [comment]
well, a couple of seconds. I just got out of my harness looked at my SkyDrop to check if it detects landing (and watching if it turns off again as the last time) and then it turned off with the logo animation when I was seeing it (without showing max values or anything).
In a second before it was like I'm flying and the next second it turned off this way that's why I'm thinking that it's connected to the landing detection in some way.

**Comment by IB0S** [comment]
maybe a state or condition so when it detects landing the auto power-off timer was already counting down prior to landing (due to long flight or something) and after landing there's already zero time left before auto power-off? just guessing

**Comment by fhorinek** [comment]
I think that I found it.
The problem was that timeout was reset only if you click the buttons.
And the power off was detected when you are not in flight.
I guess that all my flight was shorter than 45 minutes since I add this feature :(
Anyway fixed in next release.

**Comment by IB0S** [comment]
great, thanks! :) and wish you long flights ;)

**Comment by fhorinek** [comment]
update is out
