### ISSUE TITLE
IGC Filenames not according to IGC Specification

### ISSUE THREAD

**Issue by RomanKreisel** [fhorinek/SkyDrop#116]
Even though the filenames were already discussed in #100, I think they should comply with the IGC-Specification:
http://carrier.csi.cam.ac.uk/forsterlewis/soaring/igc_file_format/igc_format_2008.html#link_2.5

I have no personal preference if short- or longnames are used. Both have Pros and Contras: Short filenames are 8.3-compatible, the long ones are human-readable.

Regards
Roman

**Comment by fhorinek** [comment]
Filename is not important, according the guys from FAI CIVIL. But give me a good reason why should we use them instead of human friendly names and I will implement such option.

**Comment by RomanKreisel** [comment]
If this is not the problem for #117, I don't care much if the filenames are compliant with the IGC spec ;)
