### ISSUE TITLE
IGC files cannot be uploaded to DHV-XC

### ISSUE THREAD

**Issue by RomanKreisel** [fhorinek/SkyDrop#117]
The IGC files generated by rev. 1714beta currently are incompatible with http://www.dhv-xc.de.
I'm reporting this issue without having it checked against the already-released 1773beta - because the changelog doesn't mention any IGC-Changes.

After upload, dhv-xc responds with:
> Bei der Übermittlung des Fluges ist ein Fehler aufgetreten (translated: Error during transmission of the flight)
> 
> The date of the flight is in the future
> Please use the Year-month-day not the US Year-day-month format

I already tried to correct the filename of the IGC according to Specification (see #116) but it didn't help. I also checked the content of the IGC, but I didn't detect Y-D-M anywere. So i'm not really sure if this is an SkyDrop-Issue or an Leonardo-Issue (The software used by DHV-XC).

**Comment by fhorinek** [comment]
can you post here the H-records of the IGC file?

**Comment by RomanKreisel** [comment]
Hey, of course, here is the header:

> AXSBDRP:314A363532330611000800
> HFDTE051215
> HFDTEDATE:051215,01
> HFPLTPILOTINCHARGE:
> HFCM2CREW2:
> HFGTYFLIDERTYPE:
> HFGIDGLIDERID:
> HFRFWFIRMWAREVERSION:build 1714
> HFRHWHARDWAREVERSION:drop_1504
> HFFTYFRTYPE:SkyBean,SkyDrop
> HFGPSRECEIVER:Quectel,L80,22cm,18000m
> HFPRSPRESSALTSENSOR:Measurement specialties,MS5611,25907m
> HFFSP:AL4
> HFALGGEO
> HFALPISA

**Comment by wunderbaresnet** [comment]
Same with 1773.

**Comment by fhorinek** [comment]
Looks like that Leonardo have problem with the HFDTEDATE record. It it from the new IGC specification AL4. We will remove the record in next release until they correctly implement the IGC parser.

**Comment by RomanKreisel** [comment]
I can confirm this: after removing the HFDTEDATE record, the file can be uploaded.
It still complains about an invalid G-Record, but at least the flight book function is now working :)

**Comment by biseinerweint** [comment]
How can the HFDTEDATE record be removed?
...I've got the same problem here. Can't upload my flights to leonardo/DHV-xc because of date-problems. :(
Thanks for your help!

**Comment by fhorinek** [comment]
You can open the IGC file using any text editor and then remove the whole line starting HFDTEDATE. It will break the G-code signature but leonardo/DHV-xc will accept them.
