### ISSUE TITLE
Can't connect via bluetooth

### ISSUE THREAD

**Issue by wunderbaresnet** [fhorinek/SkyDrop#118]
I have a Dell Streak 5 with XContest or XCsoar.
SkyDrop FW 1733, BT Pan1322, 2.1, Protocol DigiFly
The device pairs with the Pan1322, I can select it in both applications, but it won't connect.
What am I doing wrong?

Thanks.

**Comment by fhorinek** [comment]
You need to manually set protocol in XCsoar. 
For XContest set protocol in SkyDrop to LK8EX1

**Comment by wunderbaresnet** [comment]
Still no luck.
XCsoar simply outputs "error". XContest just won't connect.
I have a second SkyDrop, I'll try with that later.

**Comment by wunderbaresnet** [comment]
So... One works, the other doesn't. It is one of the very first devices... Now what?

**Comment by wunderbaresnet** [comment]
Maybe there is a general problem. I got it working ONCE, but I don't know exactly how. Now, I can't get it to work again.

Dell Streak 5, Android 2.3 (Olleh, no newer version available).
- Pair with SkyDrop: works
- Connect with SkyDrop in System Settings: connect, disconnected - won't stay connected
- Open XContest (SkyDrop set to LK8EX1): worked once, never again since
- Open XCSoar (SkyDrop set to BlueFly, Protocol Bluefly set in XCSoar): Error connecting

Maybe my BT HW is outdated (devices from the very first batch)?

Any help appreciated.

**Comment by wunderbaresnet** [comment]
https://vine.co/v/iZpr1Q9ZDF9 

Device constantly connects and disconnects.

**Comment by fhorinek** [comment]
Is this with newest update?

**Comment by wunderbaresnet** [comment]
yes.

**Comment by wunderbaresnet** [comment]
Just a comment: My BlueFly Vario connects just fine.

**Comment by fhorinek** [comment]
Ok try to update and if that did not work send the device back for autopsy. You will get new one.

**Comment by wunderbaresnet** [comment]
More tests...
First, sorry, I meant the XCTrack app, not XContest. XCTrack still does not connect (or only very occasionally, not reproducable), neither does XCSoar (Error connecting).

So XCTrack, probably the best XC App, won't work for me. I'd expect the SkyDrop to connect automatically when I open the app, without further ado. At start, I don't have time/patience to wurschtel with my electronics...

Tested the BlueFly App (set SkyDrop to BlueFly) - works perfectly.
Also FlyMe works with SkyDrop set to BlueFly.

So I am fine by now, I'll use FlyMe for now.
