### ISSUE TITLE
Skydrop all of a sudden very sluggish, build 1714 / rev 1504

### ISSUE THREAD

**Issue by ganzenmg** [fhorinek/SkyDrop#120]
My Skydrop all of a sudden has become  very sluggish.

For example, when I press the center key to bring up the menu, the menu slowly appears over 4 secs, whereas that used to happen instantly after a certain delay.
When I try to navigate the menu, key presses are only occasionally registered.

USB connection to computers does not work anymore. I tried 3 different computers. The disk is not detected as a valid filesystem anymore.

Any suggestions?

**Comment by fhorinek** [comment]
Format the sd card and update to 2054.
