### ISSUE TITLE
Question: ADDED:  * 32MHz oscillator used as main clock calibration using ext 32KHz TOSC

### ISSUE THREAD

**Issue by tomasz13** [fhorinek/SkyDrop#121]
What does it mean:
ADDED:
 * 32MHz oscillator used as main clock calibration using ext 32KHz TOSC

**Comment by fhorinek** [comment]
Skydrop mcu does not have external crystal clock. It is using 32MHz on chip RC oscillator.
RC oscillators are not as precise as the crystals. With time and temperature change can frequency drift from defined frequency and then it may mess up the timing with gps, bt module or sensors.

We do have precise on board clock crystal, so we are using it as reference for the main clock.
