### ISSUE TITLE
2074

### ISSUE THREAD

**Issue by colignym** [fhorinek/SkyDrop#123]
I loaded my cfg file into the configurator, to retain all my settings.  I then updated my drop to 2074.  In the configurator it asked if I wanted to upgrade to 2074 which I did.

I then saved update.ee to my drop.  Longpress right arrow as usual.  It then tells me update.ee not compatible?

What am I doing wrong?

**Comment by fhorinek** [comment]
Send me the update file

**Comment by fhorinek** [comment]
the update file you send me was not updated. But even if it was the new configurator had some bugs. Thank you for notify.
Please try it again
Load old configuration (CFG.EE, OLD.EE) -> click to upgrade -> Save

**Comment by colignym** [comment]
thanks, but 2078 does not appear at the update files list

On Wed, Dec 16, 2015 at 9:56 AM, František Horínek <notifications@github.com

**Comment by fhorinek** [comment]
my bad, try it now

**Comment by colignym** [comment]
Eish,

Did not give error, but when I unplug USB and start it up again, it comes
on, but switches off immediately again.

**Comment by fhorinek** [comment]
uff please disable debug.log for now. I will investigate this further

**Comment by fhorinek** [comment]
http://vps.skybean.eu:8080/repo/updates/2097beta/
you can now use debug.log

**Comment by colignym** [comment]
Did latest update.  pulled old cfg into configurator,  upggraded to latest,
then saved to drop.

UDATE.EE not compatible.......

On Wed, Dec 16, 2015 at 4:36 PM, František Horínek <notifications@github.com

**Comment by colignym** [comment]
Must add, the configurator does say upgrade to 2078.

On Wed, Dec 16, 2015 at 4:36 PM, František Horínek <notifications@github.com

**Comment by fhorinek** [comment]
I am terrible developer.... fixed
