### ISSUE TITLE
vario sound

### ISSUE THREAD

**Issue by geri34** [fhorinek/SkyDrop#124]
the sound of my skybean  doesn`t work in the variomodus
in the testmodus it works, but in normal modus not.
all other sounds are okay.

**Comment by fhorinek** [comment]
You need to change your altitude by 4m to enable sound. Or you can disable
suppres audio in autostart settings.

**Comment by geri34** [comment]
Sorry. But thats not the problem. I know the fact, that i have to change the altitude.
My skybean variosound only works with the release of october. Now i haven't the bluetoothfunction.
I hope for a softwareupdate, that includes all improvements.
Gerhard

**Comment by fhorinek** [comment]
What is the firmware first version when it is not working?

**Comment by fhorinek** [comment]
Houskeeping
