### ISSUE TITLE
flight log

### ISSUE THREAD

**Issue by MatthewVanZyl** [fhorinek/SkyDrop#125]
hi there, complete  newbie here, please explain when sky drop logs flights and what information it captures, please tell me how I view my logged flights, when I plug the device into laptop it has cant read this file

**Comment by fhorinek** [comment]
The logging will start right after skydrop detects tak-off. Logs are stored on sd card (accessible via USB massstorage). You need to upgrade to latest firmware to be have compatible IGC G-record. 
It stores GPS position, GPS altitude and Baro altitude (IGC) or GPS position and GPS alt (KML).
IGC is format used in competition a XC servers. KML files can be opened using Google earth.

**Comment by MatthewVanZyl** [comment]
i updated to http://skybean.eu:8080/repo/updates/1278/ but i dont get any .KML file.
I only get CFG.EE file on the SD card

**Comment by fhorinek** [comment]
Please update to http://skybean.eu:8080/repo/updates/2097beta/
