### ISSUE TITLE
log issue

### ISSUE THREAD

**Issue by ZIRminator** [fhorinek/SkyDrop#126]
Last week I had many flights with the Drop. A few days ago I tried to read the IGC files and everything was ok but now it turns off and on a couple of times when you plugg the PC connection and the folder "G:\LOGS\2015\12" is not accessable anymore :-(
"The file or directory is corrupted or unreadable"

On mac its not even listed!
Does somebody have the same problem? How to fix it? It is a pity because of my long flights in spain :-(

current fw: 2052beta

**Comment by fhorinek** [comment]
I would suggest to reformat the sd card. 

But in case of sensitive data. Try to remove the card from skydrop and run checkdisk or http://www.cgsecurity.org/wiki/PhotoRec to recover data first.

Anyway Sorry for your loss :(.
