### ISSUE TITLE
looks good bur never works, waste of time

### ISSUE THREAD

**Issue by whu4411** [fhorinek/SkyDrop#129]
after months of waiting upgrading, downgrading, testing
all this wasting of time, i figured out that i should just buy a real device
you made me a proposal and now ask me  to send it first
just feel like having my money back instead all this trouble

**Comment by fhorinek** [comment]
Please email your request to info@skybean.eu

**Comment by whu4411** [comment]
sorry but after months of frustration i got pissed
but just got my new drop and its working perfectly!
thanks

**Comment by fhorinek** [comment]
No hard feelings, if it doesn't work complain. I would do the same :)

**Comment by whu4411** [comment]
good to know! in the end we all fly in the same sky!
best regards!

2016年1月27日水曜日、František Horínek<notifications@github.com>さんは書きました:

> No hard feelings, if it doesn't work complain. I would do the same :)
> On Jan 27, 2016 02:41, "whu4411" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > sorry but after months of frustration i got pissed
> > but just got my new drop and its working perfectly!
> > thanks
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/fhorinek/SkyDrop/issues/129#issuecomment-175334510>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fhorinek/SkyDrop/issues/129#issuecomment-175403163>.
>


-- 
臼井 秀夫 Hideo Usui
whu4411@gmail.com
