### ISSUE TITLE
Feature Request: Redefine Buttons

### ISSUE THREAD

**Issue by wunderbaresnet** [fhorinek/SkyDrop#13]
At least the middle button should be configurable (short press), e.g. mute would be really important for me. Left and right might also get more functionality. I would like to see a PC configurator for these kind of things...

**Comment by fhorinek** [comment]
Short press of the middle button let you change altimeters widgets and others will be configurable as well. I am thinking about configurable shortcuts for every button using double click.

**Comment by tomasz13** [comment]
I think so, the EZ mute is a good feature.

**Comment by atomphil** [comment]
Long press the middle (or left) button should be level-up in the menu.

**Comment by fhorinek** [comment]
@atomphil good idea!

**Comment by fhorinek** [comment]
level-up with long press is done
TODO:
shortcuts

**Comment by SonnenSimon** [comment]
keeping middle button long-pressed should get you back even further, till you exit the menu completely.

**Comment by SonnenSimon** [comment]
... and yes, quick shortcuts for mute and/or volume are quite important!

**Comment by fhorinek** [comment]
There is mute widget now it is enough?

**Comment by fhorinek** [comment]
implemented as silent page and widget
