### ISSUE TITLE
Skydrop dont start

### ISSUE THREAD

**Issue by Zzorro111** [fhorinek/SkyDrop#130]
Since i used my skydrop for one time, i cant start it anymore. No lights, no screen - nothing... Same thing after one night connecting to power adapter. Also connected there are no charging-lights. I tried with different chargers/cables. Updating not possible... Do you have a solution?

**Comment by fhorinek** [comment]
try to open the case
disconnect the battery
format sd card on pc
place UPDATE.EE and UPDATE.FW on sd card from http://vps.skybean.eu:8080/configurator/fw/00002222/
reinsert the sd card
reconnect the battery

**Comment by Zzorro111** [comment]
Allready tryed before my first message... with no success! 
Once again today with the attached link - Still nothing...

**Comment by fhorinek** [comment]
Did you solve your issue? If not I think you will need to send it back to us.

**Comment by Zzorro111** [comment]
I Sent it back more than a month ago... I Sent it to the Following Adress:
SkyBean Orglabs s.r.o.
Opalova 5/A
Bratislava 85101
Slowakei
I asked Nika for a confirmation and wrote you to get some informations... Still have no device and no answer... Im really not happy and till now i cannot recommend skydrop to anyone... I also asked for the Riser Mount for Skydrop... No answer......

**Comment by fhorinek** [comment]
I forwarded this message to Nika. I will keep eye on this issue now. You
will have answer tomorrow.

**Comment by fhorinek** [comment]
Can you send your name, email address and link to this issue to info@skybean.eu

**Comment by Zzorro111** [comment]
I still have no information, answer neigther a device :-(
