### ISSUE TITLE
configurator

### ISSUE THREAD

**Issue by colignym** [fhorinek/SkyDrop#131]
Hi,

I want to update to 2222 but, I load current drop configuration to configurator, when I upgrade to 2222 it wipes configuration back to default.   

In short, I can't upgrade without losing my personal configuration.

**Comment by fhorinek** [comment]
send me the ee file

**Comment by colignym** [comment]
When I import the cfg file into the configurator, all displays as it
should.  The problem comes, the moment I upgrade the configurator to 2222,
it resets all values, even before I want to save it.  No use to generate EE
file, as all the values has been reset already.

Regards

**Comment by fhorinek** [comment]
fixed try refresh

**Comment by colignym** [comment]
Thanks,

Works now.

Unrelated, but the drop has a big delay between movement and actual sound
coming through.  I can move it up and see the climb on the screen
immediately, but the sound is sometimes delayed by 1 sec or more.

Any setting for this filter?

Regards

On Wed, Jan 27, 2016 at 1:39 PM, František Horínek <notifications@github.com

**Comment by fhorinek** [comment]
Please go here #132
