### ISSUE TITLE
Sound delay

### ISSUE THREAD

**Issue by fhorinek** [fhorinek/SkyDrop#132]
The drop has a big delay between movement and actual sound
coming through.  I can move it up and see the climb on the screen
immediately, but the sound is sometimes delayed by 1 sec or more.

Any setting for this filter?

**Comment by fhorinek** [comment]
Are you using custom audioprofile?

**Comment by colignym** [comment]
Yes I am, and the lift threshold is 0.1.
I checked it again, and I see the main problem is when I move down, then up.  lets say it shows -0.6. Then when I reverse and go up again it first goes through the numbers back to zero and positive.  That's when the delay happens.

**Comment by fhorinek** [comment]
Please send me the configuration, because standard audio profile is working fine. Mail is frantisekhorinek@gmail.com

**Comment by fhorinek** [comment]
Could not reproduce the delay, but I place some force update on vario change, try this
[SKYDROP.FW.zip](https://github.com/fhorinek/SkyDrop/files/107952/SKYDROP.FW.zip)
Your profile is already there, this version will not work with public configurator. 

If you can manage to reproduce the delay with this FW please make a video.

**Comment by colignym** [comment]
Hi,

It's more or less the same.  If I just lift vario, it responds well.  If I
quickly go down 1m and directly up again, it has a frustrating delay.

Regards

**Comment by fhorinek** [comment]
The vario value or sound only?
Because until we figure out the accelerometer fusion, we will have to rely only on baro. And the filter have some delay.

**Comment by colignym** [comment]
Well, both

What happens, if I drop it quickly and get to say -0.6  and I reverse, it
needs to count back -0.5   -0.4  -0.3  etc. and only starts sound at +0.1
   so it sensis I'm moving in the opposite direction, but sound starts at
0.1 only.   If it could jump straight from -0.5  to + 0.1 or more, this
would solve the problem.

**Comment by fhorinek** [comment]
This behavior is standard. The delay you are experiencing is caused by barometer's kalman filter.
I can't have faster update rate without IMU implementation and that will take some time.
