### ISSUE TITLE
Is it a way to upload firmware from usb (without sd card usage) ?

### ISSUE THREAD

**Issue by vshama** [fhorinek/SkyDrop#133]
Hello,

I've a problem with my SDCard, but I want to test the vario with Flyme and logs can be on the android device. 

Under Linux the google APP never see a com port for upload. Actually I'm on the 0789 build.

Can I upgrade to the last one with usb ? Or eventually via uart pins ?

Regards
Vincent

**Comment by fhorinek** [comment]
The chrome app is for the different device, you can upgrade SkyDrop via usb
using it as mass storage device. Just copy the update files and restart the
device

**Comment by vshama** [comment]
Thank for your quick reply. Mass storage isn't a option to me since I broken the sdcard reader...

**Comment by fhorinek** [comment]
when you connect skydrop using usb cable it should act as mass storage

--
František Horínek

2016-01-31 17:50 GMT+01:00 Shama <notifications@github.com>:

**Comment by vshama** [comment]
I broke the cover of the SD card reader ... But taking up the hand I was able to update => thank you.
However I thought it would be loaded via the USB or serial port using a programateur

**Comment by fhorinek** [comment]
Unfortunately no.
The update function is done via small program in special section of memory. 
Its only function is to mount sd card, look for UPDATE.FW and the program the main memory. 
Since the ram or eeprom memory is not large enough for the update binary we have to use the sd card memory.

**Comment by vshama** [comment]
ok thanks
