### ISSUE TITLE
Feature Request - add battery level to log file

### ISSUE THREAD

**Issue by moyesboy** [fhorinek/SkyDrop#134]
Can the battery % be added to the log file at the beginning and end of flight. I think this can be added as text to the igc without and certification issues.
I would like to know how my battery is dong after a long flight but cant always remember what the % was.
Plus if it goes flat, it would be good to know if it was fully charged at the start!

**Comment by fhorinek** [comment]
I can put in in the comment section

**Comment by fhorinek** [comment]
done in next firmware release
