### ISSUE TITLE
Bluetooth iPhone

### ISSUE THREAD

**Issue by Altgenug1** [fhorinek/SkyDrop#136]
Hy,
I am one of the early birds and I have still no solution for the Bluetooth connection to an iPhone.
You told me that you will find a solution for us, but till now I got no info and the new season comes nearer every day.
Best regards
Erwin

**Comment by fhorinek** [comment]
Hi Erwin,

so far we are still not ready to use BTLE even with the newer boards (and therefore connect with iPhone), do not worry we will keep the promise and the early adopters will have the chance to upgrade bluetooth module.

**Comment by tomasz13** [comment]
ahoj,

Is there something new on this issue? thx

**Comment by fhorinek** [comment]
Nazdar, 

implementation of connectivity with an iPhone is almost done. Stay tuned!

**Comment by fhorinek** [comment]
iPhone bluetooth is connectivity is included in newest version

**Comment by Altgenug1** [comment]
Which version? It dosn't work with 3246.

**Comment by fhorinek** [comment]
It should, I need more info. What is your rev number and what Bluetooth module do you have?

**Comment by tomasz13** [comment]
I have the same problem... It is a Rev1504 pan1322v2.1 (I think this is the BTLE "early bird" model) 
Will we have the chance to upgrade a bluetooth module?

**Comment by fhorinek** [comment]
Sure you will, please write an request to info@skybean.eu :)

**Comment by Altgenug1** [comment]
Hy fhorinek, 
I am using Rev1506 pan 1026v4.0 and I have tested it with an iPhone SE, iPhone 6 and an iPhone 7plus.
I have tested it with 3244, 2346 and 3248, no success.

**Comment by fhorinek** [comment]
The flyskyhy app does not detect the device?

**Comment by Altgenug1** [comment]
I really don't now. 
The B on your Display is flashing (no connection), the Bluetooth information on the iPhone is showing no device. 
I have now tested it with flyskyhy - if I adjust the software -> Vario -> SkyDrop and the SkyDrop to SkyBean the flyskyhy softwar is showing me "SkyDrop BLE 6F85715D-02F1...-20833D62B89D" and I can choos it. Than the B is stopping flashing. But the high on the SkyDrop and at the flyskyhy is different.

**Comment by fhorinek** [comment]
We are only providing barometer information the actual altitude is computed based on QNH. You can have different QNH set on SkyDrop and FlySkyHy
