### ISSUE TITLE
Changes made using SkyDrop 2222 not saved

### ISSUE THREAD

**Issue by raymondpau** [fhorinek/SkyDrop#137]
Upgraded to version 2222.
Made the following changes which was not preserved.
1. Pilot Name
2. Glider Type
3. Glider ID
4. Timezone

**Comment by fhorinek** [comment]
How did you saved the values? The Pilot Name, Glider Type, Glider ID were not present in previous releases.

**Comment by raymondpau** [comment]
I upgraded to version 2222 and updated the values using SkyDrop.

**Comment by raymondpau** [comment]
Upgraded to version 2222 and use SkyDrop to key in these new values. 

Using the web configuration to generate the update.ee file works.

More importantly is the TimeZone value.

Also I need to take out the SD card and downgrade to the last stable version 1278 before I was able to upgrade to 2222. Dropping the latest SKYDROP.FW version 2222 using 1714beta did not start the upgrade process. 

I hope this information is useful to other trying to upgrade.

**Comment by fhorinek** [comment]
The bug is confirmed in 2222.

If you have a problem with sd card please try to format it using skydrop.

**Comment by fhorinek** [comment]
Fixed, thank you for the report
here is beta firmware
[SKYDROP.FW.zip](https://github.com/fhorinek/SkyDrop/files/132231/SKYDROP.FW.zip)
