### ISSUE TITLE
SkyDrop version 2222 IGC file invalid

### ISSUE THREAD

**Issue by raymondpau** [fhorinek/SkyDrop#138]
Tried uploading IGC files to Leonardo.
Error Message: This is not a valid .igc file

Content of IGC logs:
AXSBDRP:314A363532330612000500
HFDTE130216
HFPLTPILOTINCHARGE: not specified
HFGTYGLIDERTYPE: not specified
HFGIDGLIDERID: not specified
HFRFWFIRMWAREVERSION:build 2222
HFRHWHARDWAREVERSION:drop_1504
HFFTYFRTYPE:SkyBean,SkyDrop
HFGPSRECEIVER:Quectel,L80,22cm,18000m
HFPRSPRESSALTSENSOR:Measurement specialties,MS5611,25907m
HFFSP:AL4
HFALGGEO
HFALPISA
B0813490125463N10347618EA0005100079
B0813520125465N10347617EA0005100079
B0813530125465N10347617EA0005100079
B0813540125466N10347617EA0005100079
B0813550125466N10347618EA0005100075
B0813560125467N10347618EA0005100075
B0813570125467N10347618EA0005100075
B0813580125467N10347618EA0005100075
B0813590125468N10347619EA0005100074
B0814000125468N10347619EA0005000074
B0814010125469N10347619EA0005000074
B0814020125469N10347619EA0005000074
B0814030125470N10347619EA0005000073
B0814040125470N10347619EA0004900073
B0814050125470N10347619EA0004900073
B0814060125471N10347620EA0004800073
B0814070125471N10347620EA0004900072
B0814080125471N10347620EA0004900072
B0814090125472N10347620EA0005000072
B0814100125472N10347621EA0005000072
B0814110125472N10347621EA0005000071
B0814120125472N10347621EA0005000071
B0814130125472N10347621EA0005000071
B0814140125472N10347621EA0005000071
B0814150125472N10347621EA0005000070
B0814160125472N10347621EA0005000070
B0814170125472N10347621EA0004900070
B0814180125472N10347621EA0004900070
B0814190125472N10347621EA0004900070
B0814200125472N10347621EA0005000070
B0814210125472N10347621EA0005000070
B0814220125472N10347621EA0005000070
B0814230125472N10347621EA0004900070
B0814240125472N10347621EA0004900070
B0814250125472N10347621EA0004800070
B0814260125472N10347621EA0004900070
B0814270125472N10347621EA0005000070
B0814280125472N10347621EA0005000070
B0814290125472N10347621EA0005000070
B0814300125472N10347621EA0005000070
B0814310125472N10347621EA0004900070
B0814320125472N10347621EA0004900070
B0814330125472N10347621EA0004900070
B0814340125472N10347621EA0004900070
B0814350125472N10347621EA0004900070
B0814360125472N10347621EA0005000070
B0814370125472N10347621EA0005000070
B0814380125472N10347621EA0005000070
B0814390125472N10347621EA0005000070
B0814400125472N10347621EA0005000070
B0814410125472N10347621EA0005000070
B0814420125472N10347621EA0005000070
B0814430125472N10347621EA0005000070
B0814440125472N10347621EA0005000070
B0814450125472N10347621EA0005000070
B0814460125472N10347621EA0005000070
B0814470125472N10347621EA0005100070
B0814480125472N10347621EA0005000070
B0814490125472N10347621EA0005000070
B0814500125472N10347619EA0005000070
B0814510125472N10347619EA0005000069
B0814520125473N10347618EA0005000069
B0814530125473N10347618EA0005000069
B0814540125473N10347617EA0005000069
B0814550125474N10347617EA0004900068
B0814560125474N10347617EA0004900068
B0814570125474N10347616EA0004900068
B0814580125475N10347616EA0004900068
B0814590125475N10347615EA0005000068
B0815000125476N10347615EA0005000068
B0815010125476N10347614EA0005000068
B0815020125477N10347613EA0005000068
B0815030125477N10347613EA0005000067
B0815040125477N10347613EA0005000067
B0815050125478N10347612EA0004900067
B0815060125478N10347612EA0004900067
B0815070125479N10347611EA0004900066
B0815080125479N10347611EA0004900066
B0815090125480N10347610EA0004900066
B0815100125480N10347610EA0004900066
B0815110125481N10347610EA0004900066
B0815120125481N10347609EA0004900066
B0815130125482N10347609EA0004900066
B0815140125482N10347608EA0004900066
B0815150125483N10347608EA0004900066
B0815160125483N10347608EA0004900066
B0815170125484N10347607EA0004900066
B0815180125484N10347607EA0004900066
B0815190125484N10347607EA0004900065
B0815200125484N10347606EA0004900065
B0815210125484N10347606EA0004900065
B0815220125485N10347606EA0004900065
B0815230125485N10347605EA0004900064
B0815240125485N10347605EA0004900064
B0815250125486N10347605EA0004900064
B0815260125486N10347604EA0004900064
G8E0D97BACD27B5A41F2D78F15FB8D38245930579

**Comment by fhorinek** [comment]
What server are you using exactly? Please provide the url. 
The file is valid but it looks like that it is not using fai-civil validation server.

**Comment by raymondpau** [comment]
I'm using paragliding forum Leonardo server to keep track of my flights. 

http://www.paraglidingforum.com/modules.php?name=leonardo&op=login

**Comment by fhorinek** [comment]
the main problem is that your short track is not accepted by inner logic of the leonardo server. No altitude change, to take off / landing point.
I have also asked the developers for adding our G-record validation program.
