### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by skyhiflyguy** [fhorinek/SkyDrop#139]
my skydrop does not show as a disk drive on win 10 so I cannot update it.It does come up in devices however.

**Comment by fhorinek** [comment]
You can try to disassembe the device and pull out the sd card and copy the update files manually to the sd card.

Please be careful and do not torn out the battery, you can damage the sd card holder.

**Comment by skyhiflyguy** [comment]
OK I canmove the files FW to the sd card, now what steps need be taken to apply update?

**Comment by fhorinek** [comment]
If you have skybean.fw on the sd card, just turn on the vario. 
There should be confirmation screen like this:
![image](https://cloud.githubusercontent.com/assets/9072684/13244141/42d525ca-da04-11e5-88a5-de1677754e0e.png)

**Comment by skyhiflyguy** [comment]
It doesn't come up with that. The display flickers and fades. I formatted the card and moved 2235/skydrop.fw to it but nothing happens except for red light which is sometimes green.  The computer will not recognise the skydrop but it does the card.  Iam spewing as I have a competition on this week.  I appreciate your assistance

**Comment by fhorinek** [comment]
Did you copy rst_ft to the sd card?

**Comment by skyhiflyguy** [comment]
I have not.  
Where is this situated? Bootloader? Or update repo?

**Comment by fhorinek** [comment]
it is looks like that you have somehow triggered the factory test reset.

The fading display is just contrast test.
You need to setup the display contrast range.
First press the middle button when is something barely visible on the screen
than you can adjust the lower contrast value using left and right button
confirm it using middle one

then repeat process with the maximum and optimal contrast value

then confirm it using middle button.
Now you have set the contrast range

When you see system peripheral check, just press every button and you will
pass

good luck



--
František Horínek

2016-02-24 1:08 GMT+01:00 skyhiflyguy <notifications@github.com>:

**Comment by skyhiflyguy** [comment]
Ok ofollowed the video and got the rst_ft from earlier  and moved it to SD  and it still  fails. Would it matter that i am doimg this on android tablet  and that when it formats it retains two files by default. Android and Lost. Dir.

**Comment by skyhiflyguy** [comment]
when I reconnect the battery I get one rapid red blink on the led.Isthis significant?

**Comment by skyhiflyguy** [comment]
please see attached video and tell me if this is as it should be...https://youtu.be/XNzwZQvDHdk

**Comment by fhorinek** [comment]
No is should not blink like that. 

But I see that you manage to install some firmware. 
Now apply http://vps.skybean.eu:8080/repo/updates/2235/SKYDROP.FW

or you can use this unpacked version
[00002235.zip](https://github.com/fhorinek/SkyDrop/files/144099/00002235.zip)

**Comment by skyhiflyguy** [comment]
That firmware was installed before I started having problems.I once again installed 2235 and there is no change in the behaviour of the skydrop.

**Comment by fhorinek** [comment]
Can you try to enable debug.log?
Menu->Debug->debug.log
Then reboot the vario, turn it off again 
and then send me the debug.log file from sd card.

**Comment by skyhiflyguy** [comment]
no new files appear after debug. This is what I did; turned on; held down centre button until the menu option came; selected menu; scrolled down to debug; ticked thebox;  went back ; held down centre button until on/off;turned off; restarted; turned off; removed sd and put it in the  computer
![untitled](https://cloud.githubusercontent.com/assets/17306410/13286424/4d950f3c-db3c-11e5-8399-104bd45f96fe.png)
these are now the file on SD

**Comment by fhorinek** [comment]
looks like that sd card is unable to mount , because otherwise there will be no update files. 
SkyDrop removes applied files.
What happened when you turn on the drop without the sd card? Does it run fluently?
Try to do full format using fat32 on PC.

**Comment by skyhiflyguy** [comment]
it seems to run better without the SD card :)  I also have a spare SD I shall format both and see how we go

**Comment by skyhiflyguy** [comment]
righto which files Should i put on, ? rst-ft?

**Comment by fhorinek** [comment]
no, just SKYDROP.FW


--
František Horínek

2016-02-24 14:52 GMT+01:00 skyhiflyguy <notifications@github.com>:

**Comment by skyhiflyguy** [comment]
ok, the performance with the sd card in is the same as before, including the flashinglights which do not occur with  th card unmounted. The othe SD card I thought I had  seems to bef ucked as it doesnt read on the  comp

**Comment by fhorinek** [comment]
so there is a problem with the memory card or memory slot.

Please take a look at the card holder if it ain't damaged. Or you can try different card. But since we are not able to use SDHC it can only accept card smaller than or equal to 4Gb.

**Comment by skyhiflyguy** [comment]
There is no obvious damage to the card holder.  I shall purchase a new card on my way to the comps today and try it out. I shall be away for six days at least during which time I shall try some more ,but I think it may need to come back to you for a service or inspection.

**Comment by fhorinek** [comment]
ok, if that does not work we will replace the device for a new one

--
František Horínek

2016-02-26 3:12 GMT+01:00 skyhiflyguy <notifications@github.com>:

**Comment by skyhiflyguy** [comment]
I was not able to make it work with a new card  I had a technician inspect the card holder with magnifier but could see no damage. I shall return this to you for you to hopefully Analise.

**Comment by fhorinek** [comment]
Sure no problem, can I have your email address, so we can resolve the RMA

--
František Horínek

2016-03-07 0:32 GMT+01:00 skyhiflyguy <notifications@github.com>:

**Comment by skyhiflyguy** [comment]
my email is; austinmeyer9@protonmail.ch

many thanks
