### ISSUE TITLE
Q: G record approval

### ISSUE THREAD

**Issue by IB0S** [fhorinek/SkyDrop#140]
Hi!

Is there any news on G record validation approval process? (FAI CIVL open validation, XContest etc.)
Thanks!

**Comment by fhorinek** [comment]
Fai civil is approved

**Comment by moyesboy** [comment]
I'm not sure what level of approval this is and what it means.
I understand I can use the igc for a competition where the scorer is willing to accept it.
But could the skydrop IGC now be used to claim a world record for example?

**Comment by fhorinek** [comment]
No you can't use IGC file for claiming world record. We are unable to meet
the criteria for that. But we do have certification from FAI-civil (open
validation server) and also recently from leonardo.

**Comment by fhorinek** [comment]
SkyDrop IGC is accepted for FAI Category 1 competitions
http://www.fai.org/component/phocadownload/category/?download=11362:cat-1-instruments-2016-07
