### ISSUE TITLE
feature request: shutdown the screen

### ISSUE THREAD

**Issue by tomasz13** [fhorinek/SkyDrop#141]
we can connect the skydrop to external device and use it with xctrack, xcsoar of flyme. when i use it with that external screen, i would like to switch off the the skydrop's screen, because i would like a longer battery life.

there would be nice to have a widget for switch off the screen... after it press any key to switch on

**Comment by fhorinek** [comment]
I do not think that will work since bluetooth take 200% more power than display :). But if you insist you can make one widget layout with empty widget.

**Comment by tomasz13** [comment]
is empty screen like a switched off screen? does not consuming power? that’s way it is OK. :)

**Comment by fhorinek** [comment]
Nearly the same
