### ISSUE TITLE
battery charging

### ISSUE THREAD

**Issue by chrision** [fhorinek/SkyDrop#142]
my new SkyDrop is not charging properly. As soon as I connect it to a USB charger it switches immediately into the USB mode but the led remains off. After a short time it shows batt 100% but if I unplug the cable the battery is only at about 40%. If I connect it to PC the LED is green.
I have tried different cables and chargers and have the firmware already twice restored. FW 2235, rev 1506.

**Comment by fhorinek** [comment]
The leds are currently used only to signalise usb communication. 

Also the battery charging circuit was not yet properly parametrised. The percentage during usb power are only informative. It takes ~2 hours to charge from zero.

**Comment by chrision** [comment]
Ok, thanks for the info and the quick reply. 

CS iPhone

**Comment by fhorinek** [comment]
no problem
