### ISSUE TITLE
Corrupt KML logs

### ISSUE THREAD

**Issue by Naycon** [fhorinek/SkyDrop#143]
Yesterday I logged three flights using my SkyDrop, configured to produce KML-files. However, the coordinates in the <coordinates> tag of the KML-file seem to be corrupted. Here's a small example (complete file attached below) of what the file looks like:

```xml
<kml xmlns="http://earth.google.com/kml/2.0">
<Document>
<name>Flight log from 25.02.2016 @ 11:36</name>
<Placemark>
<name>Flight</name>
<visibility>1</visibility>
<open>1</open>
<Style>
<LineStyle><color>ff00ffff</color></LineStyle>
<PolyStyle><color>7f0000ff</color></PolyStyle>
</Style>
<LineString>
<altitudeMode>absolute</altitudeMode>
<extrude>1</extrude>
<coordinates>
€,,313
€H,,314
,?^û,313
µH,,312
€H,,312
Bm,r,314
™H,,315
Bm,,315
Bm,d,313

*** MANY MORE CORRUPT LINES ***

Bm,Ù
,247
%2,À@%@,247
%2,,247
</coordinates>
</LineString>
</Placemark>
</Document>
</kml>
```

I'm guessing this is not the intended format of a KML-file. I tried uploading the file to a couple of places (Google Maps for example) and they all claim the file is invalid. Could you have a look at this and, if possible, could you find a way to decorrupt my files? I'm guessing maybe the issue is a simple missalignment in how data is written or something similar, which would make it possible to decorrupt my logs.

Here are three full examples of logs:
https://www.dropbox.com/s/3f6mt4lzmc7zymr/01-1136.KML?dl=0
https://www.dropbox.com/s/y7xnwv6jxyo0ojl/02-1213.KML?dl=0
https://www.dropbox.com/s/aznvcvzthabg8vu/03-1408.KML?dl=0

**Comment by fhorinek** [comment]
Definitely corrupted, what is build number

**Comment by Naycon** [comment]
Latest build I think, build 2235. The comment was cut off from the KML by GitHub, but here's what the file says:
```
Generated by SkyDrop vario (www.skybean.eu)
DATE: 25.02.2016
TIME: 11:36
HW: drop_1506
SW: build 2235
```

**Comment by fhorinek** [comment]
Bug found, fix will be deployed in next build. Thank you for your report!

**Comment by Naycon** [comment]
Is there any chance it would be possible to fix my logs, or are they beyond repair?

**Comment by fhorinek** [comment]
http://vps.skybean.eu:8080/repo/updates/2239/

**Comment by Naycon** [comment]
Maybe it was unclear from my comment, but I was refering to the logs I already made (linked above), that are corrupt. I'm guessing updating the firmware won't fix them?

**Comment by fhorinek** [comment]
I understand you.
The kml files generated by 2235 does not contain gps info, just random characters

**Comment by Naycon** [comment]
Right, understood. Well, thanks for fixing the issue anyway!

**Comment by fhorinek** [comment]
![](http://i.myniceprofile.com/708/70832.gif)
