### ISSUE TITLE
Quick and easy on/off of audio - no sound on one screen?

### ISSUE THREAD

**Issue by moyesboy** [fhorinek/SkyDrop#144]
I am using skydrop as a backup vario, but full time to send nmea to my XC soar device (minikobo).
I would like to be able to quickly switch the vario audio on when and if my other vario fails or malfunctions.
I suggest being able to set up one info screen with no sound. Then I can simply advance to another screen to have audio on.

Currently I have to press several times and several things to get to the menu to enable/disable audio. Unless I am missing something?

**Comment by moyesboy** [comment]
I see I more or less reproduced this https://github.com/fhorinek/SkyDrop/issues/51
But I think I like the idea to make one of the screens silent, which whatever choice of info there the pilot wants.

**Comment by fhorinek** [comment]
will add silent screen option

**Comment by fhorinek** [comment]
Every page can now be set as silet. Added in next fw update
