### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by colignym** [fhorinek/SkyDrop#145]
With the last update, my vario volume, even at 100% is extremely soft.

**Comment by fhorinek** [comment]
The probelm occured with 2239? 
When you downgrade your firmware the sound is than ok?
Does it happends with full battery?

**Comment by colignym** [comment]
Hi,

Yes 2239

Did not try downgrade

Yes battery is full.

It's a custom sound profile

I attach file.

On Tue, Mar 15, 2016 at 9:48 AM, František Horínek <notifications@github.com

**Comment by fhorinek** [comment]
GitHub is not accepting the attachments, send it to my mail frantisekhorinek@gmail.com

**Comment by fhorinek** [comment]
I have tested the configuration and the sound looks OK on my test unit. 
I do not think that this is software related problem. Try to reapply the latest SKYDROP.FW to reset configuration to the default setting snd retry.

**Comment by colignym** [comment]
Hi,

I tried previous versions, and standard configurations.  Does not come
right.  Must be hardware then.

It is significantly softer than my other skydrop, but still usable.

I opened it up, and cannot see anything out of place.

Regards

**Comment by fhorinek** [comment]
Than we can replace the faulty part if you want to.

**Comment by colignym** [comment]
Hi,  I fiddled with the beeper, and it's now at an acceptable level, Thanks.

Issue may be closed now.
