### ISSUE TITLE
GPS down

### ISSUE THREAD

**Issue by aktie** [fhorinek/SkyDrop#146]
GPS doesn't connect.
GPS is enabled, status always 0/0 No Fix, "G" keeps blinking.
Impossible to downgrade back to version 1278 - "UPDATE.EE is not compatible!"

**Comment by fhorinek** [comment]
What version are you using?

**Comment by aktie** [comment]
v1.0 - 1504, build 2239

**Comment by fhorinek** [comment]
Please enable debug log in settings->Debug.
Leave it for a ~15min with clear sky above it.
Then connect it back to pc and send me debug.log file to frantisekhorinek@gmail.com

**Comment by aktie** [comment]
I've sent you the log file, but apparently it didn't log GPS part. Retrying again now

**Comment by fhorinek** [comment]
I will create gps debug trace, please wait

**Comment by fhorinek** [comment]
Please update firmware and enable Debug->Debug log and Debug GPS. Then try to catch the fix for few minutes and then send me debug.log file.

**Comment by aktie** [comment]
DEBUG.LOG emailed

**Comment by fhorinek** [comment]
How long did you try to catch the GPS FIX?

**Comment by aktie** [comment]
2 x 15 min.

**Comment by aktie** [comment]
Did about 20 min and 15 min more, DEBUG.LOG emailed. Can you tell from it if that's not a problem with GPS sensor of my unit actually? I need it to work, not to keep testing and experimenting for you.

**Comment by fhorinek** [comment]
You are right sorry for that. Nika will contact you and replace the unit.

**Comment by aktie** [comment]
@fhorinek, I still haven't been contacted about replacing the unit. Could you please check with Nika?
