### ISSUE TITLE
Unable to add IGC log to XC League http://xcleague.com/ - Required record is missing: "H" record (DTM)

### ISSUE THREAD

**Issue by edmondscommerce** [fhorinek/SkyDrop#147]
Unable to add IGC log to XC League http://xcleague.com/ 

- Required record is missing: "H" record (DTM)

Here is the copy pasta from the website:

> Unable to use this tracklog: 02-1319.IGC
> 
> Required record is missing: "H" record (DTM)
> Sorry, your flight cannot be entered. Please read the information below.
> 

> Information
> Your tracklog does not conform to the IGC specification. You must download your track again and create a new IGC file. Make sure you are using the latest version of your download program and if the problem persists, try a different program.
> 
> Please contact us if you are unable to resolve this error or if you have deleted the track from your instrument.
> 
> Warning
> Warning: Do not edit your IGC file because this will invalidate the security mechanism and your flight will be removed later.

Here are all the H records

```
grep '^H' 02-1319.IGC
HFDTE130316
HFPLTPILOTINCHARGE: not specified
HFGTYGLIDERTYPE: not specified
HFGIDGLIDERID: not specified
HFRFWFIRMWAREVERSION:build 2239
HFRHWHARDWAREVERSION:drop_1506
HFFTYFRTYPE:SkyBean,SkyDrop
HFGPSRECEIVER:Quectel,L80,22cm,18000m
HFPRSPRESSALTSENSOR:Measurement specialties,MS5611,25907m
HFFSP:AL4
HFALGGEO
HFALPISA
```

**Comment by fhorinek** [comment]
H F DTM GPS DATUM will be added

**Comment by fhorinek** [comment]
Done and it will be available with next fw update
