### ISSUE TITLE
Update from 1278 is not possible

### ISSUE THREAD

**Issue by tomasz13** [fhorinek/SkyDrop#148]
ahoj, skusam upgrade dropu R1504 zo firmwaru 1278 na 1449b alebo na 2222, a nedari sa mi to.

1.ked to spravim tak ze po nakopirovani suboru firmware.fw (a smozrejme korrektnom odmountovani dropu) ked stlacim stredne O tlacitko (PWR) tak pristroj sa zacne bootovat, (vykresluje logo) a spomaly sa tak ze asi na 1 frame/s pri vykreslovany loga (a potom ked sa nastartuje tiez ide nepouzitelne pomali), a verzia FW sa nezdvihne.

2.ked po nakopirovani suboru firmware.fw (a smozrejme korrektnom odmountovani dropu) vytiahnem kabel z USB, tak sa to tiez restartne, ale dostanem sa do volby "Update file found Apply? yes no". Ked si vyberem yes, tak po 3s sa vypne, a ked ho zapnem zase polozi otazku "Update file found Apply?" ked dam no tak tiez roby to iste. Verzia Fw sa ani vtomto pripade nezdihne.

prosim ta o pomoc lebo sezona sa zacina a paradne ficurky pribudli cez tu dlhu zimu....

dik

**Comment by fhorinek** [comment]
Vyzera to na chybu FS na karte, skus ju vybrat a naformatovat v PC

**Comment by tomasz13** [comment]
fat32?

**Comment by fhorinek** [comment]
hej

**Comment by tomasz13** [comment]
nepomohlo... to iste... velkost allokacnej jednotky ma byt 4096, vsak?

**Comment by tomasz13** [comment]
skusim to dlhe formatovanie...

**Comment by tomasz13** [comment]
ani tak :(

**Comment by fhorinek** [comment]
Keď to pripojiť na usb tak sa dostaneš na file systém sd karty?

**Comment by tomasz13** [comment]
ano, a ked na nom vytvorim textak, tak viem to aj citat, aj pisat, vymazat, vytvorit...

**Comment by tomasz13** [comment]
ked robim downgrade na napr. 910, ta to tiez prejde...

**Comment by fhorinek** [comment]
A s 910 ti to na najnovší nejde?

**Comment by tomasz13** [comment]
update done. SkyDrop will reboot ;)

**Comment by tomasz13** [comment]
ale potom zostane na 910... a je to rozsipane...

**Comment by fhorinek** [comment]
tak ked sa to vrati do usb modu tak skus dlho podrzat prave tlacitko

--
František Horínek

2016-03-16 18:20 GMT+01:00 tomasz13 <notifications@github.com>:

**Comment by tomasz13** [comment]
nic sa nstane... blikne na sekundu a vati sa do usb modu.

**Comment by fhorinek** [comment]
cez komp tam vidis subor update.fw?

--
František Horínek

2016-03-16 18:29 GMT+01:00 tomasz13 <notifications@github.com>:

**Comment by tomasz13** [comment]
uz nie je tam len cfg.ee... ale posledny FW 2239 uz ma skydrop.fw nie update.fw

**Comment by tomasz13** [comment]
skusil som tam natlacit 1773, aj to zhltol, vypisal "update done. SkyDrop will reboot" ale potom to iste nastartuje vidim len ikonku bat, a ked stlacim tlacitko dolava alebo doprava tak sa rozsype. pri bootovani vidim ze zosal na verzii 910

**Comment by fhorinek** [comment]
Skús nahrať SkyDrop.fw, odpojiť, zapnúť dať yes, a keď sa vráti do usb mode
podržať prave. Presne tak ako som napísal teraz

**Comment by tomasz13** [comment]
ale ked ho odpojim tak nebude chcet vratit sa do usb mode... musim niekedy medzi tym zase ho pripojit?

**Comment by fhorinek** [comment]
Nie kábel ale device

**Comment by tomasz13** [comment]
no asi nakonie naozaj bude jebnuta ta karta... lebo teraz uz ked ho dam do citacky, tak pise ze ho treba naformatovat. tak som ho naformatoval znovu.... ale asi pohladam niekde doma novu a skusim to s tym... co je maximalna velkost co zozere Drop? velke 32Gb viem ze mam mensie budem musiet QA hladat...

**Comment by fhorinek** [comment]
Max 4g

**Comment by tomasz13** [comment]
stou 4gb kartou som mal problem, nevedel som taku najst, mal som min 16gb ale s tym to nefunkovalo. vcera som zohnal 4g kartu a vsetko sa vyriesilo. Upgrade presiel hladko a bez problemov. dik za pomoc. :)

mam ale dalsi problem, co som si myslel ze sa to po case vyriesi s upgrademi, ale este ani pri verzii 2239 to nefunguje. 
Je to stav nabitosti baterii... ale na to asi spravim nove issue

**Comment by fhorinek** [comment]
ok kludne sprav, som rad ze sa toto doriesilo
