### ISSUE TITLE
feature request: make use of the RGB-LED

### ISSUE THREAD

**Issue by atomphil** [fhorinek/SkyDrop#15]
It would be nice having the RGB-LED as an additional indicator. Maybe for active settings menu or as warning lamp or something like this.

**Comment by tomasz13** [comment]
+1
good idea

**Comment by fhorinek** [comment]
Low battery is first candidate
than gps status
bluetooth link
active menu
what else?

**Comment by atomphil** [comment]
airspace near ;-)

**Comment by fhorinek** [comment]
@atomphil ok but on one condition, Name of the nearest airspace will be in mors code :)

**Comment by tomasz13** [comment]
RGB-LED can be used for signalizing vario... maybe if I climbing then green light blinking & when sinking then blinking red (with changing intensity) & zero could be signalized with stationary orange.
It would be good when I listening to music, or if I have full my head with beeping ;)

**Comment by fhorinek** [comment]
@tomasz13 I am afraid that you want be able to see it during flight, I have to test it.

**Comment by moyesboy** [comment]
How about as a warning of approach of darkness then? 
Legally we must land before 20 minutes after sunset. flash the LED at sunset time, and escalate to amber and red as 20 minutes approaches.
Then we need a bright forward facing LED...

**Comment by fhorinek** [comment]
RGB is all ready in use as indication light, check the manual
