### ISSUE TITLE
display doesnt work

### ISSUE THREAD

**Issue by commander172** [fhorinek/SkyDrop#150]
Hi ive just updatet to the last version. Yesterday myskydrop display stoped working ( blank screen) during flight but buetooth connection still worked with my app ( flyme ) after landing i shut down the vario and after powering on the Display worked again.

**Comment by fhorinek** [comment]
Did you suffer some kind of physical bump? The LCD is connected to pcb by conductive rubber. In theory you manage to break the connection for a moment you can disable the display, until next reinitialisation, but it never occurred in stress tests.

**Comment by commander172** [comment]
It was mounted on my cockpit so i disnt think there was a bump.
Am 22.03.2016 09:25 schrieb "František Horínek" <notifications@github.com>:

**Comment by fhorinek** [comment]
Ok I will close it for now. If the problem will occur one more time we will solve it as RMA
