### ISSUE TITLE
Unable to upload track 

### ISSUE THREAD

**Issue by flyboy0871** [fhorinek/SkyDrop#151]
Hi Franto. trying to upload track to Leonardo - it say 

There was a problem submitting the flight

This is not a valid .igc file

**Comment by fhorinek** [comment]
please send me the igc file to frantisekhorinek@gmail.com

**Comment by flyboy0871** [comment]
Ahoj Franto. icg file attached. Toto je prvy raz co som chcel pouzit
skydrop na xc , inac ho pouzivam len na tandem.

Safe landings!   Jaro Krupa    708-935-0177

www.chicagoparagliding.com
www.777glidersusa.com
www.oudie3.com
*Facebook*:  *Chicago Paragliding*



On Tue, Mar 22, 2016 at 3:37 AM, František Horínek <notifications@github.com

**Comment by flyboy0871** [comment]
Safe landings!   Jaro Krupa    708-935-0177

www.chicagoparagliding.com
www.777glidersusa.com
www.oudie3.com
*Facebook*:  *Chicago Paragliding*

**Comment by fhorinek** [comment]
Ahoj, github blokuje prílohy, pošli mi ho iba na tú adresu.

**Comment by fhorinek** [comment]
Zatial to zatvorim
