### ISSUE TITLE
Battery percentage

### ISSUE THREAD

**Issue by tomasz13** [fhorinek/SkyDrop#152]
mam problem, co som si myslel ze sa to po case vyriesi s upgrademi, ale este ani pri verzii 2239 to nefunguje.
Je to stav nabitosti baterii... 

stale mi to ukazuje nulu. Aj ikonka (je prazdna), aj vidget vypisuje 0%. Tympadom vobec neviem odhadnut ci je pristroj uz full nabity, alebo ci je na case ju dobijat.
Otec co ma Dropa, ten nejaky stav aspon ukazuje, neviem s akou prestnostou, lebo to sme netestovali, ale ked to dam na nabijacku tak percenta pribudaju, a ked to odpojim tak nabitost klesa. Ten moj drop vobec nic... stale 0%... tak stale stresujem ze sa vypne. 
Hardver je ten isty (early bird R1504) a teraz uz aj FW (2239).

**Comment by fhorinek** [comment]
posli mi udaj DEBUG->ADC RAW value

**Comment by tomasz13** [comment]
3841 ale mení sa to... Teraz 3837...

**Comment by tomasz13** [comment]
![image](https://cloud.githubusercontent.com/assets/12948865/13999948/253ff2c2-f13f-11e5-9eda-b39939e8ebbe.jpeg)
![image](https://cloud.githubusercontent.com/assets/12948865/13999949/256c8b0c-f13f-11e5-89b6-cebf5470a698.jpeg)

**Comment by tomasz13** [comment]
Dal som ho na nabíjačku (na cca.30 min), počas nabíjania stále ukazuje 9% (nemení sa to) a ADC sa zvýšil na 4079. (Koľko by to malo byť keď je to full nabité?)

**Comment by tomasz13** [comment]
nechal som nabijat celu noc... ADC4095

**Comment by fhorinek** [comment]
skus toto.
[SKYDROP.FW.zip](https://github.com/fhorinek/SkyDrop/files/187505/SKYDROP.FW.zip)

**Comment by tomasz13** [comment]
Wau... Vyzerá to sľubne... Teraz ukazuje 100%, full ikonku. Zajtra otestujem či to bude klesať. Potom ti podám hlásenie ;)

**Comment by tomasz13** [comment]
Ahoj, 
Včera som otestoval Dropčeka, ale ešte to nie je to pravé orechové. Teraz je to naopak :(
Stále ukazuje 100%, čiernu baterku, a 4095ADC. Zapol som ho v aute na nejaké 2h, + cesta na kopec, a potom som lietal cca1,5h. Ani o jedno % neklesla hodnota, čo by nebolo zlé. Ale keď som pristál, tak ešte chvíľku bzučal, (čakal som že sa sám stopne, a vypíše tabuľku ako zvyčajne, ale ono sa to vyplo natvrdo. Potom som ho zapol, ale o pár sekúnd zase zdochol. Úplne sa vybila baterka, hoci do poslednej chvíle ukazovala Full.
IGC Log sa vytvoril, ale keď ho chcem uploadnúť na XContest, tak mi vypíše chybu, záznam sa mi objavý a aj cesta ktorú som preletel, ale body mi za to nedá. Čo sa stalo s tým logom?

**Comment by fhorinek** [comment]
Log nie je validny pretoze name G-record. Preto tam nie su body. Vypol sa nasilne, bez toho aby ho poriadne uzavrel. Na tu baterku este budem musiet kuknut.

**Comment by tomasz13** [comment]
Čo je to G rekord? Zlyhal GPS? Dá sa s tým niečo spraviť, poriadne
uzavrieť? Vedel by si to opraviť?
Dik

**Comment by fhorinek** [comment]
Ak dosla baterka skor, tak drop nestihol korektne uzavriet subor.
G-rekord je zabezpecenie IGC suboru, ktory zabranuje jeho modifikacii po
tom ako bol stiahnuty zo zariadenia.

Zial opravit to nejde

--
František Horínek

2016-03-30 9:53 GMT+02:00 tomasz13 <notifications@github.com>:

**Comment by tomasz13** [comment]
Ďakujem za odpoved. Skús teda niečo poriešiť s tou baterkou. Dik

**Comment by fhorinek** [comment]
Skus 2288. http://vps.skybean.eu/repo/updates/2288/

**Comment by tomasz13** [comment]
Po upgrade je to zase ako na začiatku... Ikonka prázdna, widget 0%... :(

**Comment by tomasz13** [comment]
Cez víkend som testoval trosku. A zbadal som, že to neukazuje stále 0% po čase (pri ADC3754) nahodí 100%, a začne to aj klesať (dosť rýchlo).

Takto to ukazuje, a klesá:

ADC
4096 0% (full charge)
3754 100%
3630 99%
3434 56%
3380 43%
3309 30%
3191 5%
3145 0%
3080 Off

Z 30% na 0% to klesne cca za 5m30s a vypne sa.

**Comment by tomasz13** [comment]
ta kalibracia zafungovala vo FW Build-2784 ;) dik
