### ISSUE TITLE
Error in Skydrop IGC file  

### ISSUE THREAD

**Issue by almonn** [fhorinek/SkyDrop#154]
While trialling my new SKydrop in the car on multiple journey's, I've had one mysterious 'break' in the IGC file where I was mis-placed about 20 km further west for a second, before coming back on track again.

I'm quite sure its a Skydrop hardware/software issue, as the device is connected (via UART) to a Kobo running XCSoar, and XCSoar has recorded the track perfectly; see picture, which shows images of Skydrop & XCSoar tracklogs (using XCplanner). The inset shows the detail where the tracklog goes wayward. 

I can't attach the IGC, so please email for a copy.

![igc - skydrop vc xcsoar from same gps](https://cloud.githubusercontent.com/assets/18029689/13984958/88e1ab84-f0f1-11e5-810c-c3ebf1d95972.jpg)

**Comment by fhorinek** [comment]
please send me the igc to frantisekhorinek@gmail.com

**Comment by almonn** [comment]
Hi Guys
Thanks for looking at this so quickly
The first file is the Skydrop one (with the error), the 2nd one was created by the Kobo/XCSoar unit (all OK) which received its data from the Skydrop.
Cheers, Nev

Date: Wed, 23 Mar 2016 05:38:15 -0700

**Comment by fhorinek** [comment]
I think I know where is the bug but I need the raw data from gps. I just published new firmware update with enhanced debug. Please Enable Debug log and Debug GPS option in Debug menu. 
I will try to replicate this error in my car but since it is quite rare it will be great if you join my effort.

**Comment by almonn** [comment]
Hi Fhorine  (hope I got your name right!)
Sure, I will do that. Very pleased to join your efforts.
For info, I have done much testing with various GPS for 2 years while marrying-up with Kobo's (mainly PA6H and the Bluefly), and also comparison with commercial/Garmin units, plus pushing devices in 'low signal' areas to check/benchmark performance.
I have done over 250 Kobo conversions in the UK, and I'll be doing many more now we have your Skydrop with an FAI compliant tracklog; a very important feature. The testing I'm doing is to ensure I can broadcast this news! I've also liaised with John Stevenson (UK XC league, also IGC/FAI rep) to ensure IGC's are acceptable
Great work, its a nice piece of kit. Will shortly have a nice container ready for pairing the Skydrop/Kobo (just working on final drawings with manufacturer)  

Regards, Nev

Date: Wed, 23 Mar 2016 06:42:02 -0700

**Comment by fhorinek** [comment]
Please remember that we have valid tracklog only with FAI CIVIL (open validation server). 
If you have any other suggestion for the drop feel free to present them.

And the name is Fero (or full František Horínek) :)

**Comment by almonn** [comment]
Thanks Fero! :) 

I presume I'll get both an IGC file and raw NMEA file?  .....I can quickly view each IGC to see if we can replicate this rare error.

**Comment by fhorinek** [comment]
You will get IGC file and in the debug.log there will be raw GPS.

**Comment by ZIRminator** [comment]
i might have the same problem

![skydrop_gps](https://cloud.githubusercontent.com/assets/14094559/14004961/96ce2a5c-f15e-11e5-8674-418c395aa3e3.jpg)

**Comment by fhorinek** [comment]
please send me all available kml / igc / debug.log files to frantisekhorinek@gmail.com

Idealy with options Debug.log and Debug GPS enabled.

**Comment by almonn** [comment]
Hi Forec, 

I've reproduced the error and emailed the IGC files and Debug log.

The GPS feed is sound, as in parallel (via UART) I'm sending to a Kobo/XCSoar unit and the track represents the drive.

**Comment by moyesboy** [comment]
I had a more serious issue with the IGC yesterday.
There is a whol chink of log points missing, for a period from just after launch to a period well over an hour into the flight. After that the log is good.
The recording from nmea in xcsoar is good throughout.
Software was updated just before the flight. I aunched and found vario audio was annoyingly on, and some time liater I managed to switch it off. I think I then left it on that menu screen which may have times out? so there is a possibility that button presses and menu access upset the igc log?
![igc from skydrop](https://cloud.githubusercontent.com/assets/16935935/14059384/2d5b90ac-f337-11e5-93da-c1630cd45ded.jpg)
![xcsoar fed from skydrop](https://cloud.githubusercontent.com/assets/16935935/14059385/30eec89c-f337-11e5-95f7-a45ca4d91507.jpg)

**Comment by moyesboy** [comment]
I email the two igc to you, and an nmea log from xcsoar.

**Comment by moyesboy** [comment]
can I attach a zip? yes
[blank section in igc gordon rigg.zip](https://github.com/fhorinek/SkyDrop/files/190428/blank.section.in.igc.gordon.rigg.zip)

**Comment by fhorinek** [comment]
Hi, I think that I found the problem with the gps.
Please update to the 2266
http://vps.skybean.eu/repo/updates/2266/

**Comment by almonn** [comment]
Great, thanks Forec! 

Nev

Date: Wed, 6 Apr 2016 06:45:45 -0700

**Comment by fhorinek** [comment]
the 2266 will NOT work, there is an error in gps driver

you can ty this experimental release

[SKYDROP.FW.zip](https://github.com/fhorinek/SkyDrop/files/208461/SKYDROP.FW.zip)

**Comment by almonn** [comment]
Thanks Fero
Have loaded, and will trial on two journeys after work tonight (about 80km)
Will report back early tomorrow morning - thanks for sorting quickly :)

Nev

Date: Thu, 7 Apr 2016 06:25:04 -0700

**Comment by jarda-manana** [comment]
new FW looks good - thanks Fero

**Comment by almonn** [comment]
Hi Fero
Thursday evening I completed around 80km in 3 journeys, and all traces good :)Will continue testing Friday (150km), and Sat/Sun (1,000km)Thanks for getting on top of this!
Cheers, Nev

Date: Thu, 7 Apr 2016 06:25:04 -0700

**Comment by moyesboy** [comment]
Build 2276 - looks like there is a problem with vario in the nmea stream?I now know Auto start log disabled doesn't mean it is always running, so I have no Skydrop log from my drive in this morning. I will run again on the way home. My drive has quite a lot of up and down of the order of 300m.What I did see was an error in the XC soar vario as if the nmea stream has some false vertical speed in it.You see from the photo the XC soar screen shows massive descent rate on the vario that I never saw before with any other skydrop firmware. There was some change in the last digits of the number but it was always 42,500 down.The igc in xcsoar is good. See you seems to be working on the altitude info, looks like the nmea vario is not in the igc?Probably this false data can bee seen in the nmea log compared to the IGC log I have attached.
For starting the log, I guess I repeat my desire for an "always logging" setting rather than just setting the auto start to a small number. Anyway I will now set it to a small number.

Hey Nev! I work outside Manchester CTR by about 40meters! SO I can land outside the door legally!  - but ceiling is only 2500ft.(note line in Pic)

**Comment by moyesboy** [comment]
My mistake. Nar on left is arrival alt at a very distant goal. Vario is good.

**Comment by fhorinek** [comment]
:) 
I made a new update, the first lines with zeros will not appear, the bluetooth and uart will output only after  baro data are valid
http://vps.skybean.eu/repo/updates/2288/

**Comment by fhorinek** [comment]
2288 is the cure. Hallelujah

**Comment by almonn** [comment]
This weekend I performed around 1,000 km 'drive testing' the pre-release 2276 (same as latest release 2288)

Both long IGC's look fine in a 2D check using XCPlanner (i.e. no mysterious break as per originating issue)

The SKydrop was continuously feeding my Kobo/XCSoar unit (via serial/wired/Uart) and the display always reflected reality.

I'm sure this issue is closed!  :)  Many thanks Fero for persisting and resolving.

**Comment by ZIRminator** [comment]
@almonn
can you tell me how to connect the drop with kobo? only with bluetooth or do i need some extra devices?

**Comment by almonn** [comment]
You can use a wired/serial connection, connecting the UART port inside the Skydrop to the UART serial port inside the Kobo. Only the Tx(Skydrop) to Rx (Kobo and ground is required. Here is a picture. Probably best to join the Facebook group "Kobo XCsoar users" for more detail. You could also wire a Bluetooth module to the Kobo UART port, but I've yet to try that yet. I prefer the integrity of a wired connection :)

![skydrop-touch2 0-mini](https://cloud.githubusercontent.com/assets/18029689/14413495/e4ea202e-ff73-11e5-860b-e66283d6fb08.jpg)
