### ISSUE TITLE
After landing (and 1st IGC file creation), a 2nd IGC isn't started on next takeoff

### ISSUE THREAD

**Issue by almonn** [fhorinek/SkyDrop#155]
During car testing of a SKydrop connected to a Kobo running XCSoar, I notice the following:

Data to Kobo/XCSoar all good, and multiple IGC's created during simulated takeoff & landings (e.g. when XCSoar detects the car has stoped for n seconds). All good

BUT.................Whilst I get the FIRST IGC created by the SKydrop, it doesn't create the **2nd or subsequent **IGC's (e.g. If I took off, landed to get Wallet, took off again, flew record flight, landed, I would not have an IGC for my record flight)

See SKydrop vs. XCSoar tracklogs in pic below which evidence the behaviour. I also noticed the same issue when paired with a Nexus/XCsoar unit last week (but had attributed the issue to Bluetooth dropout!)

![igc - skydrop vc xcsoar from same gps](https://cloud.githubusercontent.com/assets/18029689/13985143/e495dcc4-f0f2-11e5-8ded-ff0d82dde512.jpg)

**Comment by fhorinek** [comment]
Update your firmware to 2256. The SkyDrop will start a new log now.
