### ISSUE TITLE
Blank section is igc file

### ISSUE THREAD

**Issue by moyesboy** [fhorinek/SkyDrop#156]
I uploaded date here.https://github.com/fhorinek/SkyDrop/files/190428/blank.section.in.igc.gordon.rigg.zip
I posted on nevs igc error post, but I start this because the problem is I think more serious and different.
Throughout the flight my kobo/xcsoar was using the hard wired  nmea feed from the skydrop and the xc soar igc is faultless. Above zip has skydrop igc, nmea log from xcsoar, xcsoar igc.
Skydrop has a few minutes after takeoff recorded, and then it jumps to a long time later and 15 km away/with no points recorded. After that the track log is good until landing. 
It is interesting that the igc, after well over half an hour, suddenly starts again and then runs fine. There is only one igc. It is not a landing launch detect error as that would produce separate igc files.
Obviously such a big chunk missing during a flight is a serious issue for competition flight recording!
Software version was the latest loaded on themorni g of the flight (Friday 25th).
I also have a igc from a 6030 for the same flight if that is any use.

**Comment by moyesboy** [comment]
Of course recording of 100m airspace violation at end of flight is perfect! :)

**Comment by fhorinek** [comment]
I have located the bug. 
Unfortunately I have no idea why it occurred

```
the line 243 is 
B1234005319318N00143837WA0052800547
but it should be
B1112345319318N00143837WA0052800547
```

somehow the timestamp is shifted (123400 -> 111234) but I have no idea why :(

**Comment by moyesboy** [comment]
intrersting. that depends on how you are generating the time stamp...
did the time stamp revert to a correct one after an hour or so? so the track reappeared?
if the igc contains a whole load of illegal times stamp, predating takeoff, then the igc should be rejected, but so far I only opened it in seeyou, I didn't try with anything else.
Perhaps there could be a periodic watchdog check to see if timestamp is in the expected range, to at least trap the error? or correct it if the reason is elusive. 
The question is, why is the time stamp correct in the exported nmea data? is it not a sample of exactly the same data? or is xcsoar generating its own time stamp data and the nmea is assumed to be real time with no time stamp in it?

**Comment by fhorinek** [comment]
Only one line was corrupted, when I repair it (and destroyed the signature) seeyou was able to display the flight path correctly.

I am generating timestamp from nmea and that information was correct.

**Comment by moyesboy** [comment]
I wonder why, with only one incorrect time stamp, see you shows the flight with a start, a blank, and then the rest of the flight from about an hour in? I wonder how the FAI scoring program would show it? it might just ignor the single incorrect point.
Something worth noting is in the past we discovered some pretty serious issues crossing the zero degrees meridian (not in the instruments, but in the programs for checking the flights). I didn't quite fly far enough on Friday, landing at 0deg 28.5min West. So hopefully soon I can test the meridian crossing (we found the FAI scoring program FScomp failed us a few years ago). I think crossing 0 degrees is only for British French and Spanish, but it seems there is no popular place to fly near 0 deg in France.

**Comment by moyesboy** [comment]
When I attempt to load the igc to GPS dump it fails "Format error line 7231"
Out of interest I used http://cunimb.net/igc2kml.php to convert the file to kml and view it on google earth. The trace displays correctly except for a massive position error well into the flight, not where seeyou draws a straight line. possibly near point 7231 of the track.
So, it seems different programs might be seeing this ogc srror differently.
Possibly the point with the time stamp error isn't the most important error?
Possibly the error in my file is position related rather than time related, and the issues nev is reporting are one and the same...

**Comment by moyesboy** [comment]
from the igc converted to kml file (time stamp is lost with that conversion), here is the position error line - I make this about the 6700th data point, not agreeing exactly with gps dump:

-1.32747,53.2627,650
-1.32737,53.26285,651
-1.32732,53.26298,651
-10.062,53.26312,651
-1.32728,53.26323,651
-1.3273,53.26333,657
-1.32733,53.26342,657
-1.3274,53.2635,657

perhaps that helps.

**Comment by fhorinek** [comment]
Build 2288 is fixing this issue. Closing
