### ISSUE TITLE
New Skydrop - latest update file and configurator

### ISSUE THREAD

**Issue by ChrisDD11** [fhorinek/SkyDrop#158]
Just received a new skydrop vario. Build 2239, Rev 1506. I have tried to use this link from the manual to check latest version http://skybean.eu:8080/repo/updates/ , the link does not work. I also tried to update from github readme update skydrop firmware http://www.skybean.eu/page/support , again this page does not work.

I wish to make sure I have the latest version which I believe is build 2266.
I also would like some instructions or help to use the configurator to change the settings on my vario.

Thanks

**Comment by fhorinek** [comment]
New page, new layout try this http://www.skybean.eu/support . I will
correct the readme

**Comment by ChrisDD11** [comment]
Ok thanks that link works. There is only an UPDATE.FW file in the Build 2266 folder, I presume that I don't need an UPDATE.EE file as described in the update procedure and video?
How do I use the configurator tool?

**Comment by ChrisDD11** [comment]
Actually the file in the update folder is titled SKYDROP.FW

**Comment by almonn** [comment]
Many thanks Fero, I've just updated to 2266.
In the next 4 days I have around 15 journey's to do by car to do that will total around 1,300 km
This should be a good test.
I'll be running a Kobo/XCSoar unit in parallel, driven by the Skydrop output (wired/Uart connection)

With respect to the GPS fix corruption, I'll report back some early results on Friday, and all results on Monday

**Comment by fhorinek** [comment]
That is brilliant! Perfect

**Comment by ChrisDD11** [comment]
Ok I have experimented with the update. It seems like you have to drag the new SKYDROP.FW file onto the vario. Next you need to eject the vario from the PC. This then presents a menu on the vario asking to apply update YES or NO. If you say YES it says it will apply update and reboot. The yellow LED flashes and it switches the vario off. When you then manually switch it back on update 2266 rev 1586 is applied. The new files on the vario read as OLD.EE and CFG.EE. A new you tube video with these instructions may be useful to other users.

The configurator link from your web page seems to present all the options but there must be some way to save these as a new CFG file and presumably replace the one on the vario? Help please.

**Comment by fhorinek** [comment]
you can **load** your settings from your vario from EE files 

- CFG.EE is actual configuration
- OLD.EE is configuration before the last update 

Then you can mess with the settings on the PC. 
After that hit **save** and you will get UPDATE.EE file
put it on skydrop and power it on to apply the changes.

We are working on the video tutorials.

**Comment by ChrisDD11** [comment]
Ok thanks. I have tried to use the LOAD option on the configurator web page tool http://vps.skybean.eu/configurator/#/advanced to load the CFG.EE file from my sky drop but get this message "Please select CFG.EE or OLD.EE file from SkyDrop root directory".

**Comment by fhorinek** [comment]
can you put the cfg.ee here? you have to zip it first


--
František Horínek

2016-04-07 9:21 GMT+02:00 ChrisDD11 <notifications@github.com>:

**Comment by ChrisDD11** [comment]
[CFG.zip](https://github.com/fhorinek/SkyDrop/files/207952/CFG.zip)

**Comment by fhorinek** [comment]
Strange, I have no problem with the load. What browser are you using?

**Comment by ChrisDD11** [comment]
Ok I think I have got this to work. I have used the Firefox Browser rather than Windows Explorer. Firefox does not produce the load error messages.

**Comment by ChrisDD11** [comment]
Thanks for your help. I will write a few notes based on this thread and give them to Guy Richardson if thinks they will be helpful for your Q&A's. 

Just made a mount for my forearm as an alternative to putting on risers. Posted photos on facebook. Take care, Chris
