### ISSUE TITLE
feature request: airspace warnings

### ISSUE THREAD

**Issue by atomphil** [fhorinek/SkyDrop#16]
It would be nice to have airspaces in the device. They can be putted as openair-textfiles at the sd-card. And then there are a displaypage showing the name and borders of the next airspace and the vertical and horizontal distance. And there should be warnings.

**Comment by fhorinek** [comment]
This might be a little tricky, I am not 100% sure that the device will have enough computational power to do this. Anyway this feature is low priority right now

**Comment by wunderbaresnet** [comment]
If, I would d a very simple warning, like a big arrow in the direction of the next airspace, together with the distance and a warning sound.
But for airspaces, a tablet or bigger phone with a proper display is much better - connected via bluetooth.

**Comment by fhorinek** [comment]
@wunderbaresnet the main problem will be that the device have limited amount of memory (16 KiB RAM) to store the airspace boundaries. Drop will need to periodically open the airspace file and compare current position with the map. I am not telling that it is impossible but for now it is no a priority.

**Comment by fhorinek** [comment]
not possible
