### ISSUE TITLE
Feature request - continuous logging, vario always on, simple selection.

### ISSUE THREAD

**Issue by moyesboy** [fhorinek/SkyDrop#160]
A simple selection box - continuous logging on or off with a tick box. and Vario always on tick box.
When ticked all auto start and stop and stop features for detected takeoff and landing are disabled.
Unit produces one continuous IGC or KML log from when it is switched on until when it is switched off, regardless of gps signal status (log only altitude while GPS is "lost", if that is legal for CIVL).
Vario working all the time with sound (if audio is on and not on a silent page).

Purpose:
Those who use the instrument as a backup require the simplest most fool proof possible setup to ensure a valid flight recording when they have to use the device. They do not want to have to develop and discover settings that work through unpredictable issues like very slow flight, stationary flight in stable wind, takeoffs that aren't detected until they have already started the course etc. etc. Multiple flights in one IGC, long flat lines at beginning and end are not really problems, just an annoyance. Less of an annoyance that having some of your flight missing! Many of these units will be switched on and stowed out of sight. The pilot cannot second guess if it is recording or not.

Recommendation:
Continuous logging and constant vario should be set as default in firmware. So a pilot can switch on and experience expected recording and vario operation from first switch on, not find their first flight is not recorded, or has a break in it, or two separate logs....or stand on launch wondering if their vario is going to work or not!
Vario silent until launch, and auto start stop of logging can be activated by those that want it, but most new owners switch the unit on and immediately think "why doesn't it work!"
(Probably this will make for an annoyingly noisy workplace at Skybean!?)

We have the same issue with Flytec "kindly" auto switching off the 6030 when we top land, and then we forget and launch again and instrument takes forever to boot up- and they will not listen to us all asking for a way to disable it! Also the 6030 is silent until we launch. Usually it starts audio OK but every so often when it starts it suddenly cycles through maximum up and maximum down and you have no vario for far far too long if conditions are difficult. Flytec cannot find this bug in their software.

**Comment by almonn** [comment]
Note that this has 95% commonality with my request #157 "IGC logging requires foolproofing"

**Comment by fhorinek** [comment]
I am adding config **record always** . 
It will simulate take-off as soon as the baro filter is ready. You can still land using FTime widget or by turning off the device. 
The sound will be enabled with take off.

Will this work for you?

I will not enable this behavior by default because I think that autostart/autoland is working fine (after the gps time bug fix)

**Comment by almonn** [comment]
Fero, this is brilliant, and will ease the mind of many competition pilots who just want the assurance of "unit on, logging on" - simple!
Many thanks!
Cheers, Nev

Date: Wed, 13 Apr 2016 03:42:49 -0700

**Comment by fhorinek** [comment]
Ok it will be done in next release
