### ISSUE TITLE
skydrope not logging anymore

### ISSUE THREAD

**Issue by quedimas** [fhorinek/SkyDrop#161]
Good evening all, I am new with the vario and while the first day it worked easily and generatd a log now it is not generating anymore. i go into log and under the year 2016 there is nomore generation of actual month and day and then the log.

i have searched for a manual but the link in the support website are outdated.

can you please help?
thank u much

**Comment by fhorinek** [comment]
Try to manually start the flight. 
Go to the second screen and select the FTime widget by short click of the middle button.
Then press and hold the middle button to start flight.
You should see **Take off** message.
There should be letter **L** on the right above the battery indicator.
Now you can power off the vario and recheck the folder.

**Comment by quedimas** [comment]
I did it bit above battery no L

Might itcbe because i am home and gps not reacheable?

Mario Calcagnini
+39 337 165 9048
"Aut Viam Inveniam Aut Faciam"
Il 09/Apr/2016 09:34, "František Horínek" <notifications@github.com> ha
scritto:

**Comment by quedimas** [comment]
when i go in the directory i just can see two file 

CFG.EE
DUMP.EE

**Comment by quedimas** [comment]
While the first time i have used it I havce seen a folder named 2016 then the month and the date of the log

**Comment by quedimas** [comment]
i have been another test on the street and gps was fixed but no L appears above battery.....please gys help me

**Comment by quedimas** [comment]
RST: watchdog
FW nak skydrop build 1278
adc raw value 3499
Board rev drop 1506

**Comment by fhorinek** [comment]
please update firmware 
http://vps.skybean.eu/repo/updates/2288/
just put SKYDROP.FW to the drop

**Comment by quedimas** [comment]
Yeeeeeeeeeeeessssssssss

Mario Calcagnini
+39 337 165 9048
"Aut Viam Inveniam Aut Faciam"
Il 09/Apr/2016 16:58, "František Horínek" <notifications@github.com> ha
scritto:

**Comment by fhorinek** [comment]
So I guess that I can close this issue?

**Comment by quedimas** [comment]
Yeeeeeessssss. Thank u so muccccchhhh

Mario Calcagnini
+39 337 165 9048
"Aut Viam Inveniam Aut Faciam"
Il 09/Apr/2016 07:26 PM, "František Horínek" <notifications@github.com> ha
scritto:

**Comment by fhorinek** [comment]
Happy to help

**Comment by quedimas** [comment]
hey dude...i am sorry to bother again....now the vario sound is not working
anymore :(

**Comment by fhorinek** [comment]
Does the button and power on/off sequence emit sound?

**Comment by quedimas** [comment]
solved thank u ...,my bad

**Comment by fhorinek** [comment]
No problem :)
