### ISSUE TITLE
Skydrop dies after climb/sink

### ISSUE THREAD

**Issue by MosDHV** [fhorinek/SkyDrop#162]
hello, I'm having trouble with my skydrop-  after starting up, all seems ok; however, after climbing or sinking (or simulated with blowing/sucking) it will shut itself off.  I just came from a flying trip where I was unable to use the device and couldn't figure out why it was doing this. I've tried reformatting the SD card and re-installing the configuration- but still experiencing the same issue.  Hope this is an easy fix..?

**Comment by fhorinek** [comment]
Can you make a video of this behavior?

**Comment by fhorinek** [comment]
what version are you using? (build number)

**Comment by MosDHV** [comment]
Build 2052
I took the attached video today-  blowing into the instrument consistently makes it shut off. I just returned from a week of flying and gave up trying to use 
[Skydrop error.zip](https://github.com/fhorinek/SkyDrop/files/211995/Skydrop.error.zip)
it, as I couldn't figure out what was wrong.

**Comment by fhorinek** [comment]
Can you try to format the sd card using SkyDrop (settings-> format sd).
Or you can try to disassemble the drop and try it without the sd card.

I am guessing that the problem is somehow related to the storage.

**Comment by MosDHV** [comment]
OK- removing the SD card: seems to work fine.
re-installing the SD card: tried reformatting and updating using the original 4GB SD and a new one. Unable to get it to function now with the SD card installed- will shut off. I've used several newer builds but I don't think they are being applied (no yellow LED)

**Comment by fhorinek** [comment]
Did you format it using SkyDrop?

**Comment by MosDHV** [comment]
no- removed the card from skydrop, then using an adapter directly connected to computer, I formatted/copied new SKYDROP.FW file from build page

**Comment by fhorinek** [comment]
Please try it with the skydrop, the filesystem structure might be slightly different which can cause troubles

**Comment by MosDHV** [comment]
I'm unable to format using the mini-USB attached to the skydrop-  the display reads "No SD Card". I've swapped two different SD cards in/out with no difference. 

Now the skydrop will not operate with the SD card (either one) installed- it attempts to boot but shuts off. removing the card(s) and turning it on works fine.

**Comment by MosDHV** [comment]
If the SD card reader is the problem, will I be able to send it in for repair?

**Comment by fhorinek** [comment]
OK last attempt, please disassemble the drop and start if without the sd card. Then go to setting. reinsert the sd card and hit format SD. 
If this won't solve the issue than we will replace the device.

**Comment by MosDHV** [comment]
sorry- following the instructions above, the unit shuts off within 1-2 seconds after inserting the SD card. Will not stay on after re-booting (SD card inserted). multiple attempts, no difference.

**Comment by fhorinek** [comment]
We will have to replace the device, please write email to info@skybean.eu that you have problem with sd card and refer this url. You will receive an address where you can send the device. As soon as you provide us with the tracking number, we will send you replacement to save your time. Also provide provide the color of the device.
