### ISSUE TITLE
GPS does not get a fix

### ISSUE THREAD

**Issue by msaraceno** [fhorinek/SkyDrop#164]
The G is still blinking. It was working until fw 1278 but, all the time apart once, with errors in the log. Than I have first upgraded to 2239 and now to 2238 and in both cases I am not able to get a GPS fix. The G symbol is blinking all the time.
rev 1504

**Comment by fhorinek** [comment]
please update to 2288
then go to debug and enable debug.log and debug GPS
then leave the drop outside for ~15 min.
Connect the drop to the pc and upload the debug.log file here (you have to zip it first)

**Comment by msaraceno** [comment]
[DEBUG.zip](https://github.com/fhorinek/SkyDrop/files/211927/DEBUG.zip)
Here the log

**Comment by msaraceno** [comment]
Any news on this? Is it an hardware problem or can it be solved in the next fw update?
Thanks,

Marco

**Comment by fhorinek** [comment]
Hi, the provided log file does not contain GPS debug data. Please make sure that **Debug->debug GPS** option is enabled and retry.

**Comment by msaraceno** [comment]
Here the log again. I switched on the device, I had enable both dubug and debug GPS options and left the unit outside for 15 minutes. The log is attached below.


[DEBUG.zip](https://github.com/fhorinek/SkyDrop/files/228646/DEBUG.zip)

**Comment by fhorinek** [comment]
I think that this is HW problem, do you have soldering iron and some experience with electronic?

**Comment by msaraceno** [comment]
Unfortunately I do not have such skills but I have a friend that can help. What do I have to do? If you can provide me with the instruction I can try to use the bad weather forecasted in the weekend for fix the problem.

**Comment by fhorinek** [comment]
Look on the connection between gps unit (the yellow thing from the top and
green on the bottom) and the board. Try to carefully wiggle the module and
look at the solder points.

If they are loose, just reheat it with soldering iron

**Comment by msaraceno** [comment]
Do you have pictures of the solder points?

On Fri, Apr 22, 2016 at 3:30 PM, František Horínek <notifications@github.com
> wrote:

> Look on the connection between gps unit (the yellow thing from the top and
> green on the bottom) and the board. Try to carefully wiggle the module and
> look at the solder points.
>
> If they are loose, just reheat it with soldering iron
> On Apr 22, 2016 10:32 AM, "msaraceno" <notifications@github.com> wrote:
>
> > Unfortunately I do not have such skills but I have a friend that can
> help.
> > What do I have to do? If you can provide me with the instruction I can
> try
> > to use the bad weather forecasted in the weekend for fix the problem.
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/fhorinek/SkyDrop/issues/164#issuecomment-213325281>
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/fhorinek/SkyDrop/issues/164#issuecomment-213428893>
>



-- 
Do you want sign in on Dropbox? Use this link <http://db.tt/btXn0fY>, we
both get free space!

Blog & Photo Album:
http://www.flickr.com/photos/msaraceno
http://www.2climb.com

**Comment by fhorinek** [comment]
here they are

![imag0457](https://cloud.githubusercontent.com/assets/9072684/14774270/bf96ea86-0ab4-11e6-9378-fb0e3fcba131.jpg)

**Comment by msaraceno** [comment]
I have tried to look at my device and it looks like the solder point and
they appears fine.
I am not really comfortable playing around with soldering iron and
electronics, I am afraid to brick the unit.
If I send you back the unit, can you please provide with a replacement. It
would be much better if you perform the repair.
Please let me know.

Marco

On Mon, Apr 25, 2016 at 7:10 AM, František Horínek <notifications@github.com
> wrote:

> here they are
>
> [image: imag0457]
> <https://cloud.githubusercontent.com/assets/9072684/14774270/bf96ea86-0ab4-11e6-9378-fb0e3fcba131.jpg>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/fhorinek/SkyDrop/issues/164#issuecomment-214133883>
>



-- 
Do you want sign in on Dropbox? Use this link <http://db.tt/btXn0fY>, we
both get free space!

Blog & Photo Album:
http://www.flickr.com/photos/msaraceno
http://www.2climb.com

**Comment by msaraceno** [comment]
Inviato da Outlook Mobile. Sì, funziona con Gmail.






On Sun, Apr 24, 2016 at 10:10 PM -0700, "František Horínek" <notifications@github.com> wrote:












here they are

**Comment by msaraceno** [comment]
![img_20160426_091906](https://cloud.githubusercontent.com/assets/15076851/14811813/4150f6a8-0b9a-11e6-9ee9-48e62f5a45ff.jpg)

**Comment by fhorinek** [comment]
Sure no problem.

Some users prefer to fix the device by themselves. But it is better to send
the device back if you are not comfortable with the repair.

Please write email to info@skybean.eu and refer this issue. You will get an
address where you can send your device for exchange.

**Comment by Naycon** [comment]
I'm experiencing the exact same issue. I've tried waiting outside on a field, used it in the air to get a signal and two days ago it failed to get a signal from atop a 1200 meter high mountain with no higher peaks around. In several of these cases my phone had no problem getting a signal. I've not experienced any problems before (apart from the issue with corrupt logs I reported earlier, but I don't think they are related?). Could this be software related? I tried downgrading a couple of versions to v2256 but I still experienced the same issue.

**Comment by fhorinek** [comment]
@Naycon so you did have a good fix before?

**Comment by Naycon** [comment]
I think so. At least I managed to get some successful logs with gps tracks in earlier versions. I'm not sure if this has always been a problem but that it got worse from one of the updates (didn't you fix something GPS related in one of the recent releases?) or if it is something that appeared in one of the later releases. I'll see if I can try some different versions and see if I can get a fix with one of them.

**Comment by MirkoH** [comment]
Hello,

I have the same problem: Since Updating from FW 2235 to 2256, I dont get any fix GPS Signal. Before I Updated it work fine.
So I also try to downgrade, but it still does not fix.

I dont think it is a Hardware Problem! 

Because before I updated, it gets a signal. After any update and downgrade since then (now FW 2579) I dont get any signal. I am from Germany so may this is the Problem: My Smartphone does get a signal after 10minutes or much longer. After I fixed the GPS Server with an App, I get a signal in 30 seconds. From IOS the server was USA and now I changed it to germany. So I think that could be the problem too.
Another question: When I update a FW on the skydrop is there still any data from the FW before? Because it would fix the Problem with a downgrade then, but any downgrade doesnt fix the Problem.

Best regards,
Mirko

PS: I soldered the Modul again but it doesnt fix the Problem.

**Comment by MirkoH** [comment]
On my Smartphone this App fixed the GPS Problem.
https://play.google.com/store/apps/details?id=com.Double.FasterFix&hl=de

But its not exaktly the same: My Smartphone needs long time to find GPS before the App, but the Skydrop doesnt find GPS after 1,5hours...

**Comment by fhorinek** [comment]
I think that is is HW problem, we need to examine the device. Please write an email to the info@skybean.eu and request the address for RMA. You can also attach link to this issue.
