### ISSUE TITLE
Flight start when getting altitude from GPS

### ISSUE THREAD

**Issue by eliasbe** [fhorinek/SkyDrop#165]
Noticed a minor bug: when I get altitude for alt1 from GPS SkyDrop thinks I have taken off and starts beeping and logging.

**Comment by mennodenhollander** [comment]
I also have a similar issue. If I adjust alt1 using the widget, the flight starts as well. I think the auto-start altitude should be reset every time the altitude is (manually or via gps fix) adjusted.

**Comment by fhorinek** [comment]
Fixed
