### ISSUE TITLE
IGC file validation - feedback from UK PG XCL 

### ISSUE THREAD

**Issue by almonn** [fhorinek/SkyDrop#168]
Many hours of testing now show me that the core IGC tracklog data is sound. Subsequently I have resubmitted a Skydrop IGC file to John Stevenson who runs the heavily-regulated UK PG XC league, plus also John works with the FAI & CIVL on IGC standards and hence is a subject matter expert.

There are a couple of minor corrections required on some of the more 'documentary' aspects of some of the H (header) records.

John has explained everything in detail in an email to me, plus with suggestions on resolution. Fero, I will forward the email directly to you. The good news is these look like very simple fixes.

Regards, Nev (UK)

**Comment by fhorinek** [comment]
I do not have a time to do a proper release, but here are the changes to IGC header
can you try it if it is ok?

it is not official so it won't work with configurator

[SKYDROP.FW.zip](https://github.com/fhorinek/SkyDrop/files/217338/SKYDROP.FW.zip)

**Comment by almonn** [comment]
Hi Fero
Sure, I can try that.Did you follow all of John's recommendations?  (just so I know what I'm looking for)
Regards, Nev

Date: Wed, 13 Apr 2016 07:45:05 -0700

**Comment by fhorinek** [comment]
Yes i did

**Comment by almonn** [comment]
Hi Fero
I've done a couple of runs with 2316 you sent me yesterday.
The GPS & Output behaved as expected (as evidenced by the Kobo/Xcsoar)The IGC looks good when overlaid in XCplanner (2D, Googleearth view)I've had a look at the IGC data, and the H records appear correct (i.e. as per John's feedback)
So, it looks good :)Shall I run it past John Stevenson before you issue a formal release?
Cheers, Nev

Date: Wed, 13 Apr 2016 07:45:05 -0700

**Comment by fhorinek** [comment]
Please do. I would like to have confirmation from him as well.
Thank you for the tests.

**Comment by almonn** [comment]
John Stevenson (UK PG XCL) has checked one of the IGC's I created today (with the test SKydrop release 2316) and the IGC was good.
So, the Skydrop IGC code "XSB" has been enabled on the UK PG XCL server. 
Fero, many thanks for all your hard work on this!
Cheers, Nev

Date: Thu, 14 Apr 2016 09:01:47 -0700

**Comment by fhorinek** [comment]
releasing update and closing issue
