### ISSUE TITLE
Configurator

### ISSUE THREAD

**Issue by ChrisDD11** [fhorinek/SkyDrop#169]
Is there an issue with the configurator - all the data lines seem to display "N/A - Type not (yet!) defined"

**Comment by fhorinek** [comment]
sorry, fixed

**Comment by ChrisDD11** [comment]
Like the new charging red, charged green and waiting for gps flashimg amber. This little vario is an excellent device. It is the first vario I have bought but very good.  I recently retired but used to work in IT for Rolls-Royce and was Head of Tech Support for 20000 users. You are doing an excellent job. Good luck for the future. 


Sent from Samsung Mobile

-------- Original message --------

**Comment by fhorinek** [comment]
wow thank you :)
