### ISSUE TITLE
feature request: Flip display

### ISSUE THREAD

**Issue by Paraglider1** [fhorinek/SkyDrop#17]
Depending on how the vario is fixed on the harness or body it might be useful, if it was possible to flip the whole display and the button-settings (180 degrees)

**Comment by fhorinek** [comment]
Yes this feature is planned and it will be implemented soon

**Comment by fhorinek** [comment]
implemented wait for next release

**Comment by Paraglider1** [comment]
Thanks for the quick realization... :-)
