### ISSUE TITLE
IGC logging - bug at start-up

### ISSUE THREAD

**Issue by almonn** [fhorinek/SkyDrop#170]
Since trialling #2316 from last wednesday/thursday, there appears to be a bug that generates 2 issues. This has happened 2 times out of the three tests I have run.

The two issues are:

- (1) The tracklog has a few positions at the start with zero Lat/Long (so the IGC trace, if overlayed on a map, displaces to the Equator temporarily, and returns to my real position after 27 B records (27 seconds?)
- (2) The H record for the date is 1970

No doubt these are related; at a guess, it is trying to process 'null' GPS data until is has actual GPS data.

Note that the Serial/UART feed to the Kobo/XCSoar unit is fine (i.e. the XCSoar IGC is good, so GPS data is good). Date/time was correctly set before these errors occured 

I will send one example IGC and LOG file by email

**Comment by fhorinek** [comment]
The header and filename was created using gps time, which is not valid until fix.
Now we will use system time for filename and header. This will be available in next update.

The second issue is not really an issue.
The zero Lat/Long is valid B record, since there is V - flag indicating that GPS fix is not valid.

**Comment by fhorinek** [comment]
And as always. Thank you for your input :+1:

**Comment by almonn** [comment]
No problem Fero, thank you for the great support on a great product :)
There are so many real-world test scenario's, it makes sense to have collaborative input from pilots.   

REgards, Nev

Date: Mon, 18 Apr 2016 01:12:18 -0700
