### ISSUE TITLE
Battery draining quickly.

### ISSUE THREAD

**Issue by winddummy** [fhorinek/SkyDrop#171]
Hi,
I seem to have a really high drain on the battery. I have been a bit suspicious of the battery since the unit was new but seems to have gotten a lot worse. Maybe a faulty battery. I attach 2 igc files from yesterday. First one shows a the device in use for approx. 1 hour. Battery 72% at start. This was 100% until switched on about 10 minutes before flying. Second shows after landing. I turned device off and back on. It now shows 36%. If that is accurate I can expect the battery to last less than 2 hours.

[05-1318igc.txt](https://github.com/fhorinek/SkyDrop/files/223366/05-1318igc.txt)
[051418igc.txt](https://github.com/fhorinek/SkyDrop/files/223367/051418igc.txt)

**Comment by winddummy** [comment]
I've been running a test on the unit all day today. It would appear the battery display is somewhat unreliable. Dropped immediately to 80%. Ten minutes later 70%. 1 hour later 50%. 2 hours 30%. At 5 hours very stable at 20%. 6 Hours and battery is at 15%. Low battery LED flashing. So the unit seems ok, its how the battery percentage is measured. Its a bit disconcerting to see a fully charged battery drop so quickly before Launch. The scale needs changing to read percentage of time remaining rather than percentage of charge in the battery.

**Comment by fhorinek** [comment]
We will implement battery calibration function soon.

**Comment by winddummy** [comment]
Thank you. Its still running now. Battery reading 7%. 6 hours and 40 minutes so far. When you do that could you make it so that when the unit is running and I plug in a booster power supply it doesn't go into usb mode. At the moment the unit shuts down if you plug anything in and goes to usb mode. If its off when something is plugged in then usb mode is fine.

**Comment by fhorinek** [comment]
Go to settings and disable usb mode. Then it won't go into usb mode during
active mode. It will work normally when it is no.

**Comment by winddummy** [comment]
Excellent. Thank you for responding.
