### ISSUE TITLE
Problems with Display Contrast

### ISSUE THREAD

**Issue by Lueddi** [fhorinek/SkyDrop#172]
Dear all,
today I got my SkyDrop and now I have got the Problem to adjust the Disply Contrast.
I adjust it and when I restart the SkYDrop, I have to adjust it again, because for example I raised the contrast that I can read all very good, and after restart the complete display is dark and I have to reduce teh contrast. Then after the second restart I have to raise the contrast because the it is so low, that I can't read it. You see it is a never ending story after each start.

May you can help me.

Thanks,

Lueddi

**Comment by fhorinek** [comment]
Hi, when did you receive the skydrop? What was your order number?

**Comment by Lueddi** [comment]
Hi, 
I got mine at 19.04.2016 but I ordered it from https://www.para-zone.de.
They sell the old version with the new buttons.

It seems that this probelm will occure when the battery level is lower.
Actually at 90% there is not the problem anymore.
But could it be? Or what do you suggest what I should do?

Thanks!

**Comment by Lueddi** [comment]
Ok this problem appers also with full Akku too,  so it seems to be an Display issue

**Comment by fhorinek** [comment]
The display has to be replaced. You need to send it back to us for repair. Please write email to info@skybean.eu for the address and the instructions.
