### ISSUE TITLE
Order still pending?

### ISSUE THREAD

**Issue by Flyingplanet** [fhorinek/SkyDrop#173]
Hello,
I've ordered a skydrop through the website on Sunday and paid with paypal. Its still displayed as "Pending".
Why? How long does it take to ship it to France?
Thank you

**Comment by fhorinek** [comment]
Hi, this issues are about technical questions regarding SkyDrop firmware and functions.
Please write an email to info@skybean.eu

**Comment by Flyingplanet** [comment]
Ok. I did have sent an email yesterday, but no answer...

**Comment by fhorinek** [comment]
please give me your arder number

**Comment by Flyingplanet** [comment]
I finally had an answer, it took 3 business days to have my order validated, which was surprising.
The skydrop is on the way now, thank you!
