### ISSUE TITLE
Apps supporting GPS forward w/ bluetooth

### ISSUE THREAD

**Issue by Flyingplanet** [fhorinek/SkyDrop#176]
Hello!
What applications currently support GPS forwarding with bluetooth?
I can't make it work with XCtrack and Flyme (Android on Samsung tab 4 7"). Bluetooth connection is ok with vario data, and battery data, but not with GPS data.
Thank you

**Comment by fhorinek** [comment]
XCsoar is able to use forwarded nmea messages.

**Comment by Flyingplanet** [comment]
Ok, thank you. One more question: does leaving the GPS forward checked use more battery or has any inconvenience?

**Comment by fhorinek** [comment]
No, not really.
