### ISSUE TITLE
Bluetooth pairing issue - is there a default password?

### ISSUE THREAD

**Issue by piman-34** [fhorinek/SkyDrop#177]
I am attempting to pair a Skydrop (brand new: build 2320, Rev 1506, BT 1206v4) with a generic HC05 bluetooth serial adaptor (http://wiki.iteadstudio.com/Serial_Port_Bluetooth_Module_%28Master/Slave%29_:_HC-05) but cannot complete the pairing.
The process uses AT mode programming of the device and all steps work including AT+bind of the BT hardware address but the at+link process fails. I am suspecting that the SPP profile requires some password - the module defaults to 1234 or other confirmation action although the skydrop pairs with my win7 laptop with no password requested. I have attached an image of the programming steps which shows the problem - but does not offer any help. I have enabled BT with Digifly protocol and GPS forwarding.
My requirement for doing this is to equip a Kobo e-reader with bluetooth to enable wireless connection between the Skydrop and XCSoar, and I'm sure once I get this working there will be a lot of others wanting to do the same.
Any help or advice would be appreciated
![bt-config](https://cloud.githubusercontent.com/assets/18732908/14909486/1550ce04-0ddc-11e6-8c66-06ebe1ef2707.jpg)

**Comment by fhorinek** [comment]
First enable debug->debug.log and than we can investigate the skydrop side of connection.

**Comment by piman-34** [comment]
Thanks. I ran te process again with debug on. from the log line 355 it appears to connect, but the 'B' never stops flashing on the Skydrop and the AT command still returns fail.......
[debug.zip](https://github.com/fhorinek/SkyDrop/files/241925/debug.zip)

**Comment by fhorinek** [comment]
I might be the problem with pairing procedure on 1026. Try this pre relase 
[SKYDROP.FW.zip](https://github.com/fhorinek/SkyDrop/files/250179/SKYDROP.FW.zip)

**Comment by piman-34** [comment]
Thanks, I applied the update but still have the same symptoms, the link command returns 'fail' as in original post after about 25 secs. The 'B' never stops flashing on the Sky drop. The relevant lines from the Skydrop debug log are slightly different.
"
< CMD 12
0F 00 00 E1 13 08 00 00 36 30 21 03 16 20 00 Not using link key
Pair status:
 Successful
Connection Status: 
 Status          00
 MAC             20 16 03 21 30 36 
 Connection status 00 - Connected
.
.
.
Connection Status: 
 Status          00
 MAC             20 16 03 21 30 36 
 Connection status 01 - Disconnected
"
Am I right in thinking that if paring is established, the 'B' should stop blinking and stay on on the display? Unfortunately the BT module serial access has little debugging available to me.......

**Comment by fhorinek** [comment]
From my experience:
the pairing process looks like this:

- pair 
- connect 
- disconnect 

then 
- connect
- establish SPP
- ...
- disconnect

maybe you should not try to use password

**Comment by piman-34** [comment]
I did wonder that but it seems to be not possible. A reset of the device defaults it to 1234 and the AT+pswd command throws an error unless a password >0 and <16 digits is provided....

**Comment by piman-34** [comment]
Hi again. I am still trying to get this working.
I realised that the BT device I was using was not supporting Secure Simple Pairing, so got one of these which is more advanced http://uk.farnell.com/microchip/rn42-i-rm/module-bluetooth-class-2-w-ant/dp/2143310 I have also upgraded to the latest build 2491.
I am still getting the same situation and log entries in the debug file as above whichever authentication mode I select. There is approximately a 30sec delay between the paring starting and failing on the adaptor.
Can you tell me what the first hex digits in the debug line "0F 00 00 E1 13 08 00 00 36 30 21 03 16 20 00 Not using link key" mean? the second lot are the address of the BT device in reverse order. Also what does the not using link key mean? could you send me some debug logs of a succesful pairing to a BT device?
TIA
Glyn

**Comment by fhorinek** [comment]
**0F 00 00 E1 13 08 00 00 36 30 21 03 16 20 00** is the message to the module to accept the connection.
**Not using link key** means that the connected device was not yet paired and the skydrop does not know the pairing key

**Comment by fhorinek** [comment]
```
**Turning on the BT**

bt_pan1026_init
BT_MOD_STATE_INIT
BT_IRQ_RESET
BT RESET STEP: 0
BT CTS
BT RESET STEP: 1
BT RESET STEP: 2

 - HCI ----
04 0E 04 04 00 00 00 
event_code 0E
op_code 0000
status 00


< CMD 1
01 03 0C 00 BT CTS

 - HCI ----
04 0E 04 04 03 0C 00 
event_code 0E
op_code 0C03
status 00


< CMD 2
01 08 FC 09 00 A1 00 00 00 14 0D FF 00 BT CTS

 - HCI ----
04 FF 1E 08 00 A1 00 00 00 14 0D 00 0F 38 2E 30 30 2E 37 32 42 2D 30 36 20 52 4F 4D 3D 35 30 31 00 
event_code FF
Pan1026 firmware version 8.00.72B-06 ROM=501


< CMD 3
01 08 FC 0B 00 A0 00 00 00 14 5B FF 02 03 01 BT CTS

 - HCI ----
04 FF 0A 08 00 A0 00 00 00 14 5B 00 00 
event_code FF


< CMD 4
01 08 FC 09 00 A0 00 00 00 14 83 FF 00 BT CTS

 - HCI ----
04 FF 0A 08 00 A0 00 00 00 14 83 00 00 
event_code FF


< CMD 5
01 08 FC 10 00 A1 00 00 00 14 88 FF 10 06 A0 01 01 06 02 00 BT CTS

 - HCI ----
04 FF 11 08 00 A1 00 00 00 14 88 00 10 06 00 13 43 0E F5 1E 
event_code FF
MAC: 00 13 43 0E F5 1E 


< CMD 6
01 13 10 06 1E F5 0E 43 13 00 BT CTS

 - HCI ----
04 0E 04 04 13 10 00 
event_code 0E
op_code 1013
status 00


< CMD 7
01 08 FC 03 00 99 01 BT CTS

 - HCI ----
04 FF 05 08 00 99 00 01 
event_code FF
BT_MOD_STATE_OK


< CMD 8
19 00 00 E1 01 12 00 04 02 0F 53 6B 79 44 72 6F 70 20 50 61 6E 31 30 32 36 BT CTS

 - MNG ----
0E 00 00 E1 81 07 00 00 1E F5 0E 43 13 00 
op_code: 81
status: 00


< CMD 9
0D 00 00 E1 3D 06 00 24 0C 03 10 05 01 BT CTS

 - MNG ----
0F 00 00 E1 BD 08 00 00 06 0E 04 01 24 0C 00 
op_code: BD
status: 00
HCI status 00
HCI op_code 0C24


< CMD 10
07 00 00 E5 01 00 00 BT CTS

 - SPP ----
08 00 00 E5 81 01 00 00 
op_code: 81
status: 00


< CMD 11
08 00 00 E1 0C 01 00 03 BT CTS

 - MNG ----
08 00 00 E1 8C 01 00 00 
op_code: 8C
status: 00
TCU_MNG_SET_SCAN_RESP
 sucess

**Init complete**

**connection request**

 - MNG ----
10 00 00 E1 55 09 00 CE 52 BF F6 CE B4 0C 02 5A 
op_code: 55
status: CE
Connection request from: 
 B4 CE F6 BF 52 CE 


< CMD 12
0F 00 00 E1 13 08 00 00 CE 52 BF F6 CE B4 00 Not using link key
BT CTS

 - MNG ----
08 00 00 E1 93 01 00 00 
op_code: 93
status: 00
Pair status:
 Successful

 - MNG ----
0F 00 00 E1 47 08 00 00 CE 52 BF F6 CE B4 00 
op_code: 47
status: 00
Connection Status: 
 Status          00
 MAC             B4 CE F6 BF 52 CE 
 Connection status 00 - Connected

 - MNG ----
12 00 00 E1 7D 0B 00 32 09 CE 52 BF F6 CE B4 01 00 03 
op_code: 7D
status: 32
HCI status 00
HCI op_code 32
IO_Capability_Response
 IO_Capability    01
 OOB_Data_Present 00
 Authentication_Requirement 00

 - MNG ----
21 00 00 E1 6E 1A 00 CE 52 BF F6 CE B4 13 46 72 61 6E 74 69 C5 A1 65 6B 20 48 6F 72 C3 AD 6E 65 6B 
op_code: 6E
status: CE
Client info
Device name len 19
Device name 
 - MNG ----
0F 00 00 E1 7D 08 00 31 06 CE 52 BF F6 CE B4 
op_code: 7D
status: 31
HCI status 00
HCI op_code 31


< CMD 13
13 00 00 E1 3D 0C 00 2B 04 09 CE 52 BF F6 CE B4 03 00 03 BT CTS

 - MNG ----
15 00 00 E1 BD 0E 00 00 0C 0E 0A 01 2B 04 00 CE 52 BF F6 CE B4 
op_code: BD
status: 00
HCI status 00
HCI op_code 042B

 - MNG ----
13 00 00 E1 7D 0C 00 33 0A CE 52 BF F6 CE B4 89 ED 0E 00 
op_code: 7D
status: 33
HCI status 00
HCI op_code 33


< CMD 14
11 00 00 E1 3D 0A 00 2C 04 06 CE 52 BF F6 CE B4 00 BT CTS

 - MNG ----
15 00 00 E1 BD 0E 00 00 0C 0E 0A 01 2C 04 00 CE 52 BF F6 CE B4 
op_code: BD
status: 00
HCI status 00
HCI op_code 042C

 - MNG ----
10 00 00 E1 7D 09 00 36 07 00 CE 52 BF F6 CE B4 
op_code: 7D
status: 36
HCI status 00
HCI op_code 36
Simple_Pairing_Complete
 Status 00

**link key obtained from incoming connection**

 - MNG ----
20 00 00 E1 47 19 00 00 CE 52 BF F6 CE B4 03 35 43 AB 4D D8 2B 06 C5 87 BA 2C 5C CB B4 33 A1 04 
op_code: 47
status: 00
Connection Status: 
 Status          00
 MAC             B4 CE F6 BF 52 CE 
 Connection status 03 - Link key
 Link key        35 43 AB 4D D8 2B 06 C5 87 BA 2C 5C CB B4 33 A1 
 Link key type   00
 Sniff interval  00

 - MNG ----
0F 00 00 E1 47 08 00 00 CE 52 BF F6 CE B4 01 
op_code: 47
status: 00
Connection Status: 
 Status          00
 MAC             B4 CE F6 BF 52 CE 
 Connection status 01 - Disconnected

**disconnected after pairing**

**connection request form XCSoar**

 - MNG ----
10 00 00 E1 55 09 00 CE 52 BF F6 CE B4 0C 02 5A 
op_code: 55
status: CE
Connection request from: 
 B4 CE F6 BF 52 CE 


**known device, no need to pair**

< CMD 12
1F 00 00 E1 13 18 00 00 CE 52 BF F6 CE B4 Using link key: 01 35 35 43 43 AB AB 4D 4D D8 D8 2B 2B 06 06 C5 C5 87 87 BA BA 2C 2C 5C 5C CB CB B4 B4 33 33 A1 A1 
BT CTS

 - MNG ----
08 00 00 E1 93 01 00 00 
op_code: 93
status: 00
Pair status:
 Successful

 - MNG ----
0F 00 00 E1 47 08 00 00 CE 52 BF F6 CE B4 00 
op_code: 47
status: 00
Connection Status: 
 Status          00
 MAC             B4 CE F6 BF 52 CE 
 Connection status 00 - Connected


**Connected**

 - SPP ----
24 00 00 E5 43 1D 00 00 CE 52 BF F6 CE B4 1F 02 13 46 72 61 6E 74 69 C5 A1 65 6B 20 48 6F 72 C3 AD 6E 65 6B 
op_code: 43
status: 00
BT_IRQ_CONNECTED
2D 00 00 E5 08 26 00 24 00 24 4C 4B 38 45 58 31 2C 39 37 35 39 30 2C 39 39 39 39 39 2C 2D 31 2C 32 38 32 2C 31 31 30 32 2C 2A 31 41 0A BT CTS

 - MNG ----
0A 00 00 E1 F1 03 00 00 E5 08 
op_code: F1
status: 00
TCU_ACCEPT
 Successful

 - MNG ----
0C 00 00 E1 7D 05 00 30 03 00 01 00 
op_code: 7D
status: 30
HCI status 00
HCI op_code 30

 - SPP ----
07 00 00 E5 F1 00 00 
op_code: F1
status: 30
data send!
2D 00 00 E5 08 26 00 24 00 24 4C 4B 38 45 58 31 2C 39 37 35 39 31 2C 39 39 39 39 39 2C 2D 33 2C 32 38 32 2C 31 31 30 32 2C 2A 31 39 0A BT CTS

 - MNG ----
0A 00 00 E1 F1 03 00 00 E5 08 
op_code: F1
status: 00
TCU_ACCEPT
 Successful

** more telemetry data from skydorp **

 - MNG ----
0A 00 00 E1 F1 03 00 00 E5 08 
op_code: F1
status: 00
TCU_ACCEPT
 Successful

 - SPP ----
07 00 00 E5 F1 00 00 
op_code: F1
status: 00
data send!
2D 00 00 E5 08 26 00 24 00 24 4C 4B 38 45 58 31 2C 39 37 35 38 39 2C 39 39 39 39 39 2C 2D 32 2C 32 38 32 2C 31 31 30 32 2C 2A 31 31 0A BT CTS

 - MNG ----
0A 00 00 E1 F1 03 00 43 E5 08 
op_code: F1
status: 43
TCU_ACCEPT
 On releasing SPP connection
2D 00 00 E5 08 26 00 24 00 24 4C 4B 38 45 58 31 2C 39 37 35 38 39 2C 39 39 39 39 39 2C 2D 32 2C 32 38 32 2C 31 31 30 32 2C 2A 31 31 0A BT CTS

 - MNG ----
0A 00 00 E1 F1 03 00 43 E5 08 
op_code: F1
status: 43
TCU_ACCEPT
 On releasing SPP connection
2D 00 00 E5 08 26 00 24 00 24 4C 4B 38 45 58 31 2C 39 37 35 38 39 2C 39 39 39 39 39 2C 2D 31 2C 32 38 32 2C 31 31 30 32 2C 2A 31 32 0A BT CTS

 - MNG ----
0A 00 00 E1 F1 03 00 43 E5 08 
op_code: F1
status: 43
TCU_ACCEPT
 On releasing SPP connection

 - MNG ----
0F 00 00 E1 47 08 00 00 CE 52 BF F6 CE B4 01 
op_code: 47
status: 00
Connection Status: 
 Status          00
 MAC             B4 CE F6 BF 52 CE 
 Connection status 01 - Disconnected

 - SPP ----
0F 00 00 E5 44 08 00 00 CE 52 BF F6 CE B4 02 
op_code: 44
status: 00
BT_IRQ_DISCONNECTED
```

**Comment by piman-34** [comment]
Hi Again - I have been away for a bit but am still trying to get this working.
Firstly I have found that the latest two releases of firmware no longer seem to log anything about bluetooth in the ebug log? The last one I can get sensible logs from is 2491.
I can find the Skydrop using my windows PC and it pairs with no further interaction and when I putty to the serial port I sea the NMEA sentences coming through fine. but when I try with the adaptor I have I still get the failure to connect as above. I am configuing it to use Simple Secure Pairing with an SPP profile but am running out of ideas (and hair!).

**Comment by piman-34** [comment]
I have just found buried deep in the firmware relase notes for the BT module:-
 "Simple Secure Pairing mode does not work for outgoing connections (connections initiated on the module). Current workaround is to use PIN code pairing (SA,4) or open mode (SA,0)"
D'oh!
I am now looking at another type of module and will update you when I have tested it.
The issue with debug logging reported above is still apparent though.......

**Comment by piman-34** [comment]
OK - Whoo hoo, i have now resolved this! I got yet another bluetooth module that not only supported all of the features but didnt have hidden bugs that stopped them working and straight away was able to configure it to pair with the Skydrop on power up - everytime.
I found that to get it to work with the Kobo reader I had to set the UART speed to 9600 as my initial choice of 38400 was not read by XCsoar.

Thanks for the help with this, please close this request.

**Comment by fhorinek** [comment]
congrats! :)

**Comment by fhorinek** [comment]
I have different user with the same problem.
@piman-34 what module did you use eventually?

**Comment by piman-34** [comment]
The one I used was this one: [http://uk.farnell.com/webapp/wcs/stores/servlet/ProductDisplay?catalogId=15001&langId=44&urlRequestType=Base&partNumber=1857735&storeId=10151](url)
The picture on the web page is wrong it looks more like the picture attached. I have also attached a command crib sheet
[lm411-commands.txt](https://github.com/fhorinek/SkyDrop/files/793264/lm411-commands.txt)
![bm411pinout](https://cloud.githubusercontent.com/assets/18732908/23210556/003e3212-f8f6-11e6-9f33-417c71dfe240.JPG)

**Comment by fhorinek** [comment]
Great thank you!
