### ISSUE TITLE
Error in Skydrop IGC file - Header date 1970 

### ISSUE THREAD

**Issue by almonn** [fhorinek/SkyDrop#179]
2320 was supposed to have fixed this issue, but I am still getting the date '1970' in the header record.

I have forwarded the test IGC's direct by email.

A 2nd (possible) issue is point I raised a few weeks ago regarding the first few B records with lat/long of zero, but a V status (meaning no fix). I've heard Flytec had this same dilemma a few years ago, and would be good to see what their outcome was (I've prompted JohnS in the email mentioned above). I still believe these records add no value whatsoever, and indeed, cause some very odd looking traces if the software that reads the IGC file doesn't exclude them (e.g. the widely used XCplanner doesn't exclude them)

**Comment by fhorinek** [comment]
I did made the modification and fixes, see the mail

**Comment by almonn** [comment]
Hi Fero, all 7 tests during Friday/Saturday were good, so look forward to a new (formal) release, will it be soon?. Regards, Nev

**Comment by fhorinek** [comment]
formal release in the wild, closing
