### ISSUE TITLE
Problem: Update seems to fail...

### ISSUE THREAD

**Issue by Paraglider1** [fhorinek/SkyDrop#18]
After storing the two Update-Files of version 0322 on the SkyDrop and disconnecting it, the vario does not show anything on the display. Long-pressing the right button or the power-button doesn't help. Not even reconnecting via USB does not show anything at all on the display... :-(
The storage card is recognizedby the PC and can be used normally.
What can I do to re-activate it? Factory-Reset? Does unplugging of the battery help?

**Comment by wunderbaresnet** [comment]
This happened to me, too.
Are you sure you downloaded the files correctly? You have to klick on the file and then select "RAW", then it downloads. If both files are the same size (32kb), they are not correct.
To restore the device, I opened it, took out the SD card, and replaced the two files with correct ones. Everything back together, power on, updating correctly.

**Comment by Paraglider1** [comment]
Thanks for your quick answer.. :-)
So far, I downloaded the files by right-clicking in the windows-browser and "Save Target as..."
Could you please explain, how to download as "RAW"... (sorry for the silly question)

**Comment by tomasz13** [comment]
ha-ha :D 
first time, I sucked this too... :D I clicked "save link as..." & i downloaded the html path...
restore is as wunderbaresnet said... open repleace files.

**Comment by wunderbaresnet** [comment]
Click ON the file, then on RAW.
![raw](https://cloud.githubusercontent.com/assets/12966093/8280709/1ab68bdc-18e0-11e5-8f2f-5a9df689a572.jpg)

**Comment by fhorinek** [comment]
To simplify the procedure use this link
 http://vps.skybean.eu:8080/repo/updates/

**Comment by Paraglider1** [comment]
Great.... Vario is working again... 
Another question....  how do I leave "changing widgets" ? I miss the "back" option if I don't want to change anything...

**Comment by fhorinek** [comment]
@Paraglider1 please use different thread for another question
https://github.com/fhorinek/SkyDrop/issues/21

**Comment by Albifly** [comment]
I can not understand how to save the files as .raw....
