### ISSUE TITLE
Feature request: Logbook

### ISSUE THREAD

**Issue by Flyingplanet** [fhorinek/SkyDrop#180]
Hello!
It would be nice to have a logbook to read the main value of the previous flights (Vario max, vario mini, flight time, alti max...).
I use the skydrop in tandem, and it's good to be able to tell the passenger a few metrics about their flight, not only just after you've landed, but also after you've packed (it would be great to be able to recall the summary windows from last flight, even if you've turned the vario off).

A step further would be to be able to give statistics about the current and previous years (number of flights, total time flew by years) like the Reversale vario does (see 1st, 3rd, 4th and 5th screens here: http://www.reversale.com/fr/produits/vgp-loisirs/captures-d-ecran)

**Comment by fhorinek** [comment]
duplicate #73
