### ISSUE TITLE
G Record missing

### ISSUE THREAD

**Issue by mattcanning** [fhorinek/SkyDrop#181]
Since updating to build 2491, IGC logs no longer include G Record.

**Comment by fhorinek** [comment]
This is a serious bug, please end the flights using the Flight time widget (for now). The fix will be released tomorrow.

**Comment by fhorinek** [comment]
fixed skybean.eu/updates/2579/

**Comment by mattcanning** [comment]
Quick work, cheers.  Will give it a try.
