### ISSUE TITLE
Page layout

### ISSUE THREAD

**Issue by colignym** [fhorinek/SkyDrop#183]
On the split, 2 above, and one big one bellow (3 widgets)  the bottom widget text is no bigger than a 4 split page.

It would be nice to have larger text - max possible in the bottom section.
It also would be nice to ave a plain 2 x split with left and right, both giving biggest possible text.

I fly with the drop on my riser.  Large text is always nice for a quick glance on current climb rate etc.

**Comment by fhorinek** [comment]
done in next release :)
