### ISSUE TITLE
Distances.

### ISSUE THREAD

**Issue by colignym** [fhorinek/SkyDrop#184]
I know this is not a new idea, but a widget showing distance from takeoff, and total distance flown (not FIA) should be fairly simple.  The total distance already shows up in the igc file.

Maybe the more complicated requests on this enhancement can follow when these basics are in place.

Thanks in advance. For me doing mostly leisure flying, I do not desire any other device than the Skydrop 

Regards

**Comment by leachim1** [comment]
+1

**Comment by colignym** [comment]
Thank you very much, this new features in 3416 are fantastic!
