### ISSUE TITLE
Problems with SD-Card

### ISSUE THREAD

**Issue by andre-fly** [fhorinek/SkyDrop#187]
I got problems with the last update v2579.
my skydrop doesn't recognize my sd-card anymore.
so the logger doesn't work and i can not go back to an old version.
I would be happy if you have a solution.
regards andre

**Comment by fhorinek** [comment]
I have few ideas:
- disassemble the drop and check if it did not fall out
- try to format it (fat32) in pc using adapter
- If you manage to mount it in drop, format it using the drop

**Comment by andre-fly** [comment]
thanks for the advice! unfortunately formating did not work.
Finally I tried a new sd-card and that solved the problem.
