### ISSUE TITLE
One flight split in to 3 igc files 

### ISSUE THREAD

**Issue by jschustr** [fhorinek/SkyDrop#195]
Hi,
I have build 2491, rev 1506, and my last flight was splited into 3 different igc files. I didn't touch the skydrop all the time of the flight. Is it something like a bug? I am using xcsoar, so I have one igc file, but it looks strange too. Can you please check it?
Thanks a lot 
Jan

[skydrop.zip](https://github.com/fhorinek/SkyDrop/files/310417/skydrop.zip)
[xcsoar.zip](https://github.com/fhorinek/SkyDrop/files/310418/xcsoar.zip)

**Comment by fhorinek** [comment]
Please update to newest version. The last updates are solving this issues

**Comment by jschustr** [comment]
Thanks a lot! I have one more thing to think about it :-) Than I change QNH1 (with the newest FW), skydrop automatically detect take off :-)) It is just funny, its not so serious :-)
Have a nice day
Jan
