### ISSUE TITLE
No flight logged after update to 2650

### ISSUE THREAD

**Issue by flymaven** [fhorinek/SkyDrop#197]
Hi,
I just updated to Version 2650, because I also get splitted IGC-files. But after that no more flights are logged by skydrop. After the GPS-Fix und reached starting conditions I get a blicking Euro-Sign on the display, but I can't find a explanetion for that sign. 
I try it now for 4 flights, but no one was logged.
Have you an idea what is wrong?
Regards,
Ingo

**Comment by fhorinek** [comment]
Try to reformat internal sd card. Settings->Format SD

Blinking E means that log file could not be created.

**Comment by flymaven** [comment]
Hi,

thanks, if I try it, it says "no sd-card", so I reinsert it and than it 
works.
Seems the card has loosen with time, now I fixed it with cellotape.
Now in the Display there is an "L", what does this mean?

Regards,
Ingo

Am 01.07.16 um 10:37 schrieb František Horínek:

**Comment by fhorinek** [comment]
L means that logging is active
