### ISSUE TITLE
Frequent in-flight landing detections

### ISSUE THREAD

**Issue by bluearcus** [fhorinek/SkyDrop#200]
Skydrop build 2579.

I am getting regular landing detections when thermalling, this often happens more than once in every hour of flight, sometimes several times in a matter of minutes. This is very annoying as it shuts off the vario audio for a short while and can require the landing details screen to be dismissed.

This almost always seems to occur when thermalling. 

Please fix the landing detection so that a SIGNIFICANT PERIOD of either ZERO or MINIMAL LIFT/SINK must be observed along with NO or MINIMAL GROUNDSPEED before a landing event is triggered.  It's certainly not doing that at the moment. I would suggest a user parameter, default 15 seconds for the timeout and a 0.2m/s threshold on LIFT/SINK which will prevent a landing being registered.

**Comment by IB0S** [comment]
2650 is out since May 30. It's already fixed, check changelog, update, enjoy. :)

**Comment by fhorinek** [comment]
@IB0S thank you :)
