### ISSUE TITLE
Wrong NMEA checksum in LK8EX1, digifly protocols

### ISSUE THREAD

**Issue by jarda-manana** [fhorinek/SkyDrop#201]
Hi Fero, there is a bug in the NMEA checksum implementation. Checksum has to be computed from string without delimiters ($ a * chars), but you include the $ character (first character of buf).
https://en.wikipedia.org/wiki/NMEA_0183#C_implementation_of_checksum_generation

Thanks for fix, XCTrack will check lk8ex1 checksum in the near future.

**Comment by fhorinek** [comment]
Fixed
