### ISSUE TITLE
Badly formed IGC file - multiple records for one time

### ISSUE THREAD

**Issue by bluearcus** [fhorinek/SkyDrop#203]
Skydrop with latest firmware, 2784.

IGC file generated contains many instances of more than one record for a particular time.
There should be only one single record for any time - some online flight tools reject this file (e.g. UK xc league).

I've attached the IGC file and a csv file which shows the problem records. They are indicated by a 0 value in the interval column (as they have the same timestamp as the previous record).
 
[02-1222-IGC.txt](https://github.com/fhorinek/SkyDrop/files/424716/02-1222-IGC.txt)
[02-1222.txt](https://github.com/fhorinek/SkyDrop/files/424712/02-1222.txt)

Cheers,

Mike

**Comment by fhorinek** [comment]
Funny fact, GPS module is sending the same time.

Anyway fixed in next release. Thank you for the report :)
