### ISSUE TITLE
Update from configurator

### ISSUE THREAD

**Issue by colignym** [fhorinek/SkyDrop#204]
Whether using firefox or Chrome, when "save with firmware" is selected, or "download configuration with firmware" nothing happens.

Doesn't work

**Comment by fhorinek** [comment]
sorry I did wrong upload, thank you for this report fixed

**Comment by colignym** [comment]
Thanks, but now the upgrade to 3063 in top right corner does not work
anymore.

**Comment by fhorinek** [comment]
please do not upgrade to 3063 there is bug in updater. This was the reason why I tried to pull it out. Please be patient, our build computer is curently without the internet connection. As soon as it will be online I will release new build without the bug.

**Comment by douglasfurby** [comment]
what should I do having updated to 3063? 
I am trying to update to 3079 but keep getting the error code 163

**Comment by fhorinek** [comment]
from what build did you tried the update?

**Comment by douglasfurby** [comment]
I tried updating from build 3063 to build 3079

**Comment by fhorinek** [comment]
put this file to you skydrop and press and hold the right button.
This is RAW (fallback) update method
[UPDATE.FW.zip](https://github.com/fhorinek/SkyDrop/files/447766/UPDATE.FW.zip)

**Comment by douglasfurby** [comment]
Thanks all seems to be working now.

**Comment by fhorinek** [comment]
cool, happy to help
