### ISSUE TITLE
Take off detected during manual ALT1 calibration

### ISSUE THREAD

**Issue by tofuatjava** [fhorinek/SkyDrop#205]
* Upgraded to latest and greatest firmware (3079).
* move to and edit ALT1 on the second screen
* reduce the altitude from above 300 to about 250 by press and hold the left arrow button
* TAKE OFF was displayed and the vario makes some noice

**Comment by sirgijan** [comment]
I think my issue is similar, when I change alt on my screen, I heard vario sound, and then device go crazy, and after 2 seconds screen turn off, but sound is still there. Then I must power it off using power btn. Latest hardware (I bought my device last week), and firmware is 3079.

**Comment by sirgijan** [comment]
Bus is fixed with latest update. Thanks
