### ISSUE TITLE
"File" Browser

### ISSUE THREAD

**Issue by leachim1** [fhorinek/SkyDrop#208]
I would like to have a file browser, to take a look on the last >4 flights. With min max: hight and avg climb, distance, maybe fai? ...

**Comment by Flyingplanet** [comment]
It seems to me that's almost the same feature as requested here: https://github.com/fhorinek/SkyDrop/issues/73 and I totally agree that this is a missing feature in the skydrop right now (which appart from this is a great vario-gps)

**Comment by fhorinek** [comment]
done
