### ISSUE TITLE
USB connection win7

### ISSUE THREAD

**Issue by mattbio** [fhorinek/SkyDrop#211]
My computer(s) can t detect my skydrop...
I have that problem with win7 64 bits. I tried witch several cables and PC (another win7).
The skydrop screen shows "USB MODE/ idle", is charging, I enable the setting "mass storage" but i can t see it anyway...

So strange!

**Comment by fhorinek** [comment]
Please specify **build** number and board **rev**ision

**Comment by mattbio** [comment]
Build number :2650
Board révision: 1506.

**Comment by mattbio** [comment]
As I wrote To skybean support team: after updating my 2 skydrops in build 3072,  problems aren t solved.
one is still not detected by Windows, the other cant be charged.

**Comment by fhorinek** [comment]
I am sorry but, we are unable to replicate the error.

Please write email to info@skybean.eu for return instructions.
Refer this post in the message.

**Comment by piman-34** [comment]
Got mine back today all fine now :-)

thanks for a great service :-)
