### ISSUE TITLE
Display broken (Skydrop V2)

### ISSUE THREAD

**Issue by JOSEFILHO88** [fhorinek/SkyDrop#212]
Hi,
I had a landing problem and the display is broken as in the picture attached.
I would like to know what can I do to fix it.
The vario is still working fine, doing logs and sounds, seems that the problem is only in the display.
My Skydrop is the newest version (V.2)
I already sent an email to info@skybean.eu  but no answer till now
Thanks in advance,

![2016-09-12 09 33 28 large](https://cloud.githubusercontent.com/assets/20577524/18504114/e3a7b0ec-7a60-11e6-9f12-ea49decdaade.jpg)

**Comment by fhorinek** [comment]
The screen is mechanically broken. We will need to replace it. 
More information in mail
