### ISSUE TITLE
Timeschedule for Wind calculation

### ISSUE THREAD

**Issue by Herby** [fhorinek/SkyDrop#213]
Hi,
first of all i have to congratulate to your Instrument Skydrop.
The community is waiting for the wind calculation. A datafield like "SW 12" wich indicates a wind coming from the SW with 11 km/h would be sufficient.
When is the implementation planned?
Thanks
Herby

**Comment by fhorinek** [comment]
in ~one month, we already have working implementation on pc, now we will need to put it in SkyDrop

**Comment by fhorinek** [comment]
There is a beta release of wind estimation http://vps.skybean.eu/repo/updates/3246/
