### ISSUE TITLE
Update Error #163

### ISSUE THREAD

**Issue by ZIRminator** [fhorinek/SkyDrop#216]
I have problems with the update. No matter which update version I use, I get always the same Error: #163.

Currently using build 3063

**Comment by fhorinek** [comment]
3063 was experimental so... 
the update procedure si corrupted there.

go here for "recovery files" (RAW update files)
http://vps.skybean.eu/configurator/fw/00003092/
copy UPDATE.EE and UPDATE.FW to the skydrop and press and hold right button

**Comment by ZIRminator** [comment]
Thank you! Worked well!
