### ISSUE TITLE
skydrop  no power at all afther landing

### ISSUE THREAD

**Issue by rgagne002** [fhorinek/SkyDrop#217]
I use it for 3 months, it  was ok.  Last week it came dead after landing 
I charged it over night . Next day it still dead  ,disconnected the battery ,removed the SD card and put it back and connect the battery. It did blink once and then still nothing at all.
What is next
Robert

**Comment by fhorinek** [comment]
This is something new for me.
We will need to inspect the device to solve the issue.

Please write email to info@skybean.eu for return instructions.
Refer this post in the message.
