### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by kostik** [fhorinek/SkyDrop#218]
I bought SkyDrop vario some time ago and I am really happy with it. But I also use FlySkyHigh app on my iPhone, and I wonder when you are going to add iOS device support?

**Comment by fhorinek** [comment]
yes the FlySkyHigh will support SkyDrop very soon

**Comment by kostik** [comment]
Thanks!
Is there any other iOS app with SkyBean support?

**Comment by fhorinek** [comment]
There will be also compatibility with SkyLogger in near future

**Comment by fhorinek** [comment]
Done
