### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by tomasz13** [fhorinek/SkyDrop#219]
Ahoj, 
Keď ho upgradenem na vyššiu verziu ako 2784, tak sa nepripojí k xctrack cez Bluetooth. (Rev1504)

**Comment by fhorinek** [comment]
ahoj, aky mas bt modul?

**Comment by tomasz13** [comment]
pan1322v2.1

**Comment by fhorinek** [comment]
skus upgrade, vela veci sa opravilo

**Comment by tomasz13** [comment]
ano, diky vo Build 3244 to uz funguje :+1:
