### ISSUE TITLE
Where is GPS data stored?

### ISSUE THREAD

**Issue by Paraglider1** [fhorinek/SkyDrop#22]
How do I start and stop GPS tracking and where is GPS data stored?
I enabled GPS and after a while a had a static "G" on the display.
After some hours of moving and driving around with the vario, I checked the data on the card, but no files could be found...

**Comment by fhorinek** [comment]
The logger function is not yet implemented. Gps is now used just for ground speed and heading

**Comment by Sabistik** [comment]
Hi, i have question about this functionality. Is it still not ready? Please increase the priority ;) I think it is a main feature :)

Regards!

**Comment by fhorinek** [comment]
Now it is the highest priority to build foundation for pc configurator. We really need something to configure the device. I want the tracking as much as you do, maybe even more. But function like this is not something what can be easily done... unfortunately

**Comment by Sabistik** [comment]
Ok, thanks for info and i wish you nice and easy work!

**Comment by fhorinek** [comment]
IGC logging will be avalible in next release
