### ISSUE TITLE
Add time of take-off and landing to KML log

### ISSUE THREAD

**Issue by fhorinek** [fhorinek/SkyDrop#223]

**Comment by bubeck** [comment]
One idea to implement this could be to write the following element in the header of the KML file and save the file pointer position (f_tell) of the content of the "end" element. Then in kml_stop() go back in the file to the saved position and rewrite the end content with "now".

    <Document>
      <TimeSpan>
        <begin>2011-01-16T23:59:00Z</begin>
        <end>2011-01-16T23:59:11Z</end>
      </TimeSpan>
    ....
    </Document>
