### ISSUE TITLE
Configurator - GPS Compass Arrow widget and others

### ISSUE THREAD

**Issue by IB0S** [fhorinek/SkyDrop#230]
Editing widgets with the web configurator and adding a GPS Compass Arrow results in an empty widget configuration on the selected box. (Adding it on the device works perfectly.)

Wind Direction Arrow description needs update (it displays "Arrow showing actual GPS heading").

Please include in the description if an arrow or heading widget is relative to something else or absolute.

**Comment by fhorinek** [comment]
Fixed, thank you
