### ISSUE TITLE
Wind indication doesnt work

### ISSUE THREAD

**Issue by Herby** [fhorinek/SkyDrop#232]
I could test the wind indication on version 3248 in about 3 flights with a total duration of 3 hours. I displayed the windspeed and the winddirection.
The winsspeed calculation is not correct. Although we had an estimated windspeed from E, may be 10-15 km/h, the indication of the skydrop was in the range of 0.7 to 0.9 km/h. 
Next time i will connect the skydrop with my mobile phone running xctrack and compare the wind calculation.

**Comment by fhorinek** [comment]
Thank you for the test, please include zip with IGC files for our internal testing of the algorithm.
The wind speed and direction is in beta state right now.

**Comment by Herby** [comment]
Hi fhorinek,
please find the igc-files attached.
We dont need fractions of km/h of the windspeed. I would like the following format:
"12 SW" like 12km/h wind from SW. The same format for groundspeed and heading would be nice. This allows more information in bigger font on one single datapage.
If you like, i could support you with a validated algorithm for the wind calculation. I need your personal mailaddress if you are interested.
Kind Regards
Herby   
[Wind.zip](https://github.com/fhorinek/SkyDrop/files/639055/Wind.zip)

**Comment by fhorinek** [comment]
Yes I am interested. My address is frantisekhorinek@gmail.com

**Comment by Herby** [comment]
Sorry, accidentally i closed this issue before
Herby
