### ISSUE TITLE
GPS not fixing anymore :(

### ISSUE THREAD

**Issue by Flyingplanet** [fhorinek/SkyDrop#234]
Hello,
During my last flight, I couldn't get a GPS fix at all (2 hours flight, tried to restart the skydrop). Sky was clear blue (we were above the stratus).
I have latest available firmware version
What's going on ? I couldn't record my little XC today :(

**Comment by Flyingplanet** [comment]
I can't get any fix since then, even after leaving my skydrop on the terrasse (clear sky) for 25' (then the autostop shuts the device down). Attached is the log.
I hadn't any issue with the gps fix before... tried formatting the card (via the menu), reinstalling latest firmware. No chance :(
[DEBUG.TXT](https://github.com/fhorinek/SkyDrop/files/679980/DEBUG.TXT)

**Comment by fhorinek** [comment]
Unfortunatly no clue, please write RMA request to info@skybean.eu, we will repair or replace the gps module.
