### ISSUE TITLE
HAGL field is empty

### ISSUE THREAD

**Issue by kostik** [fhorinek/SkyDrop#239]
My coordinates are ≈50 ≈-119, I created AGL folder on SkyDrop, and the relevant files are definitely there:
<img width="634" alt="screen shot 2017-01-30 at 4 44 00 pm" src="https://cloud.githubusercontent.com/assets/282103/22448047/6779436a-e70b-11e6-9d48-09479af92ce4.png">

But HAGL field is still empty ("---") after SkyDrop got GPS fix.

**Comment by fhorinek** [comment]
can you enable in debug menu -> debug.log and debug GPS
try it again 
and attach debug.log here in zip after?

**Comment by kostik** [comment]
Here it is:
[DEBUG.LOG.zip](https://github.com/fhorinek/SkyDrop/files/743850/DEBUG.LOG.zip)

**Comment by kostik** [comment]
Do you need anything else from my side?

**Comment by fhorinek** [comment]
Did you enable record screen in debug menu?
If so please disable it. Then clear the log file. Restart the Vario and try it again.

**Comment by kostik** [comment]
Here it is - without "screen record".
The HAGL field is still empty

[DEBUG.LOG.zip](https://github.com/fhorinek/SkyDrop/files/811925/DEBUG.LOG.zip)

**Comment by kostik** [comment]
Any updates?
Still is not working.

**Comment by vesloclup** [comment]
[DEBUG.zip](https://github.com/fhorinek/SkyDrop/files/835027/DEBUG.zip)
same problem here...

**Comment by kostik** [comment]
@vesloclup Do you live in the western hemisphere?

**Comment by vesloclup** [comment]
No - I'm from Europe

**Comment by bubeck** [comment]
I saw, that you use HAGL at a latitude >= 50. As I found out, there is a different resolution for HGT files above lat 50, which is currently not understood by skydrop. Could you please tell me the exact file size of your HGT files, that should be used by skydrop?

I am currently preparing  a patch for SkyDrop to handle that file sizes, if this is your problem.

**Comment by kostik** [comment]
<img width="589" alt="screen shot 2017-03-19 at 12 58 08 pm 1" src="https://cloud.githubusercontent.com/assets/282103/24084250/ce3b4586-0ca3-11e7-8c92-5cc874d012cf.png">

**Comment by bubeck** [comment]
The bug has been fixed in https://github.com/bubeck/SkyDrop/commit/91fcc96b67a801751c7b2dea1223350fd4a8c832 and will be sent to fhorinek, if his PULL queue is empty.

The problem was a negative latitude or longitude, which did not occur in europe, so we did not suffer from the bug. I apogolize for any inconvience and the long time needed to fix it. :(
