### ISSUE TITLE
Contrast settings need refinement

### ISSUE THREAD

**Issue by wunderbaresnet** [fhorinek/SkyDrop#25]
Be aware that changing contrast by more than 10% will result in a white or black display, rendering the device unusable (until you do a firmware update).

Settings should be in a range where it is still possible to use the device (60 .. 75% in my case).

**Comment by atomphil** [comment]
Thats the same I thought at first, but the usefull range is very device-dependent. And it is much influenced by the pressure that the case applies to the display. A hardware design bug in my opinion.

**Comment by fhorinek** [comment]
There is new way how to define min and max contrast value. It will be fixed in next relase.
