### ISSUE TITLE
more control over weaklift frequency

### ISSUE THREAD

**Issue by maticus** [fhorinek/SkyDrop#253]
Currently (build 3395) the weaklift frequency setting sets just the lower bound. The steps are linearly interpolated up to lift frequency, eg.: -0.3 gives 60Hz, -0.2 -> 189Hz, -0.1 -> 318Hz, 0.0 -> 447Hz, lift 0.1 -> 577Hz. 
It would be nice to be able to **specify weaklift upper bound frequency** separately of the lift frequencies, to have eg. something like that: -0.3 -> 60Hz, -0.2 -> 100Hz, -0.1 -> 140Hz, 0.0 -> 180 Hz, lift 0.1 -> 577Hz

**Comment by tomasz13** [comment]
I would like it too.

**Comment by fhorinek** [comment]
will be done in next release
