### ISSUE TITLE
GPS and Baro height

### ISSUE THREAD

**Issue by colignym** [fhorinek/SkyDrop#254]
On my IGC file, when viewed afterwards, the Baro height shows an average of 60m lower than GPS height. 
The GPS heights are correct, and the Baro height during flight are correct as well.

I also found the new "distance from home" widget showed zero during flight.  I thought it will use the take off as "home"  Will have to fly with it again to confirm.
The odometer works very well though.

Thanks

**Comment by fhorinek** [comment]
The igc altitude is using standard pressure 1.01325 bar as defined in the
specification
