### ISSUE TITLE
wind direction & speed widget

### ISSUE THREAD

**Issue by pturri** [fhorinek/SkyDrop#26]
I deem this is the only missing feature to make Drop a fully self-sufficient device.

**Comment by fhorinek** [comment]
This is also my dream, but so far not a priority.

**Comment by fhorinek** [comment]
Also if you know good wind estimation algorithm please send me link (or code).

**Comment by pturri** [comment]
well, I guess also building a brand new device from scratch is the result of a "dream", and you coped with it very well :)
Then, keep working on your dreams!
By the way: good job indeed!

**Comment by bluearcus** [comment]
There's a nice discussion of a good algorithm on the BlueFly blog:

http://blueflyvario.blogspot.co.uk/2012/09/calculating-wind-speed-from-gps-track.html

**Comment by rmerigan** [comment]
There is another way to calculate wind without turning using IMU, compass gps. William Premerlani wrote a paper on it http://diydrones.com/forum/topics/wind-estimation-without-an
Or if you Google imu wind estimation theory plenty available

**Comment by fhorinek** [comment]
Done in new release
