### ISSUE TITLE
Skydrop dont boot after Upgrade to Build 3466

### ISSUE THREAD

**Issue by leachim1** [fhorinek/SkyDrop#261]
I upgradet my Skydrop from 3395 to Build 3466 over the Configurator. After the Upgrade Skydrop doesnt start anymore. I tried to Flash it again. Skydrop asked for a reset Defaults (becouse of the Same Firmware Version) --> nothing changed still not booting.

**Comment by leachim1** [comment]
I tried now: Downgrading to several old Versions + Deleting all Configuration/Reset + Remove SD Card. Nothing works, when i boot my Skydrop i get a horizontal line for some micro seconds and then a blank screen.
It would be very nice if you can give me at least a short response. 
The main season is starting and my main vario is dead 👎

**Comment by fhorinek** [comment]
Sorry I was on vacation last week with no internet connection.

Can you use usb mode?
Can you see vario storage in your pc?

Try to copy UPDATE.EE and UPDATE.FW to the storage and than press and hold the right button.
There should be yellow light during firmware update.
after that power it normaly the "update.ee applied" should pop up.

**Comment by leachim1** [comment]
I ve uploaded you a short Video: https://youtu.be/ICbcyKyTbnQ

**Comment by leachim1** [comment]
And here i copied 1278 UPDATE.EE and UPDATE.FW to the storage and pressed and hold the right button:
https://youtu.be/2q25UO_d2qc

still not working but at least i can see the boot logo now... https://youtu.be/mgNh78nwFFE

**Comment by fhorinek** [comment]
try this update files from here http://vps.skybean.eu/configurator/fw/00003466/

**Comment by leachim1** [comment]
Still the same Situation

**Comment by tomasz13** [comment]
And what kind of sdcard do you have in the device? The original 4GB or a bigger one?

Because when I "upgraded" to a 16GB, I has a same trouble. ;)

**Comment by leachim1** [comment]
I have still the original 4GB SD Card. But i am going to try a different one.

**Comment by fhorinek** [comment]
Can you boot without the SD card?

**Comment by leachim1** [comment]
Now i tried two different 2GB Cards and two different 4GB Cards. Empty and with data. With the .fw and .fw+.ee. Also without SD Card, but noting works still the same Problem.

**Comment by fhorinek** [comment]
Then I am afraid that you need to send us the device back for repair. 
Please write to info@skybean.eu and ask for return address. Refer this link and mention that Fero (me) is aware of the situation. We will fix it as soon as possible.
