### ISSUE TITLE
Skydrop Log

### ISSUE THREAD

**Issue by jugglerstx** [fhorinek/SkyDrop#263]
what is the "raw" format of the logger. What software is able to read this format ?
Thank you for your help.

**Comment by jugglerstx** [comment]
one other question : what is the "raw" format of the logger. What software is able to read this format ?
Thank you for your help

**Comment by fhorinek** [comment]
The raw format contains only raw data from all sensors.
It is used for special purpose, testing or for advanced users. 

you can use this python utility to convert raw data to csv file
https://github.com/fhorinek/SkyDrop/blob/master/skydrop/utils/raw_parser/raw_parser.py
