### ISSUE TITLE
more pages

### ISSUE THREAD

**Issue by tomasz13** [fhorinek/SkyDrop#264]
will be good to activate more pages then 5 (maybe max 10)

bolo by dobre zvisit pocet stran, lebo mame mrte fasa widgetov, ale malo miesta na zobrazenie...

**Comment by fhorinek** [comment]
I can give you 8 pages, will this be enough for you?

**Comment by tomasz13** [comment]
Amazing ;)

**Comment by fhorinek** [comment]
it was easy enough so it will be avalible in next release
