### ISSUE TITLE
Timezone H record

### ISSUE THREAD

**Issue by johnstevenson** [fhorinek/SkyDrop#275]
Fero, this is wrongly formatted: `HTZN0.0000000.1` and the data doesn't make much sense! (from build 3466 IGC files, although I see you have added a commit to change this to `HFTZN` ).

The format for H records is (spaces added) `H F CCC LONGNAME : value` where `CCC` is the appropriate three-character code, the long name is the subject of the record and all this is separated from the value by a colon.

So the value should be prefixed with `HFTZNTIMEZONE:`

The spec describes the value as: "Time Zone Offset, hours from UTC to local time" so I'd guess `1` or `1.0` for a UTC offset of  plus 1 hour.

**Comment by bubeck** [comment]
Patch is applied in master branch by Fero, so this can be closed (or seen as closed. :)
