### ISSUE TITLE
Winddirection points

### ISSUE THREAD

**Issue by Herby** [fhorinek/SkyDrop#282]
Hi Skydropteam,
it would be nice, if you implement a new widget "wind direction points", in order to see N, NE, etc.

Thanks for your good work.

Kind Regards
Herbert

**Comment by fhorinek** [comment]
will do :)

**Comment by fhorinek** [comment]
done in next

**Comment by Herby** [comment]
Sorry, it doesn't work in any layout in 3801, only an empty field is shown.  
Please correct as soon as possible
Kind Regards
Herby
