### ISSUE TITLE
Feature request - 90 / 270 screen rotate.

### ISSUE THREAD

**Issue by bluearcus** [fhorinek/SkyDrop#286]
Is it possible to have two more screen modes, at 90 and 270 degrees rotation? I would like to mount the skydrop sideways on my flight deck? Obviously this would require new screen layouts / widget dimensions too...

**Comment by fhorinek** [comment]
Unfortunately the lot of gui elements are hard wired to current resolution, it is not doable without rewriting lot of stuff.

Sorry
