### ISSUE TITLE
accelerometer calibration

### ISSUE THREAD

**Issue by tomasz13** [fhorinek/SkyDrop#287]
ahoj, 
ako sme to Kossene preberali... neide mi kalibracia akcelerometra vo verzii FW3802, board1506, acc.sens275927292686, mag.bias-1082-554996, mag.sens603859545836, gyro.bias-28.2 21.8-13.2
asi je to nejaky bug.... prosim ta o opravu, dakujem :)

**Comment by tomasz13** [comment]
hi, 
I can't calibrate the accelerometer on my skydrop. Can you fix it please? thanks

**Comment by fhorinek** [comment]
ahoj, skus toto
[SKYDROP.FW.zip](https://github.com/fhorinek/SkyDrop/files/1102639/SKYDROP.FW.zip)

**Comment by fhorinek** [comment]
ten update pomohol?
