### ISSUE TITLE
SD Card not working

### ISSUE THREAD

**Issue by trashmaster9000** [fhorinek/SkyDrop#290]
Hi,

i bought my Skydrop 3weeks ago. i flew with it 3-4 times since i got it (last time 2 weeks ago). i want to fly tomorrow so i checked my equipment and my Skydrop is now Faulty?

if is start the flight timer i get an error message "SD card error!".
if i choose to format the SD card i get the message "No SD card"

if i plug the skydrop via USB in my PC i can see the content of the SD card and add/delete files.

SKYDROP.FW gets ignored...

FW: 3802
rev. 1506

edit:
i disconnected the battery and removed / inserted the SD card, didnt help

**Comment by fhorinek** [comment]
Please try to format the sdcard in pc in fat32 format

**Comment by trashmaster9000** [comment]
ok, formated the original SD card (no quickformat)
same problem.

tryd a new sd card, same problem.

**Comment by fhorinek** [comment]
The drop might have some problems with large cards.

Please make sure that the original card is formatted and fully inserted
into the drop.

If this does not work we will send you a new one.

**Comment by trashmaster9000** [comment]
i have tested a 1Gb noname card, does not work...

the card is fully inserted, i can acces the card through usb...

**Comment by fhorinek** [comment]
try this experimental fw
[SKYDROP.FW.zip](https://github.com/fhorinek/SkyDrop/files/1102626/SKYDROP.FW.zip)

**Comment by trashmaster9000** [comment]
i cant update the Firmware...

i connected the skydrop via usb and copied the file onto the sd-card.
the bootloader does not ask me to update the firmware.

i have arduinos and an USBASP. can i flash the firmware directly?

**Comment by fhorinek** [comment]
my bad, try this, this will be read directly by the bootloader
[Release.zip](https://github.com/fhorinek/SkyDrop/files/1108708/Release.zip)

you can't use ISP whith xmega mcu since they use another interface called PDI

**Comment by trashmaster9000** [comment]
ok, it works now.

what was the problem?

**Comment by fhorinek** [comment]
the problem is hardware, 
you have some derbies in sdcard detect switch
usb mode ignores the switch as well as bootloader
now the main firmware will ignore the switch as well
