### ISSUE TITLE
Shut down on usb connection

### ISSUE THREAD

**Issue by tchewitt** [fhorinek/SkyDrop#292]
Hi,

I fly with the skydrop with an external battery. If the battery disconnects and reconnects the skydrop shuts down. This breaks the igc log.

Can this be disabled?

Thanks

Tom

**Comment by fhorinek** [comment]
this is not standard behavior, do you have enabled mass storage in settings?

**Comment by tchewitt** [comment]
Yes it was enabled, I guess that is the cause. I have disabled it.

Very fast response in time to fly today, big thanks
