### ISSUE TITLE
HAGL is negative when lon or lat is negative

### ISSUE THREAD

**Issue by kostik** [fhorinek/SkyDrop#297]
I guess #270 by @bubeck did not fix the bug: I now have negative HAGL, like "-700" or so (I previously reported about empty HAGL field in #239, which is now closed). 

Please find the log attached.

[DEBUG.LOG.zip](https://github.com/fhorinek/SkyDrop/files/1254147/DEBUG.LOG.zip)

**Comment by bubeck** [comment]
I will take a look

**Comment by bubeck** [comment]
@kostik I developed a GPS simulation (https://github.com/fhorinek/SkyDrop/pull/301) which will allow me to 'fly' your path to see the problem and fix it once and forever. 

I need a GPS track in any file format for the area where you see the problems. Could you please provide on here as a attachment? Thanks!

**Comment by kostik** [comment]
a short one

[2017-05-06-XLK-KOI-03.IGC.zip](https://github.com/fhorinek/SkyDrop/files/1275754/2017-05-06-XLK-KOI-03.IGC.zip)
