### ISSUE TITLE
Log file time zones

### ISSUE THREAD

**Issue by mdt733** [fhorinek/SkyDrop#303]
The igc log files seem to get saved to the SD card in raw GPS time without considering the local time zone, not a complicated mental conversation, but it would be nice if for example a 9am (local time) flight got a file name '01-0900.igc'

**Comment by bubeck** [comment]
Yes, I agree. The **filename** should be in local time.

However, the contents of the file is still UTC, but together with a time zone, so I see no reason to change this.

**Comment by fhorinek** [comment]
ok i will change the behavior to use local time

**Comment by fhorinek** [comment]
done in next release
