### ISSUE TITLE
Not working at all.

### ISSUE THREAD

**Issue by bjkv** [fhorinek/SkyDrop#304]
My SkyDrop refuses to start logging automaticly, and when I choose menu item "Vario" it shuts down.

**Comment by fhorinek** [comment]
Please specify build number and hw revision.

**Comment by bjkv** [comment]
Build number 3824 rev 1506

**Comment by fhorinek** [comment]
please try upgrade to newest version with default configuration. 
https://vps.skybean.eu/repo/updates/3850/

**Comment by bjkv** [comment]
Done! Seem to have fixed the problem with vario-menu. On my next flight I will try and see if it works :)
