### ISSUE TITLE
Wrong IGC file 

### ISSUE THREAD

**Issue by ulipo** [fhorinek/SkyDrop#308]
Since I updated to FW 3836 I cannot upload any tracklog to XContest, it results in "Errors occured during data processing!"

Trying to compare an old (working) IGC and a new one, I found a relevant difference between the fix records:

before 3836:
B1051114226441N01333511EA0196202086
B1051124226439N01333502EA0196002086
B1051134226437N01333496EA0195902086
B1051144226435N01333490EA0195802085

with 3836:
B1349584347851000102518830+43.79751660102518830+43.7975166A00024-0041
B1349594347846400102518950+43.79744000102518950+43.7974400A00022-0042
B1350004347842300102519160+43.79737160102519160+43.7973716A00021-0040
B1350014347838800102519420+43.79731330102519420+43.7973133A00021-0041

**Comment by fhorinek** [comment]
Fixed in 3850
thank you for your report!
