### ISSUE TITLE
Bug: Alt2

### ISSUE THREAD

**Issue by atomphil** [fhorinek/SkyDrop#31]
It relative to itself in the standard config. I ve to set it to an other ref value to make Alt2 and Alt3 stop counting useless values.

**Comment by atomphil** [comment]
and it is possible to set alt2 -> alt3 AND alt3 -> al2 .... this should be prevented

**Comment by fhorinek** [comment]
TODO: 
fix default EE configuration
fix cyclic Alt configuration
