### ISSUE TITLE
android BlueTooth "Can't communicate with SkyDrop" without APP

### ISSUE THREAD

**Issue by tomasz13** [fhorinek/SkyDrop#313]
I would like to use my SkyDrop as a "Trusted device" in Andoid 7.1.2 Nugat's Smart Lock setup. Thus I could automate the flight computer's starting process even if the phone accidentally reboot when I'm in the air.
For this reason I need to connect the SkyDrop with phone immediately when i switch on the vario.
Now it only connects, when i start the application, like xctrack or lk8000... 

(After phone's reboot, or application crash, I must manually unlock the screen with slide up, enter the pin, click on apps icon... and that is so hard when you have a big gloves on your hands) 
WINTER IS COMING! :smile:  :snowman_with_snow:

**Comment by fhorinek** [comment]
Unfortunately SkyDrop is acting as slave device. We can't establish the connection from the SkyDrop with current profile (SPP).
