### ISSUE TITLE
Acromode

### ISSUE THREAD

**Issue by stuvat** [fhorinek/SkyDrop#315]
Is there any way to get an audio alarm when crossing a set altitude?  Would be nice for acro pilots to have som help remembering when to stop manouvers and head towards landing.  If possible 2. one "exit" alarm, and one "EXIT NOW" alarm

**Comment by fhorinek** [comment]
This is pretty straightforward. I will add this function

**Comment by fhorinek** [comment]
I will release software update. Then everybody with skydrop can upgrade for free.

**Comment by stuvat** [comment]
You rock! Does it take long?



Sendt fra min Samsung Galaxy-smarttelefon.


-------- Opprinnelig melding --------
Fra: František Horínek <notifications@github.com>
Dato: 16.11.2017 20:32 (GMT+01:00)
Til: fhorinek/SkyDrop <SkyDrop@noreply.github.com>
Ko: stuvat <sture_vatnehol@hotmail.com>, Author <author@noreply.github.com>
Emne: Re: [fhorinek/SkyDrop] Acromode (#315)


I will release software update. Then everybody with skydrop can upgrade for free.

**Comment by fhorinek** [comment]
Approx two weeks, since this week I am out of office

**Comment by stuvat** [comment]
Did you get this done?

**Comment by stuvat** [comment]
Ideally!
Push  button at landing to calibrate. 
1 alarm at 200m. 2 alarm at 100m.  Posebillity to mute each alarm after triggere.
And 1 more mode! 
Calibrate at lowest point of hang. 1 alarm 100m above. 2 alarm at calibration  hight. 
I made this with an arduino, but i think it is much better to have it combined with  the skybean.

**Comment by fhorinek** [comment]
I am sorry for the delay but currently there is very little time for this. But I will try to make time to do this this week.

**Comment by fhorinek** [comment]
I have released the update for the altitude alarm, so far only two fixed values are available.
The alarm will flash and beep displaying current altitude.
After the second value is reached the alarm will be even more annoying.
You can dismiss the alarm with the middle button.
The alarm will rearm if you surpass the alarm altitude by configurable reset height.

**Comment by stuvat** [comment]
Awesome! Ordering a skydrop tonight :)



Sendt fra min Samsung Galaxy-smarttelefon.


-------- Opprinnelig melding --------
Fra: František Horínek <notifications@github.com>
Dato: 20.02.2018 13:57 (GMT+01:00)
Til: fhorinek/SkyDrop <SkyDrop@noreply.github.com>
Ko: stuvat <sture_vatnehol@hotmail.com>, Author <author@noreply.github.com>
Emne: Re: [fhorinek/SkyDrop] Acromode (#315)


I have released the update for the altitude alarm, so far only two fixed values are available.
The alarm will flash and beep displaying current altitude.
After the second value is reached the alarm will be even more annoying.
You can dismiss the alarm with the middle button.
The alarm will rearm if you surpass the alarm altitude by configurable reset height.

**Comment by tomasz13** [comment]
it would be good to set the upper limit of the altitude...
