### ISSUE TITLE
No GPS fix and also no recognition of home files

### ISSUE THREAD

**Issue by Evelcyclops** [fhorinek/SkyDrop#316]
Hello,

Just bought your sky drop, haven't had a chance to try it yet but so far quite impressed with the functionality, however i have 2 issues:

1. my skydrop cannot get a fix - i can see that it can find satellites, but cant fix. Followed advice here and debug logged outside for 15 minutes, please find attached. I've dismantled and checked out the hardware - connections seem fine and no clear signs of damage. 

[DEBUG.LOG](https://github.com/fhorinek/SkyDrop/files/1545272/DEBUG.LOG)

2. I've created  home location files, created a folder in the skydrop SD called "HOMES" (Will not allow me to name it \HOMES) however not only are they not visible in the skydrop, the "SD Card" selector in the skydrop itself in the 'Home' settings is greyed out and cant select it at all. Not sure if i've done the right thing to create a file called home, or there should already be one present but i need some help!

Regards,

Arran

**Comment by Evelcyclops** [comment]
Homes issue fixed ;) still no joy on gps though.

**Comment by fhorinek** [comment]
for the first time the gps will take some time to get the fix.
please be test this outside with good visibility to sky.
Do not assume smartphone speed for fix, we do not have data from gsm network to assist

**Comment by Evelcyclops** [comment]
I’ve had it for a week now, still no GPS. It’s been left outside till it auto shuts down. :(

**Comment by Evelcyclops** [comment]
Sorted thanks

**Comment by fhorinek** [comment]
@Evelcyclops how?
