### ISSUE TITLE
Custom Logo

### ISSUE THREAD

**Issue by Evelcyclops** [fhorinek/SkyDrop#318]
Hi, i'd like to add my own custom logo, but unfortunately i am a complete dunce with regard to coding - ive tried following your instructions, but 'm afraid its beyond me.

would you be able to do a video for it or help with more detailed instructions please? would be very helpful :)

**Comment by bubeck** [comment]
Yes, i will. Please give me a few days.

**Comment by bubeck** [comment]
A tutorial video can be found at https://youtu.be/69Z_eXo92eQ
