### ISSUE TITLE
Skydrop dont start.

### ISSUE THREAD

**Issue by leachim1** [fhorinek/SkyDrop#320]
Hello,

i just wanted to download my log files after a nice flying day. My Computer told me that the Device is not working and asked if i wanna format the SD card. Since that the device just started one again and asked me to format the sd card. I agreed but since that the device does not start anymore.

**Comment by fhorinek** [comment]
carefully disassemble the device an pull out the sd card
https://www.youtube.com/watch?v=EAom7rh_F00
then try to start the device
The sd card might be broken

**Comment by leachim1** [comment]
i took the sd card out, tried to start the device but nothing happend.
The i plugged in the usb cable and after some time the device suddendly started.
so i turned it off and put in a new 2GB SD Card empty formated as Fat32. But still the device does not start, even not when plugging in the USB Cable.

**Comment by fhorinek** [comment]
- try putting UPDATE.EE and UPDATE.FW from https://vps.skybean.eu/configurator/fw/00003906/ to fresh formated sd card to fat32
- unplug the battery connector
- insert the card
- plug back the connector
- is there a yellow light?

**Comment by leachim1** [comment]
I had some Competitions in the last days, so unforunally i had to buy another Vario and there was just a few time to test. But now i tried everything. Nothing happens and there is no yellow light. My new theorie was that maybe the on/off button is dead and it just awakes by plugin the USB wen the battery is a bit low. But it doesn seems to be the case, it just randomly starts sometimes wehen usb is plugged in :-(
