### ISSUE TITLE
Cycling the screens.

### ISSUE THREAD

**Issue by lemonydes** [fhorinek/SkyDrop#328]
It is possible to make last update to the SkyDrop with the new future?

"Cycling the screens".

It will be just enought to have option to cycle the screens for example each 3 sec. new screen. I am using this feature on the Garmin Fenix 3 watches and a lot of persons foudn it to be very usefull.

Thank you in advanced for the thinking about.

**Comment by bubeck** [comment]
This should be quite easy. I think about a setting called Auto rotate Screen taking a number of seconds which is meant as the duration of the screen after that Al the next screen is shown.

This could not take much space in progmem. Fero, should I take over?

**Comment by fhorinek** [comment]
I think that I can make this together with option to automatic screen change (eg. screen for circling, take off, gliding). It should not take me much longer that day or two.

@bubeck please keep working on the last big thing :)

**Comment by bluearcus** [comment]
Change to specific screen number in particular condition would be great.

When 'on ground'
When 'climbing'
When 'gliding'
