### ISSUE TITLE
feature request: customization of vario sound

### ISSUE THREAD

**Issue by atomphil** [fhorinek/SkyDrop#33]
Settings for vario/sink tone frequencys.

**Comment by pturri** [comment]
I totally agree with atomphil. 

To be honest i found standard vario sound quite good, but actually one of the MAIN reasons why I bought SkyDrop, was that I was sure it would have had the same (fantastic) customizable audio of SkyBean.. :(
Are you planning to implement this system to Drop too? 

One more thing: 
the killer improvement (for Drop and Bean both) would be to add also also a pre-thermal sound, like Flymasters. This is something incredibly useful in weak conditions.

**Comment by fhorinek** [comment]
I am working on sound profiles right now
also pre-thermal wil be implemented

**Comment by pturri** [comment]
you are my hero!! :+1: :)

Seriously: it is just amazing the way this device is growing! 
Last saturday I did a short test flight and I discovered that most of my take off mates ordered or are willing to order the Drop... once all these enanchemets will be on board, there will be no competitors anymore! :+1:

**Comment by heiner24** [comment]
I would also love the customizable vario sound, since the basic sound in weak lift is somehow not really nice. Any news on this?

**Comment by fhorinek** [comment]
My primary concern is pc configurator and customisable sound

**Comment by fhorinek** [comment]
done
