### ISSUE TITLE
Height in log file differs from GPS height by approx. 50 meters

### ISSUE THREAD

**Issue by pdbgwich** [fhorinek/SkyDrop#331]
The GPS height in the log files is always approximately 50 m lower than the GPS height shown on the display. Can this be corrected anywhere?

**Comment by bubeck** [comment]
Could you please provide the log file?

**Comment by pdbgwich** [comment]
Find attached a track log from a short flight.
[02-1531.zip](https://github.com/fhorinek/SkyDrop/files/2008879/02-1531.zip)

**Comment by bubeck** [comment]
Thanks for the log. I extracted the last GPS step from the log, which is:
B1336385144397N00920874EA0013400101

This has to be read as follows:
B: Type of log entry
133638: time of day, 13:36 and 38 seconds
5144397N: GPS latitude, 51.44379 North
00920874E: GPS longitude, 9.20874 East
A: We have a 3D fix, this means, we have a GPS height
00134: Altitude to the ICAO ISA above the 1013.25 HPa sea level
00101: Altitude of GPS

The 101 is corrected by the geoid, which depends on the position you are. For Stuttgart this is 48m. So the GPS would probably show 149 whereas 101 is logged. This is wanted behaviour. More Info here, what the geoid is: http://www.esri.com/news/arcuser/0703/geoid1of3.html

Is this the difference you are looking for?

**Comment by pdbgwich** [comment]
Yes, that seems to be the case. Problem is, that all the software that interprets this log (at least all software that I use) assumes the height is already compensated. So, would it be possible to implement a switch to change this behaviour in the log output?

**Comment by bubeck** [comment]
This change was made by fero in https://github.com/fhorinek/SkyDrop/issues/294
He references a "new" igc specification, which requests this behaviour. So I am of no further help here. Questions are:
* What "new" igc specification is meant? What is correct?
* What other software are you using, which assume the other behaviour?
* where to fix? Skydrop or "other" software?

@fhorinek what do you think?

**Comment by fhorinek** [comment]
Several people are asking the same questions about altitude in IGC log.
New IGC specification require to use geoid compensation for GPS height and ISA QNH (1013.25 hPa) for barometric altitude.
It is a requirement from FAI CVIL, I know that there are lot of devices ignoring this, but we decide to meet their reqirement.

Therefore we will not allow to change this behavior with valid G-record.

@bubeck thank you for support :)

**Comment by pdbgwich** [comment]
Can You please point me to the new IGC specifications. I only found http://www.ukiws.demon.co.uk/GFAC/documents/tech_spec_gnss.pdf, dated 10 April 2016. In this document in chapter 3.2 and appendix A the record of GNSS altitude above the WGS84 ellipsoid is still requested.
