### ISSUE TITLE
USB ejecting issue on Mac OS X

### ISSUE THREAD

**Issue by nfedera** [fhorinek/SkyDrop#332]
SkyBeab build 3909 rev 1506:

After ejecting the SkyBean in Finder the device reappears automatically after a few seconds:

```
27/05/18 11:07:24,705 mdworker[12526]: (ImportBailout.Error:1331) Asked to exit for Diskarb
27/05/18 11:07:39,000 kernel[0]: USB device 1209D7061D100000 - BOT reset completed with kIOReturnTimeout.
27/05/18 11:07:39,000 kernel[0]: USB device 1209D7061D100000 - will be reset!
27/05/18 11:07:39,000 kernel[0]: USBMSC Identifier (non-unique): 735533438323FFFF30FFD000D000 0x1209 0xd706 0x1, 1
27/05/18 11:07:39,000 kernel[0]: USB device 1209D7061D100000 - fConsecutiveResetCount = 1.
```

So there is never really a safe point to unplug the device without damaging the file system.

**Comment by fhorinek** [comment]
well, you only need to eject the device when you are doing some modifications to the file system.
If you eject an the device will reappear you can disconnect it  without any worry.

**Comment by nfedera** [comment]
Well, you know that Mac OS's loves writing meta data, especially directly after the connection.
