### ISSUE TITLE
Make battery indicator and widget more useful while charging.

### ISSUE THREAD

**Issue by bluearcus** [fhorinek/SkyDrop#339]
Battery indicator currently doesn't indicate real battery status during charging. Please update so that animation cycle starts from current level, not from zero, as is the convention for this sort of charging indicator.

Similarly, the widget just says Chrg. If it could show this, alternating with the current charge % every half second that would be a big improvement.

**Comment by fhorinek** [comment]
Unfortunately this is not possible due hardware design.
