### ISSUE TITLE
updates doesn't work

### ISSUE THREAD

**Issue by geri34** [fhorinek/SkyDrop#34]
I installed the update of 29.6......... Skydrop starts and always shows the same: test
The sane happens with the update of 28.6.
When i install update 0322 my skydrop has no sound.
What runs wrong.

**Comment by fhorinek** [comment]
hi, download a new version from here
http://skybean.eu:8080/repo/updates/0530/

then proceed as it is described in http://skybean.eu:8080/repo/updates/0530/Warning.txt
by default sound is suppressed before start (you have to change altitude by +-/4m)
