### ISSUE TITLE
Improve reported battery charge % by applying a discharge voltage curve adjustment

### ISSUE THREAD

**Issue by bluearcus** [fhorinek/SkyDrop#340]
Can we have a charge % which is calcuated based on a looked up discharge curve?

When I fly a long flight the Skydrop goes to 40% after the first hour or so and stays at 40%, perhaps dropping to 30% during the next 4.

From the code it appears that the battery voltage is linear converted straight to a charge percentage, not attempting to compensate for the very non-linear discharge curve. 

Just a lookup to a generic curve generated by a test discharge would give much better charge state information.

**Comment by bubeck** [comment]
Good idea. I started working on it. The idea would be to ask the user for a "calibration", which would start with a full battery and then discharge until empty and store the different voltages, their associated (linear) percentage and the remaining run time. The data would be stored in a SD file and used to give better battery values during normal usage.

From time to time (as battery gets worse) user should re-calibrate.

**Comment by bluearcus** [comment]
Sounds good. Discharge curve is a little bit dependent upon rate, so the calibration routine should try to configure the instrument during the calibrate rune so that the battery is draining at a realistic rate. GPS + bluetooth on, and regular SD card activity. I think users could live without the vario beeping for 8 hours though...

Supplying a default curve (and allowing reset back to it) for those that don't want to run a calibrate, or have run an incomplete or interrupted one, would be good too.

**Comment by bubeck** [comment]
![screenshot_20180702_075417](https://user-images.githubusercontent.com/828969/42147246-289ddaca-7dcd-11e8-88e5-201aea0af996.png)

Here you see the discharge curve of my drop. I see the following:
1. The curve is not linear at all. :)
2. My battery is able to go below 3200 for around 2 hours, which is a constant in the code for the lowest possible value.

**Comment by bluearcus** [comment]
The current code uses integer and rounds down always as well when producing the battery indicator state value, which makes it seem like the skydrop discharges even quicker to begin with if you are just using the status bar icon. Rounding nearest would help also.

**Comment by bluearcus** [comment]
Any chance for incorporation in a new release?
