### ISSUE TITLE
 Serious error in GNSS altitude 

### ISSUE THREAD

**Issue by johnstevenson** [fhorinek/SkyDrop#346]
https://github.com/fhorinek/SkyDrop/blob/3c937b78963ef069296e571c9200bd1860f2ca58/skydrop/src/fc/logger/igc.cpp#L194

You have misunderstood the NMEA GGA sentence (which actually reports height above the geoid), so what this code does is:
```
   galt = (height-above-geoid) - (height-of-geoid-above-ellipsoid)
```

In areas where the geoid is above the ellipsoid, the reported altitude will be lower than it should be:

```
                            Height reported 950m

Point X --------            Height above geoid      1000m
                            Height above ellipsoid  1050m                    
    1000
           
Geoid ----------            Height of geoid         50m
                            above ellipsoid
    50
        
Ellipsoid ------            Zero reference          0m
```
In areas where the geoid is below the ellipsoid, the reported altitude will be higher than it should be:

```
                            Height reported 1110m

Point X --------            Height above geoid      1050m
                            Height above ellipsoid  1000m                           
    1000
                  
Ellipsoid ------            Zero reference          0m

    50

Geoid ----------            Height of geoid         -50m
                            above ellipsoid
```

**Comment by fhorinek** [comment]
Hi John,

well this is embarrassing. 
But according to the documentation for L80 the altitude in gsa is according to wgs84 ellipsoid not geoid.
so galt = ellipsoid - height of geoid above elipsoid.
since it is above i should add it instead of subtract. 

thank you I will fix this with the new release soon enougth

**Comment by johnstevenson** [comment]
Hmm, are you sure about that? From files I've seen it looks like it is reporting geoid height.

**Comment by johnstevenson** [comment]
The L80 protocol document states: "L80 supports NMEA 0183 standard commands." so it is very strange that it then describes the GGA Altitude field as "Altitude in meters according to WGS84 ellipsoid", when every other manufacturers documents I've seen, and the various NMEA 0183 resources, describe it as altitude above the geoid.

Have you tested what the module actually outputs?

I've got 4 IGC files of the same flight in Spain, where the Skydrop data is generally around 60m below the others. One of these files was from a device running Xc Soar that was receiving its data from the Skydrop  - and interpreting the NMEA altitude as generally understood, ie. above the geoid.

**Comment by fhorinek** [comment]
The datasheet to L80 is wrong. I made several tests with other gps devices and it does output MSL height.
This bug is fixed in 4016

**Comment by bubeck** [comment]
Did you find this bug inside any errata of the company?

Is there a way to update the firmware on the L80?

Should we 'fix' the according nmea sentences in the gps parser, so that forwarding gps is also correct?

**Comment by johnstevenson** [comment]
@bubeck As I understand it the altitude was only "corrected" when writing IGC output, and reported correctly in the forwarded gps/nmea data. As I mentioned above, XC Soar reports a different (the correct msl) atlitude when being fed with Skydrop GNSS data.

**Comment by fhorinek** [comment]
@bubeck I have already fix the problem by not correcting altitude. 
The only problem is that I wrongly implemented the gps driver, because of error in documentation.
@johnstevenson and yes It was only corrected in igc files
