### ISSUE TITLE
usb connection

### ISSUE THREAD

**Issue by geri34** [fhorinek/SkyDrop#35]
Connection doesn't works on win7

**Comment by fhorinek** [comment]
You have to be more specific. We have never encouraged problem on windows.

**Comment by tobyhoremans** [comment]
Same here : Device is not recognised by Win7 computer when in USB mode , shows as unknown usb device in device manager.

**Comment by fhorinek** [comment]
can you specify windows version (32 or 64-bit) did you try another (preferably shorter) cable?

**Comment by tobyhoremans** [comment]
Hi

Indeed ! Tried another cable ( long one) & it works now. Windows is 64bit

Thx.
Toby

**Comment by fhorinek** [comment]
Lot of USB problems are cable-related :)

**Comment by geri34** [comment]
The problem is my notebook( win7. 64 bit). With an other pc skydrop connects to usb.

**Comment by mattbio** [comment]
I also have the same problem with win7 64 bits. I tried witch several cables and PC (another win7).
The skydrop screen shows "USB MODE/ idle", is charging, I enable the setting "mass storage" but i can t see it anyway...
