### ISSUE TITLE
High vario (accelerator) values

### ISSUE THREAD

**Issue by idlefella** [fhorinek/SkyDrop#351]
Hi Skybean Team

I recently started using your SkyDrop device. When I was playing around and analyzed the bluetooth protocol, I realized that the device sends very high and noisy vario data in the bluetooth protocol (here protocol LK8EX1 without touching the device - it lies on a flat surfce).

~~~
$LK8EX1,96166,99999,5,23,1049,*2C
$LK8EX1,96166,99999,6,23,1049,*2F
$LK8EX1,96166,99999,3,23,1049,*2A
$LK8EX1,96166,99999,1,23,1049,*28
$LK8EX1,96166,99999,-0,23,1049,*04
$LK8EX1,96166,99999,2,23,1049,*2B
$LK8EX1,96166,99999,1,23,1049,*28
$LK8EX1,96166,99999,-0,23,1049,*04
$LK8EX1,96166,99999,-1,23,1049,*05
$LK8EX1,96166,99999,-0,23,1049,*04
$LK8EX1,96167,99999,-4,23,1049,*01
$LK8EX1,96166,99999,-2,23,1049,*06
$LK8EX1,96167,99999,-4,23,1049,*01
$LK8EX1,96167,99999,-6,23,1049,*03
$LK8EX1,96167,99999,-4,23,1049,*01
$LK8EX1,96167,99999,-3,23,1049,*06
~~~

By the definition here https://github.com/LK8000/LK8000/blob/master/Docs/LK8EX1.txt and also according to the code here https://github.com/fhorinek/SkyDrop/blob/40f56d741afa369ad431d3a3f42930b6c186064b/skydrop/src/fc/protocols/LK8EX1.cpp#L26
the vario rate is in `cm/s`. But as you can see in the plot here
![output2](https://user-images.githubusercontent.com/1322083/46493207-fbd67280-c80f-11e8-8721-e9a23d33fe5d.jpg)
the value is very noisy. I don't touch the device while recording these values, but it reports climb rates of up to `10cm/s`, which seems to be a lot.

When I slowly move the device up and down, the climb rate becomes very smooth.

![output4](https://user-images.githubusercontent.com/1322083/46494236-b0719380-c812-11e8-8442-f22be190476e.jpg)
Note: The violet line is vario climb/sink rate with yaxis1. The green line is pressure with yaxis2.

I was wondering if there's something wrong? Especially because the curve becomes smooth when moving the device. I also dug a little bit deepter in the code and saw that the climb ratio reported over bluetooth comes directly out of the kalman filter. Unfortunately I didn't have time to implement logging of the raw data from the accelerometer sensor to see if that reports that noise or if it is introduced later.

Thanks and greetings
idlefella

Edit: Forgot to the following details:
Firmware Build: 4016
HW Rev: 1506

**Comment by idlefella** [comment]
Any updates on this one? Because for me the vario is actually totally unusable.

**Comment by fhorinek** [comment]
@idlefella this behavior is normal, +/-10 cm is the device precision.
I am now working on few tweaks around filter, but do not expect miracles from pressure sensor

**Comment by fhorinek** [comment]
Please test on new release, the IMU and filtering method are completely replaced

**Comment by idlefella** [comment]
Hi @fhorinek 
Thank you very much for the update. I will test it today evening when I'm back home :)

Best,
idle_fella

**Comment by idlefella** [comment]
HI @fhorinek 

I updated my device with the latest release and first tests showed a **huge** improvement compared to the previous version. Also the vario doesn't show anymore climbing and sinking while keeping it calm on a table. Unfortunately I'm going to holidays the next weekend that's why I can't test it while flying.

But maybe somebody else can report his experience with the new firmware version.

Thank you very much for the update.

Best
idlefella
