### ISSUE TITLE
IGC file shows wrong alititude

### ISSUE THREAD

**Issue by comtsamsmith** [fhorinek/SkyDrop#353]
Hi,
I fly a paramotor, on flat land near sea level.  So before flight I set the Alt1 to 0 Altitude.  It may actually y be 20 ft or something like that.

But when I download the IGC file from it it shows take off Alt as -270+ feet.

Any ideas on why? or how to make zero?

**Comment by fhorinek** [comment]
According to specification the altitude in IGC file is calculated based on ICAO Standard Atmosphere	1013.25hPa
