### ISSUE TITLE
New Feature "airspace"... Dont fly near airports!

### ISSUE THREAD

**Issue by bubeck** [fhorinek/SkyDrop#354]
I would like to propose the following feature, which I am willing to implement
an offer as a pull request. Before I do, I would like to ask @fhorinek (and others) for 
your opinion, because otherwise it would be a waste of time... :)

The feature is called "airspace": Show the pilot, if he is inside of
a "forbidden" airspace, which is typically near an airport. Additionally
show him the shortest way to allowed airspace to get out. If he is outside
the forbidden airspace, show him, in which direction the airspace starts
and how far away he is to help him to avoid the forbidden area.

This is especially helpful for pilots flying near airports (like me). 

There could be two widgets:
  1. An arrow pointing away from the forbidden area. Pilots should follow this
   direction.
  1. A distance (in ft and km) to the border of the forbidden area.

# Implementation

The implementation should be fast and compact. To do so, I would propose to 
pre-compute a map for a given area (e.g. germany) outside the skydrop and
store it on the SD card. This map contains a grid with 100m distance
between the points. It is similar to the HAGL files. Each point stores
the distance and direction to the nearest forbidden area. SkyDrop then
reads the file at the currect GPS position to show the information stored
there. This is fast and compact in PROGMEM.

Here is an example of an area and the points in the grid. For each point
you see an arrow pointing to the forbidden area, which will be stored
efficiently inside the file using 2 bytes per point. This file will then
be stored on the SD and used by the code.

![airspace example](http://bubecks.de/public/sky/airspace.png)

In a second step, we could provide more files corresponding to different
"heights", so that we also provide a height distance as well and go for 3D.

# PROGMEM size

The current version 4016 uses 191127 bytes, leaving ~5K free in PROGMEM.
By switching over to GCC 7.2.0 it has 187337 bytes, leaving ~9k free.
I estimate, that the above feature, would not need more than 4k. This 
means, it will come "for free" when switching to a newer compiler.

What is your opinion about that feature? Are you willing to integrate this?
Do you have any additional ideas or remarks?

Thanks!

**Comment by fhorinek** [comment]
Hi Til,

this looks great and its looks like a viable solution for airspace warning in skydrop. 

But unfortunatly I need to solve out of memory issues with the current firmware. PROGMEM is not the only memory running low. There are problems with the RAM, where stack and heap overlap, causing unexpected problems. 

I need to solve this problem first. I know that implementing new features is exciting but stable firmware is my first priority. 

I am curently experimenting with gcc 8.2 for progmem. But the ram issues need to be fixed manualy. 
We are pushing this mcu to the limit for a long time. I will need to cut few buffers and maybe dump whole debug system first. Then we can discuss new features.

I really like the idea but maybe it is bit too much for our tiny mega.

**Comment by bubeck** [comment]
I agree, that stability is priority 1 and wait for you to solve RAM issues first. If we know, where we are, we can discuss this feature again. Please give me a hint if you reached that point.

**Comment by bubeck** [comment]
Feature implemented and currently in testing on my device. I will keep you updated. :)

**Comment by bluearcus** [comment]
How will this feature cope with heights? We frequently fly under airspace as well as around / alongside it? My understanding is that if I am under some airspace, then I won't have any information because the nearest restricted would be 'here, up'.

**Comment by bubeck** [comment]
This is taking into account. You will get to information:
1. the horizontal distance and I go to the next airspace
2. The height at the current position where the next airspace above you begins.

In your example only 2 would be important. for example if the current position the next airspace above you begins at 2500 feet it will display '<2500 ft'. If you would go up to 2600 ft this display will start flashing.

**Comment by bluearcus** [comment]
Two widgets please. Vertical nearest, and horizontal nearest!

**Comment by bubeck** [comment]
There are 3 widgets:
1. Horizontal distance (with flashing if inside)
2. Horizontal angle
3. Vertical height

**Comment by ukeconsulting** [comment]
will there be an easier way to make tile.AIR files ? 
because i installed python 3.7 (python 2.7 was not enough), and after matplotlib, shapely (manually), GDAL and i still have python errors when running the script.

this feature is great but i still can't use it since i am not flying in germany nor in slovakia and i couldn't convert files into .AIR
(for next months i need france, slovenia, italia, switzerland, austria and hungary).

**Comment by ukeconsulting** [comment]
Thanks for the .zip for each european country :-) 
it is far easier than using the script.

**Comment by ukeconsulting** [comment]
this weekend i was  flying in an usual paragliding take off within a restricted airspace for engine powered aircraft but not for paragliding 

so the vario was showing me an alarm:  LHB25 Vertes 
https://terkep.legter.hu/as/zYG4K#11.19/47.4031/18.3743

i was in Börgönd TIZ2 600m-2300m airspace too
but the only restricted airspace i had to avoid as a paraglider: TMA1, 2300m 

it could be good to have an option to desactivate the complete airspace function because it seems that the blinking sucked half of my battery for nothing, or it is constant calculation to go out of the airspace... 

perhaps we could 
- chose an option like PG or PPG that automatically activate alarm or not depend on the autorisations 
- or just chose different options for each airspace type: activated with alarm / activated / desactivated

for my example : 
PG allowed = no alarm if PG type choosen or TIZ & LHB activated without alarm and TMA activated with alarm
PPG not allowed = alarm if PPG type choosen or TIZ & LHB &TMA activated with alarm

is it possible to have a inversion of the display (white written on black background) to show the problem instead of a blinking? because constante blinking is stressing, especially when you are not in a restricted zone, just the vario is telling wrong.

**Comment by ukeconsulting** [comment]
I have to desactivate the feature, that always tell me that i am in forbidden airspaces despite not:
Nowadays on french official take off, it was already in alarm. That was the good airspaces but not restricted one for PG. so no alarm needed and i didn't have to go out.

**Comment by bubeck** [comment]
Could you please send the gps coordinates of the (wrong) position?

**Comment by ukeconsulting** [comment]
of course, i m here to help :-)
the 3 places i tested: 

HU - CSÁKBERÉNY, KOPASZ-DOMB
GPS: 47.34942, 18.29998
Airspace to avoid: TMA1, 2300m
https://goo.gl/maps/KgP5vZtDH74UcM6R9

HU - towing place in szekesfehervar 
https://goo.gl/maps/gx1VjYmhLwVjcoy16

FR - PLAINE JOUX
https://federation.ffvl.fr/sites_pratique/voir/124
https://goo.gl/maps/2PDHaaqvQ3XWabJh6

if you need the igc files i can send it to you.
if you need i make specific tests, just tell me.
when i am home in france, i am flying nearly everyday.

**Comment by bubeck** [comment]
```
Point (lat, lon) 47.34901989808152 18.29627202875341
Point (lat, lon) 473490198 182962720
 filename is 'data/N47E018.AIR'
x, y 59 69
origin lat 473474999.99999994
origin lon 182975000.0
  0 173deg    3.537km IN mode 1
   i = 27      0 AGL -   1500 AGL [RESTRICTED] LHB25 Vertes
origin lat 473474999.99999994
origin lon 182975000.0
  1 216deg    2.781km    mode 1
   i = 20      0 AGL -  14500 MSL [    DANGER] LHD36B
origin lat 473474999.99999994
origin lon 182975000.0
  2   0deg    1.624km IN mode 1
   i = 16   2000 MSL -   7500 MSL [         F] Borgond TIZ2 135,7
origin lat 473474999.99999994
origin lon 182975000.0
  3 270deg    3.442km IN mode 0
   i = 21   7500 MSL -  19500 MSL [         C] Budapest TMA1 APP 129,7
origin lat 473474999.99999994
origin lon 182975000.0
  4 358deg   42.439km IN mode 0
   i =  4   9500 MSL -  32767 MSL [         C] BUDAPEST CTA Info West 125,5

```

**Comment by fhorinek** [comment]
I am working on alert / supress system for the airspaces right now

**Comment by bubeck** [comment]
This is a duplicate

https://github.com/fhorinek/SkyDrop/issues/399

**Comment by ukeconsulting** [comment]
For the airspaces suppressor : as it is type of airspaces : it would be interesting to have a list of airspaces pattern name to silence alerts or checkboxes with the type of airspaces to alert.
