### ISSUE TITLE
Unable to BT Pair using SkyDrop BLE (fine with SPP)

### ISSUE THREAD

**Issue by athertop** [fhorinek/SkyDrop#356]
Hi, Just bought SkyDrop (so current firmware: 4016), but I cannot get a Bluetooth pair (using "SkyDrop BLE" profile) to either my Google Nexus P6 phone (circa 2016, running current android 8.1.0 release) or my Nexus 7 tablet (circa 2013, running older Android 6.0.1 release). It tries to pair then just stops trying on both devices. I see on the skydrop "Bluetooth connected" when I start the pairing process, then when the pairing process quits, I see, "Bluetooth Disconnected" on the SkyDrop. Both devices pair just fine with the "Skydrop SPP" profile. This surely can't be two completely separate Android systems with the same fault?

**Comment by fhorinek** [comment]
Hi. for BLE just select the device in the application. No pairing needed.
