### ISSUE TITLE
[Improvement] Show distance when the flight ends.

### ISSUE THREAD

**Issue by EduZamora** [fhorinek/SkyDrop#357]
Hi, I am very happy with the Skydrop but I am missing one thing I think would be easy to implement. When you land and stops the vario recording or when you see your last traks on the track log, you can see information like maximun height or maximun ascent ratio but you can't see the distance traveled from point to point (free distance). To see that I have to use the computer. I think it would be very useful to see this data directly on the vario when you have done a cross and want to know how many km you've traveled. Many thanks and very good work!

**Comment by bubeck** [comment]
This can be easily implemented on top of odometer. Store a start value and subtract End value on landing.

Probably needs around 300 bytes in Progmem and  4 bytes ram.

I am willing to implement.

@fhorinek willing to merge?
