### ISSUE TITLE
feature request: save configuration to SD card

### ISSUE THREAD

**Issue by tomasz13** [fhorinek/SkyDrop#36]
there is so much FW upgrades, and that is cool because we have more and more settings, but would be nice save them to the cfg file and store it on the SD, and after FW upgrade everything would be like before... layouts & widgets, disp settings, audio settings, vario & alti setting, etc...

**Comment by fhorinek** [comment]
That is the problem, because every time I add more settings the configuration file will change. Currently UPDATE.EE contains default configuration. But I will try to do it somehow.

**Comment by aktie** [comment]
That would be fantastic. Too many personalisation to do after each software update.

**Comment by fhorinek** [comment]
Now you can upload CFG.EE (or OLD.EE) to configurator and update it to newest version.
