### ISSUE TITLE
Unable to calibrate skydrop

### ISSUE THREAD

**Issue by EhsanBaninajar** [fhorinek/SkyDrop#362]
The acceleration calibration process is always failing, it calibrate X+, Y+ and Z+ even without changing the edges and then the screen stays on waiting without anything happens even when you put the device on each edges.
Also the magnetometer calibration is failing too, it beep once in the first and no matter how much you rotate it noting happens!

So this didn't work:
https://www.youtube.com/watch?v=Pa07fwXTDnw

My build number is: 4066 and rev: 1506

**Comment by fhorinek** [comment]
Please try 4240
