### ISSUE TITLE
No USB after updating FW to 4084

### ISSUE THREAD

**Issue by kubotron** [fhorinek/SkyDrop#366]
Unable to connect over USB after updating SkyDrop from old firmware (about 2 years old) to 4084. With 4016 USB works fine. 

HW is the 1st generaton I think. The speaker openings are 3 rectangles, like in this image: https://imgur.com/a/FoApQh5

**Comment by fhorinek** [comment]
This is strange since USB subsystem was not modified during this update.

Can you confirm that previous version is working by downgrading?

You can disassemble the drop to upload files to SD card directly

Dňa pi 1. 3. 2019, 12:31 Jakub Ludma <notifications@github.com> napísal(a):

**Comment by tomasz13** [comment]
Where can I find the 4084 firmware? I see only 4016...

**Comment by kubotron** [comment]
Yeah thats what I did: put the 4016 FW on SD card directly and now USB
works again

**Comment by fhorinek** [comment]
@kubotron does it stays in charging mode?
Did you get any message from operating system?

**Comment by Charlie-McDaddy** [comment]
I had a similar issue after updating the firmware.  The SD was in charging mode but WIN 10 wouldn't recognise the USB device.  After a computer restart all is good.

**Comment by xavgdt** [comment]
The same is happening to me too on Windows 10 and with firmware 4084. When I plug it in Windows says "USB device not recognized". I managed to make it work after formatting the SD card and then it stopped working again. If I connect it it stays in charging mode.

**Comment by fhorinek** [comment]
Fixed in next release
