### ISSUE TITLE
IGC file barometric altimeter value

### ISSUE THREAD

**Issue by nfedera** [fhorinek/SkyDrop#371]
I've always seen unusual high differences between GPS and barometric altitude in my IGC files, right from the start although altitude 1 was exactly calibrated.

I looked up the B record writes in the source and the barometric alt written is calculated like this: 
```
uint16_t alt = fc_press_to_alt(fc.vario.pressure, 101325);` 
...
igc_pre_start_cache[igc_pre_start_index].balt = alt;
```
So it seems that IGC will always receive barometric heights with fixed QNH 1013.25 (standard pressure).

Is this an "official" IGC requirement or your design decision?

**Comment by fhorinek** [comment]
This is official requirement from fai civl.

Dňa so 23. 3. 2019, 23:28 Norbert Federa <notifications@github.com>
napísal(a):

**Comment by nfedera** [comment]
Thanks František, for reference I'm quoting from the [IGC GNSS FR Technical Specification](www.ukiws.demon.co.uk/GFAC/documents/tech_spec_gnss.pdf):

Page 11:
> Pressure Altitude - In an IGC FR, this is a five numeric group indicating the pressure altitude in metres with respect to the ICAO International Standard Atmosphere (ISA) used in worldwide aviation, with a sea level datum of 1013.25 HPa. 


Page 29
> Press Alt. | 5 bytes | PPPPP | Altitude to the ICAO ISA above the 1013.25 HPa sea level datum ...
