### ISSUE TITLE
Allow config of Home and Waypoint navigation distance widgets units

### ISSUE THREAD

**Issue by bluearcus** [fhorinek/SkyDrop#373]
Currently seems to be set only to miles. Option to have distances in km please.

**Comment by bubeck** [comment]
You can change this by going to Settings>Altimeters>Altimeter1>Units and switch to "metric".

**Comment by bluearcus** [comment]
Hmm. Logical! A dedicated config setting for distance units would be nicer.

**Comment by bubeck** [comment]
Thats right. I will propose this change. :)

**Comment by fhorinek** [comment]
@bubeck you can use free bits in gps_format_flags the first 4 are free

**Comment by bubeck** [comment]
Ok, thanks

**Comment by bubeck** [comment]
Integration into main source code done. Feature will be part of the next firmware release.
