### ISSUE TITLE
Build 4240 Compass Problem

### ISSUE THREAD

**Issue by cmoorice** [fhorinek/SkyDrop#375]
After updated to 4240, the compass indication is totally wrong. I have re-calibriated the unit twice, but the problem still exists. Many thanks.

**Comment by fhorinek** [comment]
Hi can you specify your SkyDrop revision?

**Comment by cmoorice** [comment]
Sorry, I don't understand the meaning of "revision". I just update it from 
4016 to 4240. The compass can indicate the direction correctly at 4016. 
However, after the update, it indicates totally wrong directions.

Thanks.

**Comment by fhorinek** [comment]
revision is to second number showing during stat-up screen. Did you
calibrate all sensors or just the magnetometer?
--
František Horínek


ut 9. 4. 2019 o 12:27 cmoorice <notifications@github.com> napísal(a):

**Comment by cmoorice** [comment]
Oh! I got it. It  is 1506. I re-calibrated ALL sensors.
Thanks.

**Comment by fhorinek** [comment]
Can you make a video? Is a value wrong (like there is an offset) or does it move randomly?

**Comment by cmoorice** [comment]
It doesn't move randomly, it just show a wrong direction.



As shown in the pictures, the green one is the updated unit and the blue 
one is not yet updated but the direction is correct.


Thanks


On Tue, 9 Apr 2019 at 18:57, František Horínek <notifications@github.com> 
wrote:


Can you make a video? Is a value wrong (like there is an offset) or does it 
move randomly?

**Comment by fhorinek** [comment]
Are you using Compas in mode magetic north or did you specify declination. Also there are no attachment. I think that you can only add attachment trough GitHub form

**Comment by cmoorice** [comment]
![IMG_20190409_190528](https://user-images.githubusercontent.com/31579487/55797234-7b663680-5afe-11e9-8589-2154b6791185.jpg)
![IMG_20190409_190507](https://user-images.githubusercontent.com/31579487/55797249-8620cb80-5afe-11e9-831f-9772291f440a.jpg)


Just magnetic north.

**Comment by cmoorice** [comment]
Ok, let me check and reply to you.

**Comment by cmoorice** [comment]
You are right, the compass arrow show the correction direction. However, I found that the compass heading just swap E to W and W to E.

**Comment by fhorinek** [comment]
Fixed pleas upgrade your firmware
