### ISSUE TITLE
Add VARIO_USE_ACC to Configurator

### ISSUE THREAD

**Issue by IB0S** [fhorinek/SkyDrop#376]
Hi!

Use accel is only available through the device configuration menu. Updating SW on the device always disables use accel setting.
Please add it to the configurator so I can save and reload it alongside the other settings.

Thanks!

**Comment by fhorinek** [comment]
thank you fixed

**Comment by kolaCZek** [comment]
I think, it's not fixed. After editing and updating settings from web configurator (vps.skybean.eu/configurator) Use accel is unchecked.
