### ISSUE TITLE
Altitude alarm (safety improvement)

### ISSUE THREAD

**Issue by tomasz13** [fhorinek/SkyDrop#377]
if I reach the altitude limit, the skydrop alarming continuously and I must touch the button on it. Some time (quite often) I cant release control, because I'm in a turbulent air,  strong or very weak thermal, and I must centering and I need both my hands.

Please add a possibility to set the duration of alarming sound in seconds (for me is enough 3s-5s alarming sound)

**Comment by bubeck** [comment]
Another idea could be:

 1. Show alarm for 5s (and allow pressing middle button to dismiss alarm message immediately)
 2. As long as alarm remains active, show alarm regularly all 30s for 1s.
 3. Optionally add a small alarm icon in the right side of the display (like Logging, Bluetooth, ...) as long as an alarm is active, e.g. a :warning:

@fhorinek What do you prefer/think?

**Comment by bubeck** [comment]
By looking at the code iI think, that there is an TIMEOUT already:

#define GUI_ALARM_TIMEOUT	5000

However, maybe it is not working and this is a bug? I will further investigate.

**Comment by tomasz13** [comment]
when will be implemented this feature? thanx ;)

**Comment by bubeck** [comment]
It is already implemented. However, @fhorinek must accept this feature and integrate it into his code base.

**Comment by tomasz13** [comment]
thank you, Im waiting for it very much ;)

**Comment by tomasz13** [comment]
@fhorinek please accept this feature and integrate it into the next release.... plsplspls.

**Comment by bubeck** [comment]
Has been merged, 7 minutes ago. Will be part of next release. :)
