### ISSUE TITLE
analog/digital/average vario

### ISSUE THREAD

**Issue by pturri** [fhorinek/SkyDrop#38]
Sorry for the silly question, but being user manual not available there are still some question marks :) 

Could you please clarifiy the difference between varios?

We have 2 widgets: "Vario" and "Avg"
To my understanding, Vario should show analog "real time" vario (unfiltered), while Avg should show averaged analog Vario, according to "Average vario integration interval" (standard 10secs).

Is this correct?

But what about digital vario and its integration interval setting? 

Thanks in advance!

**Comment by fhorinek** [comment]
Vario bar and audio are always real time
Vario widget value can be averaged using vario integration interval (default 0s).
Average vario it the same, but it uses average integration interval (default 10s).

**Comment by pturri** [comment]
Thanks as usual for you real time support! :+1: 

In other words, "vario" widgets shows what you call "digital vario" value, right? 

By default, this value is shows real time values NOT averaged anyhow, while by changing "digital vario intergration" >0s, it is possibile to average it. Right?

**Comment by fhorinek** [comment]
Yes
By default it "average readings in zero second interval" (digital vario intergration = 0)

**Comment by pturri** [comment]
ok thanks again, all clear now :+1:
