### ISSUE TITLE
AirSpace convert.py not working for french airspace

### ISSUE THREAD

**Issue by eltorio** [fhorinek/SkyDrop#383]
Hi,
File http://soaringweb.org/Airspace/FR/190523__AIRSPACE_FRANCE_2019-05.txt
send error with convert.py

`python3 convert.py source/190523__AIRSPACE_FRANCE_2019-05.txt
Loading source/190523__AIRSPACE_FRANCE_2019-05.txt
Traceback (most recent call last):
  File "convert.py", line 598, in <module>
    sys.exit(main(sys.argv[1:]))
  File "convert.py", line 512, in main
    load_airspace(DataSource)
  File "convert.py", line 388, in load_airspace
    for oas in openaip.load_file(filename):
  File "/mnt/d/DATA/Download/SkyDrop-master/skydrop/utils/airspace/openaip.py", line 86, in load_file
    data = regex.sub("&amp;", f.read())
  File "/usr/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 2745: invalid continuation byte`

I tried to convert it:
`chardetect3 source/190523__AIRSPACE_FRANCE_2019-05.txt
source/190523__AIRSPACE_FRANCE_2019-05.txt: ISO-8859-2 with confidence 0.24529772295366375
uconv -c -f ISO-8859-2 -t UTF-8 source/190523__AIRSPACE_FRANCE_2019-05.txt > source/AP.txt`
but it still doesn't work
`python3 convert.py source/AP.txt
Loading source/AP.txt
Traceback (most recent call last):
  File "convert.py", line 598, in <module>
    sys.exit(main(sys.argv[1:]))
  File "convert.py", line 512, in main
    load_airspace(DataSource)
  File "convert.py", line 388, in load_airspace
    for oas in openaip.load_file(filename):
  File "/mnt/d/DATA/Download/SkyDrop-master/skydrop/utils/airspace/openaip.py", line 90, in load_file
    root = ET.fromstring(data)
  File "/usr/lib/python3.4/xml/etree/ElementTree.py", line 1325, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0`

Finally I tried to convert it to "unix" without success
[AP.txt](https://github.com/fhorinek/SkyDrop/files/3268592/AP.txt)
[190523__AIRSPACE_FRANCE_2019-05.txt](https://github.com/fhorinek/SkyDrop/files/3268593/190523__AIRSPACE_FRANCE_2019-05.txt)

**Comment by fhorinek** [comment]
hi, you need to use openAIP format

**Comment by eltorio** [comment]
Thank you fhorinek,
but 19023_... is reported as an OpenAIP format
http://soaringweb.org/Airspace/FR

**Comment by eltorio** [comment]
Even with the .aip provided in source directory
`./convert.py -l source/openaip_airspace_france_fr.aip 
Loading source/openaip_airspace_france_fr.aip
UNKNOWN [PROHIBITED] FR (None - None) INVAILID Parsing error No altitude reference!
UNKNOWN [GLIDING] FR (None - None) INVAILID Parsing error No altitude reference!
UNKNOWN [RESTRICTED] FR (None - None) INVAILID Parsing error No altitude reference!
UNKNOWN [E] FR (None - None) INVAILID Parsing error No altitude reference!
UNKNOWN [A] FR (None - None) INVAILID Parsing error No altitude reference!
UNKNOWN [C] FR (None - None) INVAILID Parsing error No altitude reference!
UNKNOWN [D] FR (None - None) INVAILID Parsing error No altitude reference!
UNKNOWN [RESTRICTED] FR (None - None) INVAILID Parsing error No altitude reference!
UNKNOWN [DANGER] FR (None - None) INVAILID Parsing error No altitude reference!
Shell is not a LinearRing
Traceback (most recent call last):
  File "./convert.py", line 598, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./convert.py", line 512, in main
    load_airspace(DataSource)
  File "./convert.py", line 408, in load_airspace
    airspaces.append(Airspace(oas))
  File "/Users/rlemeill/Development/SkyDrop/skydrop/utils/airspace/Airspace.py", line 41, in __init__
    self.setPolygon(shapely.geometry.Polygon(a.coordinates))
  File "/Users/rlemeill/Development/SkyDrop/skydrop/utils/airspace/Airspace.py", line 67, in setPolygon
    self.near_box = shapely.geometry.box(self.bb[0] - ex, self.bb[1] - ex, self.bb[2] + ex, self.bb[3] + ex)
IndexError: tuple index out of range
`

**Comment by fhorinek** [comment]
The http://soaringweb.org/Airspace/FR/190523__AIRSPACE_FRANCE_2019-05.txt is **OpenAIR** format. You need **OpenAIP**
The error is related to shapely polygon construction.
What version of shapely are you using? This is my version
```
horinek@worktop:~$ pip show shapely
Name: Shapely
Version: 1.6.4
Summary: Geometric objects, predicates, and operations
Home-page: https://github.com/Toblerity/Shapely
Author: Sean Gillies
Author-email: sean.gillies@gmail.com
License: BSD
Location: /usr/lib/python2.7/dist-packages
Requires: 
```
From the path, it looks like that you are running mac os. 
A quick search tells me that it might cause this problem.
https://github.com/geopandas/geopandas/issues/556

Nevertheless, if everything else fails France is already done  https://vps.skybean.eu/air/

**Comment by eltorio** [comment]
Sorry for the AiR AiP confusion
`ÇaKlakBling:airspace rlemeill$ pip3 show shapely
Name: Shapely
Version: 1.6.4.post2
Summary: Geometric objects, predicates, and operations
Home-page: https://github.com/Toblerity/Shapely
Author: Sean Gillies
Author-email: sean.gillies@gmail.com
License: BSD
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: 
Required-by: `

**Comment by eltorio** [comment]
Hi František,
Finally I succeed with your help. I uninstall all my python stuff, reinstall python3.7 lxml, shapely numpy matplotlib …
Next I change the shebang in all .py for refleting my specificv python3.7 install…
And it works.
Thank you
