### ISSUE TITLE
Airspace - Inside FIR Praha

### ISSUE THREAD

**Issue by kolaCZek** [fhorinek/SkyDrop#384]
Vario alerts me that I am inside airspace FIR Praha. But this airpsace is covering whole Czech Republic. This image is from Vranany (50.315880, 14.354260) ~1m HAGL.

![IMG_20190608_085635](https://user-images.githubusercontent.com/13732574/59205665-a4a94e80-8ba3-11e9-8f75-18c3e7f56876.jpg)

**Comment by fhorinek** [comment]
Well, technically it is not a bug.
But it is a quite unusable feature.
I am afraid that you will have to wait until we implement airspace class filter.

**Comment by kolaCZek** [comment]
What about converting airspaces without FIR?
Set this https://github.com/fhorinek/SkyDrop/blob/master/skydrop/utils/airspace/const.py#L63 to False..?

**Comment by fhorinek** [comment]
Well that would work for Czech republic, but for example in Slovakia or Hungary fir is useful, since it starts at maximum allowed altitude for free flying, therefore they have valuable information.

**Comment by kolaCZek** [comment]
Ouch... :-( I will convert Czech Rep. without FIR for myself and wait for airspace class filter... Thx! ;)
