### ISSUE TITLE
Gps precision during high speeds

### ISSUE THREAD

**Issue by alexisb38** [fhorinek/SkyDrop#387]
My skydrop never let me down during a paragliding flight, always very precise and stable gps tracks, not a second missed. I wanted to try it while wingsuiting out of a plane. I put it in my "chest pocket", in close proximity to my phone (in airplane mode).
I had a hard time getting a signal during ascent, thought it was because of all the metal in the plane around me. But during the jumps (3 tests in total) the tracks are very inconsistent. it lost the signal frequently.
Could this be due to the phone being in very close proximity, or is it normal that at such high speeds my skydrop loses the g
ps ? Any workarounds possible, settings I missed ?
 here is the log : [04-1515.txt](https://github.com/fhorinek/SkyDrop/files/3296173/04-1515.txt)

**Comment by fhorinek** [comment]
This might be caused by a bad GPS reception.
The GPS antenna needs to see the satellites (display needs to be directed to the sky).
If you have the device in the front pocket you act as a shield to the radiowaves,
