### ISSUE TITLE
Change default autostart feature config

### ISSUE THREAD

**Issue by bluearcus** [fhorinek/SkyDrop#39]
The current default of  Settings->Logger->Autostart->Suppress Audio set to ON leads to lots of people worrying that their vario won't beep.

Please change the default for this setting to be 'OFF'. Then when the vario comes out of the box the first time and is switched on, it passes the customers first test!

**Comment by fhorinek** [comment]
At least they learn a new function, when they are looking for cause. I want to engage our customers in the development process.
