### ISSUE TITLE
Make contrast menu setting a 'live adjustment'

### ISSUE THREAD

**Issue by bluearcus** [fhorinek/SkyDrop#40]
Unlike other config settings, currently it is easy when adjusting the LCD contrast to make your skydrop temporarily unusable.

Because the contrast is only changed when 'confirming' the new value, it is difficult to know if you have selected the best value, or one which will make the screen unreadable. Contrast often needs to be adjusted on LCDs in my experience due to changing environment temperature and pressure.

Please change the adjustment facility for the contrast so that the actual contrast setting is adjusted in real time as the value is changed, without the need to 'confirm' the value. This will allow the adjustments to be made easily and safely.

**Comment by atomphil** [comment]
+1

**Comment by fhorinek** [comment]
it is allready in next milestone. No need to push it :)

**Comment by fhorinek** [comment]
done in next release
