### ISSUE TITLE
Weird pressure unit when setting QNH

### ISSUE THREAD

**Issue by nfedera** [fhorinek/SkyDrop#407]
I'm always a bit irritated when setting the QNH on the device (as in the screenshot below):

![image](https://user-images.githubusercontent.com/670606/62708566-f596c100-b9f3-11e9-9236-61ca59d9b599.png)

The QNH value seems to be displayed in Decapascal [daPa], which is kinda unusual.
Maybe a decimal dot should be drawn so that it is clear that the unit is hPa.

I think that there should even be be enough space to display the value in Pa as shown in the following makeup:

![image](https://user-images.githubusercontent.com/670606/62709461-ace00780-b9f5-11e9-81fd-b6033cfe34a7.png)

**Comment by fhorinek** [comment]
Chnged from dPA to Pa
