### ISSUE TITLE
Public airspace file distribution 

### ISSUE THREAD

**Issue by weidi** [fhorinek/SkyDrop#409]
At the moment i´m creating a Docker container for automated building of the airspace files.
Is this planned already to be publicly available already? 
I also optimized the documentation and plan a pull request soon and i am thinking about how airspace calculation is done if there is an AGL airspace. is this only working when there are HAGL files and will there be a warning if there are none?

Thank you, Johannes

**Comment by fhorinek** [comment]
the data are available here https://vps.skybean.eu/air/
The airspace function is released to public but it is still bit clunky. Without blacklisting and filtering on the device it is sometimes confusing.
I am working on the airspace filter right now.

When there is altitude based on AGL and the AGL data are available then you will see calculated altitude based on AGL data for the floor and ceiling. If not then you will see something like 200AGL.

**Comment by weidi** [comment]
Thank you for the answer, will update the wiki so that it´s clear to everybody.
