### ISSUE TITLE
GPS offset

### ISSUE THREAD

**Issue by RomanKreisel** [fhorinek/SkyDrop#41]
Unfortunately I seem to have a (constant?) offset of about 60-70m in height of my GPS. I found out by comparing to the GPS of my other Vario and my Android Phone (A-GPS).
Even if it's a hardware-problem, it could possibly be fixed by a configureable offset? Due to the lacking possibility to show the GPS coordinates right now, I cannot tell if there are other offsets as well. This offset might become annoying after the implementation of #27

**Comment by fhorinek** [comment]
you can see coordinates in settings->gps->status
can anyone check and post their gps alt error offset?

**Comment by leachim1** [comment]
My A-Phone says 390 Meters, Skydrop 310-320Meter (very drifty).
http://www.mapcoordinates.net/ says 361 Meters for the location... Funny thing is when i enter just my City it tells me 391 Meters. So just a suggestion, fucking android works with Database corrections? Just a idea unfortunately I don't have time to test. Work and fly ...
Maybe I go test it on my weekend trip.

**Comment by aktie** [comment]
XCSoar GPS on the phone says I'm at 61m ASL, googling GPS altitude for the location says 61m, SkyDrop says 1m.

**Comment by RomanKreisel** [comment]
Just checked @ Tegelberg Landing Area:
Paragliding Map: 830m
Flytec 6020: 828m
Android Phone: 820m
SkyDrop: 762

**Comment by fhorinek** [comment]
@RomanKreisel and the real altitude?

**Comment by RomanKreisel** [comment]
The DHV says it's @ 830m
http://www.dhv.de/db2/details.php?qi=glp_details&popup=1&item=1101

**Comment by ptt79** [comment]
I am not experienced with this topic, but may the difference between EGM96 and WGS84 height be a possible cause for that offset? The difference in our area seems to be around 60m. I do not know which format the GPS module is usually reporting. See https://en.wikipedia.org/wiki/EGM96 for details ...

**Comment by ptt79** [comment]
As I now also received my Skydrop, I could replicate the issue, that it shows constantly a too low altitude, and also at my location it matches the geoid offset. So I checked the NMEA syntax (as in the manual of used GPS there is no detailed information about which height given by the altitude parameter) and confirmed:
fist altitude given in  $GPGGA sentence means already MSL (WGS84 compensated with geoid offset). The extra geoid height information following as next value is just to convert it back to WGS84.

As MSL is relevant for most of us (and most other GPS as well as maps also shows MSL) I would suggest to remove the geoid subtraction in your GPS driver code:
line 236 	fc.gps_data.altitude -= geo_id; 

Hope that fixes the issue.

**Comment by ptt79** [comment]
Just have seen that you made the change in drop 0910 (thanks!) and tested gps height: With this update there is no significant offset to my other gps devices and real altitude any more, so this issue can be closed.

**Comment by RomanKreisel** [comment]
Just tested it on my balcony, and the offset is gone on my device as well.
Thanks you very much for solving this issue! :)
