### ISSUE TITLE
Suggested feature : Ability to register several gliders and to switch between registred gliders easily

### ISSUE THREAD

**Issue by ukeconsulting** [fhorinek/SkyDrop#420]
Hi,

When we have several gliders, it could be good to switch easily from one glide from another on the same vario.

In "Glider type, for IGC record" we could be able to register 2 or 3 glides with their related "Glider ID, for IGC record".
A widget could show the glide in use and with a long press on it and side button we can change quickly from one glide to another in cycle. 

Bonus: Why not the same type of feature with the "Pilot name, for IGC record
" where there is "Guest" for when we lend the vario to a friend.

thanks in advance

**Comment by fhorinek** [comment]
Hi, unfortunately this would require a a lot of new stuff to write (== big memory usage) and unfortunately the device is already maxed out.
