### ISSUE TITLE
HOME & wpt files don't work :  error "no waypoints founds"

### ISSUE THREAD

**Issue by ukeconsulting** [fhorinek/SkyDrop#426]
i tried to use a file made by https://vps.skybean.eu/homes/  as HOME position and it doesn't work.

i tried with 3 home files put in differents directories and try to activate it from the menu (navigation - home position )

in HOME directory with .txt extension = vario firmware don't see it 
in HOMES directory with .wpt extension = vario firmware don't see it 
in WPT directory with .txt extension and .wpt extension = vario firmware see them but error "no waypoints founds" from begin and each time i validate a file (.txt or .wpt)

ATTERO_C.txt and ATTERO_C.WPT
NAME: Attero Chedde
LOC: 45.9289162N 6.72475743E

ATTERO_L.txt and ATTERO_L.WPT
NAME: Attero Lac
LOC: 45.9164438N 6.66487842E

ATTERO_B.txt and ATTERO_B.WPT
NAME: Attero Batistock
LOC: 45.9162278N 6.70710754E

note: the same problem occurs with wpt file https://parapente.ffvl.fr/compet/3628/balises
i never were able to use wpt. 
even manually done.

**Comment by bubeck** [comment]
I assume you are running the latest firmware or at least version 5027. Please find the specification of the file format under https://github.com/fhorinek/SkyDrop/wiki/Navigation.

Upon your request I created this page to explain this (new) file format. You were using the old page, which is not your fault, as the new page didnt exist. :)

**Comment by ukeconsulting** [comment]
yes i always update to the last firmware available  and test with it before posting.

thanks for the quick answer and the documentation update, it is far easier now with the cup files:
i can see and choose the waypoints i want.
i need now to be autorised to fly in order to test it :-)

**Comment by bubeck** [comment]
seems to be fixed. -> Please close.
