### ISSUE TITLE
Double battery skydrop - appear unable to enter Battery Calibration mode?

### ISSUE THREAD

**Issue by bluearcus** [fhorinek/SkyDrop#428]
I have an early Skydrop retrofitted with the dual battery kit.

Recently I upgraded to latest firmware and have been trying to carry out a battery calibration run.

Behaviour is always as follows. Irrespective of charge state...

Enter settings, Advanced, Calibrate, select Battery.

Short press to select.
Irrespective of charge state or whether USB is plugged in, message always shown saying 'Plug USB and wait for full charge'.

Whether USB was already plugged in, or is plugged in at this point, or is not plugged in then after a few seconds the message goes away.

No further messages are shown, no matter how long the Skydrop is then left plugged in (tried 12+ hours).

Unplugging then seems to simply return Skydrop to normal mode.

What should be the behaviour here? How should the Calibration 'check' indicator appear (it only ever shows as an empty square, never selected). What further message should appear to indicate ready to enter discharge logging?

Ran full discharge anyway after a period. Doesn't look like calibration has run, but not sure how to tell.

**Comment by fhorinek** [comment]
Full battery and plugged cable is calibration start condition.
You need to plug the usb and wait for a full charge.
Then go to menu and select the calibration.
During the calibration the box is checked.
The battery indicator will blink during calibration.

**Comment by bluearcus** [comment]
I have tried this several times, without success. The message is always shown, and calibration mode is not entered.

This afternoon, with the instrument off, I charged it for 2 hours.
On startup, the vario shows 99% charge. I then charge for 1 hour further with the vario on.
Just now I select the calibrate option.
And the message is shown again, and calibration does not start.

My understanding is that the instrument does not know battery state when charging (hardware) so what logic is being used to determine that it is charged and ready to start the discharge please?

Either there's something needed in terms of a missing step which I am not doing, or there is some other problem?

**Comment by bluearcus** [comment]
Attempting to enter calibrate at 100% charge... with unplugged USB. Message shown.
Attempting to enter calibrate at 100% charge having just plugged USB. Message shown.
??

**Comment by bubeck** [comment]
I will check it this evening. What I can remember, that I really needs a lot of time. Code can be found at https://github.com/fhorinek/SkyDrop/blob/master/skydrop/src/drivers/battery.cpp.

The basic idea is:
 1. Plugin USB
 2. Start calibration.
 3. What until battery is full (this needs sometimes >12h)
 4. Unplug USB
 5. Wait until battery is empty and device shuts down
 6. When turning on again, the calibration is read and available.

**Comment by bluearcus** [comment]
Plugged skydrop in to USB charger, from near full state. Turned on. Started calibration. Message appears 'Plug USB and wait for full charge'. Leave instrument alone, plugged in. 20 hrs now.

I presume I should I be seeing the fixed unplug message, until I disconnect at which point the backlight goes on and the discharge curve logging stage then runs. No sign of this yet...

**Comment by bluearcus** [comment]
Thanks for the workaround Tilman... yes, this allows me to enter calibration mode quickly with just a few minutes charging in USB mode.
