### ISSUE TITLE
SkyDrop not detected and not switching to USB mode, only charging

### ISSUE THREAD

**Issue by ahmadooka** [fhorinek/SkyDrop#437]
My SkyDrop is not getting detected and not switching to USB mode, only "Charging" then "Battery full".

It was not doing this before until I recently upgraded to build 5205 rev 1506 and since then it is not getting detected.

I have tried 2 different windows 10 PCs, different USB ports and different cables but still the same issue.

Unfortunately I am not able to provide the debug log since I can't connect to the device.

I have not tried factory reset but let me know if you have any other suggestions before I try that.

**Comment by ahmadooka** [comment]
Also enabling / disabling mass storage option in settings is not helping

**Comment by 0x007E** [comment]
Same problem, solved it by changing the USB cable. There are some cables for charging only they have no RX/TX so the device can't connect to the PC.
