### ISSUE TITLE
Invalid numbers in airspace code comments

### ISSUE THREAD

**Issue by jcoffland** [fhorinek/SkyDrop#444]
0x7f == 127 not 126 as the code comments imply.

https://github.com/fhorinek/SkyDrop/blob/206a54fda58a2a7d34b282a1dbe18725cbc9f9e2/skydrop/src/fc/airspace.cpp#L10-L11

The comment should read:

```
//#   -III IIII - 0 - 126 index
//#             - 127 no airspace (127, 0x7F)
```

**Comment by bubeck** [comment]
thanks! I will create a PR with your change.
(If you like to, you can do this on yourself).

**Comment by jcoffland** [comment]
Go ahead and make the PR.
