### ISSUE TITLE
Enabling instant vario setting

### ISSUE THREAD

**Issue by bazirico** [fhorinek/SkyDrop#451]
Hi everyone,

I've just update my Skydrop, didn't do that in almost 2 years. I see that now you can have instant vario reaction : 

https://www.youtube.com/watch?v=xt_1UM_uatI

Can you tell me where can I enable this ? I've search in the settings, browsed the wiki and the FAQ but except for the video, I didn't see any mention of this feature.

To test, I've set the Lift/Sink threshold to +0.1 and -0.1 m/s. No sound when moving upward and downward with my arm.

Build 5205
Rev 1506

**Comment by fhorinek** [comment]
The setting is called vario / use accel.
If it does not work, try to re-calibrate the sensors
