### ISSUE TITLE
Larger font - Feature request

### ISSUE THREAD

**Issue by FlyLightTAS** [fhorinek/SkyDrop#453]
I'd love for altitude, vario and speed to scale to, say 85% of the widget area. I'm too old to see the default sized small writing on the screen!!!

**Comment by bubeck** [comment]
You can go for a screen layout of just 1 (or maybe 2 or 3) widgets. This means, that there is more place and fonts will get bigger. However, even the largest font on the device could be too small. Unfortunately the display is really small.

I dont assume, that there will be a bigger font used by the device, as the screen is very small in any case and memory is nearly full. :(

**Comment by FlyLightTAS** [comment]
Yeah, I tried single display but my eyes still aren’t that great. Using my phone as a screen because i love the tone and weak-lift features.

No problem.

thanks for the support.


Brad

---------------
Brad Harris
bh photo - hobart
ph:0428 626 470
w: bhphoto.com.au <http://www.bhphoto.com.au/>
f: https://www.facebook.com/bhphoto.hobart
---------------------------------------------------------
