### ISSUE TITLE
Coding style and automatic code formatting, i.e. clang-format?

### ISSUE THREAD

**Issue by tleichtle** [fhorinek/SkyDrop#454]
As SkyDrop user and SW developer I'm thinking about getting involved in the development.
Is there any recommended coding style and a way to enforce it, i.e. a clang-format file for it?

**Comment by bubeck** [comment]
Unfortunately no. You have to take a look at how the existing code is formatted. If you need specific help, feel free to ask me or fero.

Unfortunately the development of skydrop has nearly come to an end, as the coding space in eeprom is full (except a few hundred byte). To include further functionality, we first have to shrink existing code (which is also hard).
