### ISSUE TITLE
Airspace

### ISSUE THREAD

**Issue by Pisa56** [fhorinek/SkyDrop#460]
I'm new with Skydrop - but after a lot of hours spent in configuring and connecting (xctrack) I can say I'm not a novice anymore. 

But the topic airspace is really an issue. 
So please tell me how to implement the newest (!) airspace into skydrop.
Write a script to convert Open AIP FIles to these special AIR files.
I don't know your IT programming language. So for an (advanced) user, it is still impossible to do that job.
A really strange thing happen. Or just tell that is not possible and one can not use that feature in skydrop. So one does not have to spend hours for anything.

**Comment by bubeck** [comment]
As I wrote part of the airspace code, I will try to create updates, iff @fhorinek is not sending a message here, that he will do this.
I will keep you informed here.

**Comment by Pisa56** [comment]
Hi There, nice to hear from you - We need Switzerland (export from XCtrack probably best from a Sunday or holiday, because they switch on daily Airspace from Military on working days.) 
By the way, where does this AIR-Format come from? It does not exist on any other device. 
Would be good to have a script or batch file to convert. Is there no existing script?
I don't know exactly if it's worth doing so, because probably the device is a bit out of date and at least you can connect it to the smartphone. 
Anyway, it was hard to find out these things and how it works (or do not work). :-)
regards Pi

**Comment by bubeck** [comment]
Please find switzerland here: http://bubecks.de/public/sky/switzerland_ch.zip

It was generated today based upon "Switzerland (CH) | 27.12.2021 | 13.06.2021 | openaip_airspace_switzerland_ch.aip | aip | 163.42 KB"

I do not take any responsibility for correctness or whatever. Please tell me, if this is OK.

The AIR comes from openaip.net. It is a community building freely available airspace definitions. Find more information on openaip.net

**Comment by fhorinek** [comment]
@bubeck Thank you.
I know the SkyDrop is not getting the love it should have. sorry.
I am now on holiday, but I have refreshed the source file from openaip and now I am processing the files. The update airspace will be available in few days as it is quite intensive on processing.

**Comment by Pisa56** [comment]
you do a great job. By now I love the Skydrop.

**Comment by fhorinek** [comment]
https://vps.skybean.eu/air/ is updated except for US, canada and australia. 
The files are still regenerating.

_BTW the reason for openAIP was that (at the time) the files were properly formatted and provided from single place. Many open air files were outdated and full of errors, every file need to be fixed before. I will recheck current sources for new data_

**Comment by Pisa56** [comment]
Thanks a lot (work in progress). What I can mention is that the airfields are missing. I tested two devices.

The easeast an best would be an export in XCTrack. (switch on "freeflying" "All", "Country", Switch off "Notam" >> Import it in open AIP >> export it and convert it to AIR. (Airfields are included)

Is there no script to be published for that? A Batch or Java script for example, implemented on your website?.

cheers Pi
![noname](https://user-images.githubusercontent.com/96610670/147552176-2270022f-ac40-4797-b446-8f2366d2053c.jpg)

**Comment by bubeck** [comment]
Why would you like to include airfields into the data for the SkyDrop? The device is not dealing with airfields: there are no widgets showing them or whatever. The code deals with airspaces, so that flying is always in allowed airspace.

**Comment by Pisa56** [comment]
the problem is that airfields in openAIR are only marked as Spot (or Point). As you can see on every openair file from XCtrack (or DHV). It is not allowed for paragliders and hang-gliders to enter this "airspace" So let's say in Switzerland/Thun you can see the airfield as in the Image. The borders of the airfield (like many in Switzerland) are individually managed by agreement (which are official for paragliders (and hanggliders). 
I mean, we do that for years (to export and convert to other formats). since XCtrack provides now all the files (also international) in openair format, there is the possibility to convert it for many other devices. 
without the airfields, this procedure is completely useless because usually, you fly not only near TMA or CTA but especially close to airfields.  
![image](https://user-images.githubusercontent.com/96610670/147556886-d973e454-45ad-48b0-bb26-aa67e7244151.png)

**Comment by bubeck** [comment]
The problem is with the underlying data from openaip.net where airfields and their airspace "P" are missing. I created a corresponding issue for openaip at https://github.com/openAIP/openaip/issues/91

**Comment by bubeck** [comment]
I received an answer from openAIP:

> The problem is with the underlying data from openaip.net where airfields and their airspace "P" are missing. I created a corresponding issue for openaip at [openAIP/openaip#91](https://github.com/openAIP/openaip/issues/91)

They will not add this to their dataset, as this is specific for paragliding and they do general aviation and nothing specific. So we have to insert this data ourself. This would be a todo for SkyDrop. I am not sure, if this will be done, as development shifted towards strato (However, this also applies to airspace on strato).
