### ISSUE TITLE
Firmware update (Build 5250) creates malfunction on website and skydrop crashes

### ISSUE THREAD

**Issue by 0x007E** [fhorinek/SkyDrop#466]
The new firmware is incompatible with the website [Configurator](https://vps.skybean.eu/configurator/). After updating firmware config is empty and the SkyDrop hangs on startup.

![image](https://user-images.githubusercontent.com/61001336/160577360-f033fafd-ad10-472a-96c3-a5c9de5e21c5.png)

**Comment by kolaCZek** [comment]
This looks suspicious:

https://github.com/fhorinek/SkyDrop/commit/e3cafa9af15c6c0cb14395b4074e259c0668ba57#diff-fe0f32c3074ae1bf6b21ddbe59d9ddbb1478672ea8aaaafd4a26f880cfff7de8R54

**Comment by Pisa56** [comment]
same here yes... doesn't work - can not configure the screens

![image](https://user-images.githubusercontent.com/96610670/160655206-02e9e5c0-b6f3-4116-aae2-8aadcad8e3e2.png)

**Comment by bubeck** [comment]
> This looks suspicious:
> 
> [e3cafa9#diff-fe0f32c3074ae1bf6b21ddbe59d9ddbb1478672ea8aaaafd4a26f880cfff7de8R54](https://github.com/fhorinek/SkyDrop/commit/e3cafa9af15c6c0cb14395b4074e259c0668ba57#diff-fe0f32c3074ae1bf6b21ddbe59d9ddbb1478672ea8aaaafd4a26f880cfff7de8R54)

Why?

**Comment by 0x007E** [comment]
@Pisa56  at least that works that the Skydrop runs. But the whole config is lost and the standard config is loaded. If you load your config into the [configuration](https://vps.skybean.eu/configurator/#/wizard) tool, it will update your firmware again to Build 5250 and you will run in an endless loop. Of course it is better to fly with standard config instead of having no vario ;-)...

**Comment by 0x007E** [comment]
@Pisa56 at least that works that the Skydrop runs. But the whole config is lost and the standard config is loaded. If you load your config into the [configuration](https://vps.skybean.eu/configurator/#/wizard) tool, it will update your firmware again to Build 5250 and you will run in an endless loop. Of course it is better to fly with standard config instead of having no vario ;-)...

**Comment by 0x007E** [comment]
@kolaCZek thanks for investing the time, it worked perfectly!

**Comment by bubeck** [comment]
> @Pisa56 , @0x007E You can use this: https://www.kolaczek.cz/SkyDrop/skydrop_configurator/app/ It's working config page for 5205 (only temporary till devs will fix official config page) ;)
> 
> #god_bless_opensource

Fantastic work, could you please do a PR with your fix?

**Comment by kolaCZek** [comment]
> > @Pisa56 , @0x007E You can use this: https://www.kolaczek.cz/SkyDrop/skydrop_configurator/app/ It's working config page for 5205 (only temporary till devs will fix official config page) ;)
> > #god_bless_opensource
> 
> Fantastic work, could you please do a PR with your fix?

I only cloned repo and reverted last changes...

`git checkout d43d0f4b5197829a390d4ff337413fe41390f89c`

**Comment by fhorinek** [comment]
The configurator is fixed, sorry
