### ISSUE TITLE
Firmware (Build 5248) doesn´t create a correct *.igc file

### ISSUE THREAD

**Issue by 0x007E** [fhorinek/SkyDrop#467]
The IGC files created by [Build 5248](https://github.com/fhorinek/SkyDrop/commit/6162849d04bdaf4736f230dc9b93d96fa1d585d2) are not correct and can´t be ranked on [xcontest](https://www.xcontest.org/world/en/). It says that the file is `not validated` correct. [IGC File](https://www.xcontest.org/track.php?t=1648403273.59_6240a34990901.igc)

**Comment by kolaCZek** [comment]
Same here...
`AXSBDRP:375930313531170C001500
HFDTE260322
HFPLTPILOTINCHARGE:kolaCZek
HFCM2CREW2:NIL
HFGTYGLIDERTYPE:FAI-3 (PG) Discovery 5
HFGIDGLIDERID:EL SPEEDO Freddie 2
HFDTMGPSDATUM:WGS84
HFRFWFIRMWAREVERSION:build 5248
HFRHWHARDWAREVERSION:drop_1506
HFFTYFRTYPE:SkyBean,SkyDrop
HFGPSRECEIVER:Quectel,L80,22cm,18000m
HFPRSPRESSALTSENSOR:Measurement specialties,MS5611,25907m
HFALGALTGPS:GEO
HFALPALTPRESSURE:ISA
HFTZNTIMEZONE:+2.0
HFFRSSECSUSPECTUSEVALIPROG:This file is not valid. Private key not available!
B1250325024395N01346205EA0029500420
B1250335024395N01346205EA0029500420
...`

**Comment by bubeck** [comment]
> HFFRSSECSUSPECTUSEVALIPROG:This file is not valid. Private key not available!

The 5248 is not an official firmware, and therefore does not contain the digital signature needed to sign IGC.
Please use official 5250.

**Comment by 0x007E** [comment]
Thanks @bubeck for reply, I installed it over the official website. Maybe i was to fast.

**Comment by kolaCZek** [comment]
But there is proglem with [configurator](https://vps.skybean.eu/configurator). It's not possible to upgrade to 5250.

https://github.com/fhorinek/SkyDrop/issues/466

**Comment by kolaCZek** [comment]
Btw, how to recognise official and non-official firmware? I've updated to 5248 via [configurator](https://vps.skybean.eu/configurator) like any other version before...

**Comment by Pisa56** [comment]
5250 doesn't work go to 5205 
https://vps.skybean.eu/repo/updates/

**Comment by kolaCZek** [comment]
@Pisa56 This will reset vario to default settings. [Config page](https://vps.skybean.eu/configurator) is only 5250. And still does not work properly (#466). :(

**Comment by 0x007E** [comment]
@Pisa56  at least that works that the Skydrop runs. But the whole config is lost and the standard config is loaded. If you load your config into the [configuration](https://vps.skybean.eu/configurator/#/wizard) tool, it will update your firmware again to Build 5250 and you will run in an endless loop. Of course it is better to fly with standard config instead of having no vario ;-)...

**Comment by Pisa56** [comment]
I didn't lose my config. I saved 5205 in a file before. More or less luck.

**Comment by fhorinek** [comment]
Sorry guys.
To clarify the problems, I forgot to include IGC private key when I build 5248.
When I realize my mistake I immediately remove the file forcibly.
Then I publish fix for the IGC logger and broke the configurator.

Everything is fixed now.

Anyway the 5248 was official, but flawed.
Also the new builds does not provide any new functions, just add support for xmega256 as drop in replacement for x192 and remove the sht21 support for boards without the sensor (Chip shortage fun).

**Comment by LukaszWiktor** [comment]
I updated my SkyDrop to build 5281, and I'm encountering the same problem.

```
AXSBDRP:3855303139360A0D001500
HFDTE110124
HFPLTPILOTINCHARGE:
HFCM2CREW2:NIL
HFGTYGLIDERTYPE:
HFGIDGLIDERID:
HFDTMGPSDATUM:WGS84
HFRFWFIRMWAREVERSION:build 5281
HFRHWHARDWAREVERSION:drop_1506
HFFTYFRTYPE:SkyBean,SkyDrop
HFGPSRECEIVER:Quectel,L80,22cm,18000m
HFPRSPRESSALTSENSOR:Measurement specialties,MS5611,25907m
HFALGALTGPS:GEO
HFALPALTPRESSURE:ISA
HFTZNTIMEZONE:+1.0
HFFRSSECSUSPECTUSEVALIPROG:This file is not valid. Private key not available!
```
