### ISSUE TITLE
Changing Contrast Settings Question

### ISSUE THREAD

**Issue by aktie** [fhorinek/SkyDrop#47]
Default Contrast in build 0551 is 70%. Once I try to make it higher or lower and press "<" or ">", the value changes to 78% or 79%. You can't cancel it and have to press the "o" button. Once pressed, no matter what's the contrast setting, the whole background becomes dark and it's very hard to see anything on the screen. Build 0530 does the same. The only way to get display back to normal is to update the software.

**Comment by fhorinek** [comment]
Did you run the factory test correctly after 523 update?

**Comment by aktie** [comment]
1st update I did was from 0322 to 0530. The screen went dark after update, I thought it messed up. According on the website info I expected it just to work. Maybe there was the "factory test", not sure. My 1st reaction was just to press buttons randomly until I realized the unit works, but is just very dark. Then I did a few more updates to see what causes screen go dark, but there was no factory tests then.

**Comment by aktie** [comment]
Found Factory Test Reset in settings and ran it. It started cycling the contrast from zero to max. I pressed it at a wrong time I guess and this time it made it totally invisible of anything on the screen. Another software update.. Another Factory Test Reset... Now instead of pressing "o" I pressed arrow key and realized that this is the way you set up minimum contrast. Then Set Max, then Set Optimal?... Then next screen some small letters and numbers with "OK", except "BUT: 1 0 1". If you press "<" LED goes from blue to red and there's a long non-stop beep.
Not intuitive, should be explained for users what to expect and how not to mess up like I did.

**Comment by aktie** [comment]
Even after I though I did everything OK, I restarted the unit, went in Settings>Display>Contrast. It was 70% there. Once I press "<", the screen goes totally blank again, no texts no graphics, just backlight until timeout.

**Comment by fhorinek** [comment]
Have you read this?
http://vps.skybean.eu:8080/repo/updates/0523/Warning.txt

**Comment by aktie** [comment]
Guess from 3 tries

**Comment by fhorinek** [comment]
I guess not

**Comment by fhorinek** [comment]
Is it working for you now?

**Comment by aktie** [comment]
Victory! You guessed right! Crazy wording in the Warning txt file X) Yes, @fhorinek, it does work for me - figured it out through trial and error, at least didn't have to unbrick it - software reinstalls were enough. Still the question remains - why do we need "Settings>Display>Contrast" if it has such a tiny unnoticable range (70-72 after the last successful Display Test Reset)?

**Comment by fhorinek** [comment]
Because every display is different. Sadly. Some works from 45-62 some 80-92...

**Comment by aktie** [comment]
OK, fair enough then

**Comment by fhorinek** [comment]
I will leave this open, it is easier to find the opened issues for newcomers

**Comment by aktie** [comment]
I think warning people about Reset Factory Test would be more effective, I followed instructions of updating there.

**Comment by fhorinek** [comment]
I added this
Please read carefully additional instructions before update when they are included in build directory (e.g. Warning.txt,. Readme.txt)
