### ISSUE TITLE
odometer, distance to takeoff, xc-distance would also be nice.

### ISSUE THREAD

**Issue by fhorinek** [fhorinek/SkyDrop#49]

**Comment by bubeck** [comment]
"odometer" and "distance to takeoff" implemented in https://github.com/bubeck/SkyDrop but not yet pushed.
Next step is "bearing" and then the GUI widget.

**Comment by fhorinek** [comment]
Great to hear that,

one small remarks, I would prefer to have odometer function in separate
file in fc directory

See you @ thermik messe, you will have one skydrop ready for you for your
contributions (for free) :)

Fero

--
František Horínek

2017-02-15 15:03 GMT+01:00 Dr. Tilmann Bubeck <notifications@github.com>:

**Comment by bubeck** [comment]
Hey, that sounds great! :)

CU at Thermik.

**Comment by bubeck** [comment]
Everything implemented, test needed but soon possible, when skydrop is in my hands. :)

**Comment by fhorinek** [comment]
done
