### ISSUE TITLE
Battery display

### ISSUE THREAD

**Issue by dnngll** [fhorinek/SkyDrop#5]
Feature request: Different battery status views: 1. Status not shown (save some screen estate), 2. Only percentage shown in upper/lower left/right corner, 3. One line of Pixels on eiter top, bottom, left or right side, 4. Battery bar.

Feature for all 4 viewing options: Only show battery if lower then X percent. X definable

**Comment by fhorinek** [comment]
Left bar will be used for GPS, BT, SD and Logging notification area
