### ISSUE TITLE
Audio Volume - Less Gradual (0%, 40%, 55%, 70%, 85%, 100%)

### ISSUE THREAD

**Issue by aktie** [fhorinek/SkyDrop#50]
Audio Volume gradation is too fine for a variometer in my opinion. Do you really need 5% increments? That's not an audio player! Something like 0%, 40%, 55%, 70%, 85%, 100% would be enough for most users. Currently the interface is extremely poor. Imagine default screen. Now, how many times do you need to press buttons to get Audio Volume from 0% to 100% and back to the main screen? That's 35 TIMES pressing these awful buttons!
Count:
- long press "o",
- ">"x5,
- "o",
- ">"x2,
- "o",
- "o",
- ">"x20,
- "o",
- long press "o",
- long press "o",
- long press "o".

**Comment by fhorinek** [comment]
True, I will look on this issue after volume parameterization.

**Comment by mennodenhollander** [comment]
You could also do a long button press, and while the button is pressed in continuously increase/decrease the volume every half a second.

**Comment by fhorinek** [comment]
long press value change will be implemented in next release

**Comment by tofuatjava** [comment]
is it possible to make the audio louder at all. in case of a visor helmet it could be louder...

**Comment by fhorinek** [comment]
No sorry 100% is the max.
anyway the 0% / 25% / 50% / 75% / 100% for audio is now implemented
