### ISSUE TITLE
Easy Audio ON/OFF Switching - in Layouts or Widgets

### ISSUE THREAD

**Issue by aktie** [fhorinek/SkyDrop#51]
Pilots often want to turn the sound of vario on only after taking off and then turn it off sometimes during the flight. I suggest:
- Muted Sound Layout. Switching to another layout with enabled sound immediately turns the volume up, basically enough of pressing "<" or ">" once;
- Audio Volume Control Widget, similar to Altimeter widgets. Either Audio ON/OFF, either few gradation steps.

**Comment by fhorinek** [comment]
There is automatic audio on after take-off. But there will be implemented something like configurable shortcuts for actions on double-click on each button.

Will this work for you?
Also the layout option may be interesting

**Comment by aktie** [comment]
Shortcuts sound fun, but now when you press arrow keys, it jumps to the next layout immediately. If you wait for a double click, you will have to delay switching screens. Also, buttons are hard to press in winter gloves, so if instead of double clicking you click it just once? - it jumps to a different layout which you don't want to happen. Because of the button of SkyDrop is not flat, it rocks on a side in cockpit when you press arrow keys - which makes it even more difficult. Maybe a long arrow key press instead of double-click would be more effective?
I think it's very much a personal thing, but I would rather prefer single clicking:
- "<" to switch through screen layouts;
- ">" to switch through volume gradations.
And maybe long presses for some other functions.

**Comment by tomasz13** [comment]
I think the long arrow press is a good choice for volume control (& clicking for layout select)

**Comment by tomasz13** [comment]
also would be nice to switch on/off the buzzer & vario separately... now if i switch off the vario sound, I cant hear the buzzer. 
When I use the vario connected with the smart phone, the application like xctrack can provide a vario sound, but cant buzzing... that way there is a situation when I would hear only the buzzer.

-    a long arrow press for volume control from off to maximum

-   widgets: 1. for "all sound on/off", 2. for "vario sound on/off", 3. "buzzer sound on/off"

**Comment by fhorinek** [comment]
Now we have silent page setting and widget. Everyone happy? Can I close this now?
