### ISSUE TITLE
Flight Time Counter Never Stops

### ISSUE THREAD

**Issue by aktie** [fhorinek/SkyDrop#52]
Once SkyDrop registers the start of a flight, it doesn't stop. I went for a 30 min walk, put SkyDrop on the desk, after 45 minutes of lying on one place Flight Time keeps ticking. GPS was on. I turned it off - no difference, flight counter goes on.

**Comment by fhorinek** [comment]
Yes this is true, it is because auto landing is not yet implemented

**Comment by aktie** [comment]
I keep SkyDrop turned on lying on the desk. Sometimes it starts Flight Timer for no reason or when after some time I lift it up 10-20 cm

**Comment by fhorinek** [comment]
It is because of baro alt drift over time. I will add some sort of reset over time to compensate this.

**Comment by fhorinek** [comment]
done in next release
