### ISSUE TITLE
update from 322 to 551

### ISSUE THREAD

**Issue by Albifly** [fhorinek/SkyDrop#53]
Hi all, I can not understand how to update from 322 to 551. If I do it I loose all the widgets on the display.
Thanks

**Comment by fhorinek** [comment]
Are you applying UPDATE.EE as well?

**Comment by Albifly** [comment]
yes! I copied update.ee and update.fw in the device. I think I am doing everything correctly, after playing with the contrast I had to reset the device and then I loaded the 322, but if I try to load the 551 I found this problem every time.

**Comment by fhorinek** [comment]
just to clarify Update.ee and update.fw bust be from same bild directory. When updating to build with new factory test you need to follow this https://github.com/fhorinek/SkyDrop/blob/master/updates/0551/Warning.txt

**Comment by Albifly** [comment]
first I put RST_FT into the device and restart it. Then I put both of the files in it and restart. Is it correct?

**Comment by fhorinek** [comment]
should work but try:
put update.fw and rst
then put RST_FT and pwr
then put update.ee and pwr

**Comment by Albifly** [comment]
No way... It accept the 322 but as I try to load the 551 UPDATE.EE it disappear everything from the display

**Comment by fhorinek** [comment]
You are doing something wrong if you did not found contrast calibration.
Please put UPDATE.FW on drop and press RST
Then put RST_FW and UPDATE.EE on drop and press PWR
Then follow instructions here https://github.com/fhorinek/SkyDrop/blob/master/updates/0551/Warning.txt

**Comment by Albifly** [comment]
Thank you for the super quick reply. Now I am trying to load the new update, I can start now with your indications the contrast calibration but my on the display now I can not see anything.... Maybe too complicated for me
