### ISSUE TITLE
Maximum contrast config value too low.

### ISSUE THREAD

**Issue by bluearcus** [fhorinek/SkyDrop#54]
The maximum 'dark' contrast value that can be set in the factory config routine is 127, and on my skydrop this is very close to the best value. It is certainly nowhere near the background pixels going dark point. This seems to mean when the temperature varies (eg when charging) my screen becomes unreadable.

Can the max seeing be allowed to go higher than

**Comment by bluearcus** [comment]
127, or is do you only have 7 bits representing the voltage to play with?

If the range can be made bigger, please consider this. Otherwise, I am concerned that the screen on my unit will never be able to be set to cope with temperature changes properly, as its dark endpoint is outside the expected range.

**Comment by fhorinek** [comment]
Did you notice only after the last release? If so after what release?
Unfortunately 127 is maximum value I can send to display first bit is command identifier.


```c++
src/drivers/n5110_disp.cpp@178
void n5110display::SetContrast(uint8_t val) //0-127
{
	sendcommand(0x21); //Extended
	sendcommand(0x80 | val);
	sendcommand(0x20); //Basic
}
```

**Comment by bluearcus** [comment]
Have only tested on last release. Contrast settings which look fine (except for not being able to reach the upper black limit) when set in factory config seem to often result in an unreadable screen on restart. Setting the display config in the menu then results in a working setting, which survives restarts, but it's not at all stable with temperature change and can easily become practically unreadable.
On 9 Jul 2015 06:07, František Horínek <notifications@github.com> wrote:Did you notice only after the last release? If so after what release?
Unfortunately 127 is maximum value I can send to display first bit is command identifier.

src/drivers/n5110_disp.cpp@178
void n5110display::SetContrast(uint8_t val) //0-127
{
    sendcommand(0x21); //Extended
    sendcommand(0x80 | val);
    sendcommand(0x20); //Basic
}

**Comment by bluearcus** [comment]
Further investigation... this was down to pressure on the display component after re-assembly. The case front and back joining gasket must be fitted the correct way up, or the display is subject to pressure from the front of the case when the unit is assembled. This moves the display contrast point towards the grey end, and makes the display very subject to changes in contrast when the front of the case area above the screen is pressed.

If pressing the case front gently above the display area causes contrast changes, then the gasket ring is upside down!

Can we have an assembly diagram showing the correct orientation for the gasket? A better long term fix would be to have a notch in the edge of the back case, and a raised part on the gasket which fits into this to prevent fitting the wrong way up.
