### ISSUE TITLE
Build 0789

### ISSUE THREAD

**Issue by aktie** [fhorinek/SkyDrop#55]
Few comments on the build 0789:
- 1st layout (the very left one) has Debug as the 3rd widget;
- DUMP.EE being created on the SD card;
- cycling through menus sometimes lag or just don't jump to next menu at all, haven't figured out what causes it. After few minutes it goes back to normal - no lags or freezing;
- Backlight adjustment - perfect;
- Contrast - how about if you long-pressed arrow keys, it would slowly start changing contrast without the need of click-click-click-click-click-click?
- Time-out period of the long "o" press on the main screen - I, personally, would prefer it to be a second or two longer, disappears too fast.

**Comment by fhorinek** [comment]
* True, but can be easily changed
* True, not a bug it is preparation for configurator
* Buttons drivers was untouched from last release. I am guessing that may be GPS issue, did the lag appeared only in gps menu config?
* :)
* It is on task list
* Can and will be extended

**Comment by aktie** [comment]
Mentioned Debug widget in layout because normal users don't need it  ;)
The lag was happening everywhere - display settings, GPS, etc. I thought it was because GPS could not find signal, but it continued for another minute or two after I turned GPS off. Updated the software, will see if it happens again.

**Comment by fhorinek** [comment]
True, but still can be easily fixed.
There is possibility of lag in gps menu since when you enter it gps will send more detailed messages than usual.

**Comment by fhorinek** [comment]
* Contrast - how about if you long-pressed arrow keys, it would slowly start changing contrast without the need of click-click-click-click-click-click?
 * done

* Time-out period of the long "o" press on the main screen - I, personally, would prefer it to be a second or two longer, disappears too fast.
  * done

**Comment by aktie** [comment]
I switched the SkyDrop on a few hours ago to see how long battery lasts. It started counting flight time at some point. fTime counter shows now "151:53". If that's minutes:minutes, 151 minutes + 53 minutes = 3h24m. 53 was going up once a minute until 151:59. Then it changed to 152.00. If 152 is hours - hours of what?

**Comment by fhorinek** [comment]
did you change the clock during "flight"? because now it cannot compensate for that

**Comment by aktie** [comment]
No, didn't change. Actually.. I didn't change the time after updating software. Then I kept SkyDrop turned on for a couple hours, then turned GPS on. Not sure when the flight time started, but GPS must have changed the time, right.

**Comment by fhorinek** [comment]
Gps will update the time, so that will be the problem.
FTime show MM.SS when MM < 60 or HH:MM

**Comment by aktie** [comment]
Wouldn't be bad for fTime just to have it's own time counter and not change if GPS changes the clock on the device

**Comment by fhorinek** [comment]
done in next release
