### ISSUE TITLE
Charging / Data Connection

### ISSUE THREAD

**Issue by aktie** [fhorinek/SkyDrop#56]
If device is turned off and you plug in a power cable, it should stay turned off after unplugging the cable. Now, when you unplug a cable, device turns on and goes into flying instrument mode - not OK.
That would be cool if device behaved differently in charging/data connection modes:
- data connection: USB mode + "charging" instead of "battery 100%";
- power connection: red LED for charging, green LED for charged, no USB mode.

**Comment by fhorinek** [comment]
Done
