### ISSUE TITLE
Factory test

### ISSUE THREAD

**Issue by Albifly** [fhorinek/SkyDrop#57]
I would like to know how to do the factory test. I put the file into the device and I switch it on, it starts with only the backlight on the display and a strange sound. And then? I wait for something on the display to press the left button as the instructions say but nothing happen...

**Comment by fhorinek** [comment]
You have probably used wrong update file, did you get it from github or http://vps.skybean.eu:8080/repo/updates/

**Comment by Albifly** [comment]
I took it from the 789 folder

**Comment by fhorinek** [comment]
github or link http://vps.skybean.eu:8080/repo/updates/
I ask because lot of people do not know how to properly download from github and it is a common issue #18

**Comment by Albifly** [comment]
So how can I do the factory test?

**Comment by fhorinek** [comment]
Did you update the firmware correctly?
From what location?
When you plug it to usp does it go to usb mode? can you see it as mass storage device?

**Comment by Albifly** [comment]
Now I have the 322 and I can load it without any problem. I am not able to load anyone with the factory test. I take the file to start it from the same folder where I find the two files .EE and .fw. I am sure I do something wrong but Following the instructions step by step when I switch it on on the display I have only the backlight and it starts a noisy sound. I waited for few minutes, maybe I should wait more... Anyway to stop it I hold the pwr button and it switch off... Sorry for this but I would like to understand how to load a firmware with the factory test to be updated with all the new features

**Comment by Albifly** [comment]
I can see it as storage mass, just to be clear again I can load the 322 easy, after that I do something wrong with the factory test... I suppose...

**Comment by fhorinek** [comment]
* Go to http://vps.skybean.eu:8080/repo/updates/789/
* download UPDATE.EE and UPDATE.FW to the sky drop
* then unmount it from computer and hold right button.
* Let go the button after you see yellow light. 
* download RST_FT to the drop and then hold middle button.
* Then unplug it form computer.
* The screen will be clear but it will go gradually to light contrast.
* than press left or right button to tune minimal contrast value
* press middle button to confirm it
* wait until the contrast go up and then pres left or right button to tune the maximum contrast value
* press middle button to confirm it. Then confirm optimal value.
* Now you will be in device test
* all test will pass automatically except button test (but: 000 will blick)
* press all the button one at the time
* you will hear different sounds and led will shine at different colors
* after that the vario will boot-up and you are done

**Comment by Albifly** [comment]
Sorry.. I reply by email, I can load the 322 so I think I know how to update the firmware. When I start the procedure with the factory test (after I put both files on the drop and pressed the right button) something is still going wrong, only backlight and nothing appears on the display, it is only coming out a strange sound… For how long should I wait to see something on the display? I waited for minutes. I followed your indications step by step but I can not see anything different. Today I will fly again with the 322… The problem is the factory test I guess

**Comment by fhorinek** [comment]
can you send me the update files you are applying to skydrop to fero@skybean.eu

**Comment by fhorinek** [comment]
We will release video tutorials for update, config and factory test soon, please be patient.

**Comment by fhorinek** [comment]
https://www.youtube.com/watch?v=_qffgnJawU0
