### ISSUE TITLE
freezes, restarts, no vario value

### ISSUE THREAD

**Issue by Sabistik** [fhorinek/SkyDrop#60]
Hi,
I just received my skyDrop but after update to newest software version i have only problems.
My SkyDrop are restart after turn it on. 
If SkyDrop turn on correctly - vario value is empty or show weird values. 
I shot a short video to illustrate this. https://goo.gl/photos/CpqqTynvhQZeVryo6

Any suggestion to solve this problems?

**Comment by fhorinek** [comment]
Did you apply update file UPDATE.FW without UPDATE.EE? Try to copy UPDATE.EE
from the same build to the vario and then power it up.

**Comment by tomasz13** [comment]
i think, this is your problem...

https://github.com/fhorinek/SkyDrop/issues/18

**Comment by Sabistik** [comment]
hmm. I copied both files to vario like is in 'quick start guide'. But now i copy only .ee file and update are done. It looks like ok now.

Thank you very much!

**Comment by fhorinek** [comment]
Happy to help
