### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by heiner24** [fhorinek/SkyDrop#64]
Hey, I just received my Skydrop after changing gps module, thx for that. Everything works except I have no sound. I already did the factory test reset, but still no sound. Any ideas? FW is the newest version.

Kilian

Already found a solution, it was the autostart-no sound function. Done ;-)

**Comment by Sabistik** [comment]
i think that skydrop should have 'Suppress Audio' set to off in default. i also on start thing that the sound is broken. :)
