### ISSUE TITLE
frozen gps altitude

### ISSUE THREAD

**Issue by jarda-manana** [fhorinek/SkyDrop#68]
During a flight a gps altitude suddenly froze, showing same number for few hours. Other pages had broken layout (ie small widget (time) had enormous font size), so I wasn't be able to check gps speed nor gps heading. 

After landing gps altitude was ok, but I forgot try switch pages, unfortunately.
Sorry for poor bugreport, if there is something that I can provide, I will.
Build 789

**Comment by fhorinek** [comment]
Try to update to newest version

**Comment by fhorinek** [comment]
Did this error occured in newer version?

**Comment by jarda-manana** [comment]
Don't know yet - it happened during 6 hours flight and I wasn't be able to replicate it again. I will try new fw at car during longer drive tomorrow.

**Comment by jarda-manana** [comment]
During 4 hours drive this error didn't occurred on 1112...
So, I'm closing this issue. Thanks for all your work.
