### ISSUE TITLE
End flight

### ISSUE THREAD

**Issue by colignym** [fhorinek/SkyDrop#71]
Please implement different way to end flight.  At the moment one needs to switch device off.  Would be nice if device detects no motion for maybe 30 seconds, then "prompts"  "end flight"  if no response from user, then prompt disappears after X seconds.

**Comment by Paraglider1** [comment]
Thumbs up...! Great proposal...! I have the same "problem"...

**Comment by tomasz13** [comment]
sorry, I don't know write this idea in english :(

...bolo by dobre tuto funkciu spraviť tak, ako je to s resetovaním a nastavovaním hodnôt ALT1, ALT2... čiže s tlačítkom O by sa dalo vybrať widget Ftime, a keď podržím O dlhšie, tak čas vynulujem (následne sa mi ukážu TOP hodnoty v podobnom okne ako keď nastavujem hodnoty ALT). Keď potlačím tlačítko >, tak naštartujem nove kolo. A keby sme to chceli ešte viac sofistykovať, tak dalo by sa dalo v Settingsoch vytvoriť položku Manual start, a keď je to aktivovane, tak po zapnutí by SkyDrop nabootoval do okienka s poslednými top hodnotami,  a s tlačítkom > by sa aktivovalo vario, pípanie, meranie...
Tým pádom by bolo vyriešené ukončenie letu, zhrnutie dosiahnutých hodnôt, manuálny štart. :)

**Comment by fhorinek** [comment]
In new release >1000 you can takeoff/landing via Long press in Flight time widget

**Comment by colignym** [comment]
On the latest release, one can stop flight, but not reset, unless one switches off.  
Maybe long press arrow for reset?

**Comment by fhorinek** [comment]
@colignym Why do you need to reset it anyway?
It can be done of course

**Comment by colignym** [comment]
Where we play on our slope, we often come in and land, and launch again a few minutes later.  it's nice to start timing the next flight.  The best will be if the device autostarts the next flight automatically on launch.  Maybe this works already?

**Comment by fhorinek** [comment]
@colignym uff newer been on such slope yet
I have to climb to get to take off or get parataxi :)
the autoland is not yet available, but I will implement manual reset

**Comment by colignym** [comment]
Would it not be simpler to let the device reset and start timing again, the moment it detects a new takeoff?

**Comment by colignym** [comment]
I flew with the Skydrop again this weekend.  It is nice that one can now "end flight" on landing, but it's very frustrating that there is still no way to reset the flight time, other than switching device off.
The other problem, whilst flying, one can accidentally end flight while fiddling with the menus.  Would be nice to have a prompt asking "end flight? Yes or no"

**Comment by fhorinek** [comment]
done in next release

**Comment by colignym** [comment]
Thank you,  thank you, thank you!!!    It is now brilliant, that the device will start to record a new flight on a new "take off detection"

In the past one could easy forget to reset Skydrop before the next flight.  Now it is automatic.  Thank you very much!
