### ISSUE TITLE
feature request: make use of the acceleration sensors

### ISSUE THREAD

**Issue by atomphil** [fhorinek/SkyDrop#72]
Is it possible to implement the use of the acceleration sensor data to make a lag free super accurate vario? Like www.xctracer.com

That would be my favorite feature wish besides bluetooth.

**Comment by tomasz13** [comment]
I would like this function too... :)

**Comment by mennodenhollander** [comment]
I would like this function as well, there is nothing about a vario that I would like more than that it responds immediately.

**Comment by tomasz13** [comment]
Are there any news around this feature? It would be cool. ;)

**Comment by fhorinek** [comment]
we are working on it right now, and the implementation is almost done

**Comment by martinb69** [comment]
Would be a game changer for me and saves an xctracer.... keep up the good work!

**Comment by fhorinek** [comment]
Implemented, you can enable it in newer versions in Vario->use accel.
This will require sensor calibration, we are working on tutorial video.
