### ISSUE TITLE
audio profiler 

### ISSUE THREAD

**Issue by pturri** [fhorinek/SkyDrop#74]
As wrote in the past, I deem this one of the most interesting features of SkyDrop, I'm really glad you managed to add this features, good job! 

BUT, as far as I can understand web based profiler does not give audio feedback, and the only way to check audio settngs is to create a profile, download it on the Drop, and use simulation menu. Right?
It works, but it's a real PITA.

Are you going to implement real time audio simulation to audio profiler in future, or this will remain as it is?

**Comment by fhorinek** [comment]
There will be audio simulation in next release do not worry :)

--
František Horínek

2015-08-31 12:31 GMT+02:00 pturri <notifications@github.com>:

**Comment by pturri** [comment]
very good! :+1: 
:ok_hand:

**Comment by colignym** [comment]
Would be nice to have a smaller increment between 0 and 0.5 m/s lift.  I set mine up for very short, spaced blips at 0.1 - 0.2 m/s then normal from 0.5.  Please note that the graph in Red = length of beep, and not Pause as indicated on legend below graph.
Nice work.

**Comment by pturri** [comment]
I agree with colignym, but as far as I understood the "weak lift" zone is going to be managed through a specific and separate set up / menu.

**Comment by fhorinek** [comment]
yes the weak lift will be separated from the audio profile

**Comment by filozof83** [comment]
that's what i mean in #70

**Comment by fhorinek** [comment]
I have switched the lines for pause and length
simulation is still pending

**Comment by SonnenSimon** [comment]
not the absolute correct place here, but instead of opening a new issue:

Now the volume-control is too rough for me. 10% or 15%-steps would be a good compromise i think.

**Comment by fhorinek** [comment]
@SonnenSimon please open another issue.
It is much easier to track them down this way

**Comment by fhorinek** [comment]
Simulation done in next release
