### ISSUE TITLE
bearing and distance from the starting point

### ISSUE THREAD

**Issue by marekbeyer** [fhorinek/SkyDrop#75]
It is possible to make a firmware allowing a widget, which would show actual straight distance from the starting point in km during the flight?  ...Thanks :)

**Comment by colignym** [comment]
I think that would be very nice, but Please also add a total km flown widget.

**Comment by SergeantAsh** [comment]
Note to the admins...please CHECK before closing suggestions as duplications, this idea is NOT the same as mine... https://github.com/fhorinek/SkyDrop/issues/77

I requested a direction pointer to show the way to home as well as a distance from that point. By blindly closing suggestions, you're missing out on good quality content. Please add my concept to this idea OR reopen the one you closed.

**Comment by fhorinek** [comment]
@SergeantAsh sorry, I might overlooked that this request does not have direction to home. But I have already put distance and direction on my list :)

**Comment by SergeantAsh** [comment]
Thanks @fhorinek!

**Comment by moyesboy** [comment]
If this is implemented please include glide ratio to starting point too!

**Comment by fhorinek** [comment]
@moyesboy I am not familiar with this function, can you explain it?

**Comment by moyesboy** [comment]
Start point lat/long and altitude is known at takeoff when logging and vario start.
Current lat long and altitude is known.

current distance from start / altitude difference with start = required glide ratio to got home.
ie, I am 10km from launch and 1000 meters higher. My glide ratio home is 10.0
I suggest display home glide ratio displayed with one decimal place up to 99.9 max.
Negative glide ratio could be displayed but might be confusing. Probably better to show just XXX (XC soar used --).

Usefulness: when recreational flying usually we want to know if we can get back. This number is an easy indication of if we can do that or how many climbs are required to make it.
When pointing back to home it is easy to see if this number is reducing (we are making it) or increasing (we are making it).
This number easily tells us if we are "committed" when we stay in a thermal as we drift over the back from launch (if we climb well enough to make it back into wind the number gets smaller - very useful for UK pilots).
 Irrespective of the glider performance/wind etc so a very useful info without complex calculations.
By automatically having the home destination for every flight we have what we want much of the time without adding to our preparation at all.

I think this is quite easy and should come before direction arrow which will be a lot more work. Probably direction arrow should come with route navigation functions.

I which my 6030 used the launch point as a competition class goal automatically when no route is programmed. But they will not add to 6030 any new features now.

XC soar does this already, complete with direction indication.


Next step would be to show current average glide angle, for comparison. Requires averaging of direction, speed and descent. And a decision algorithm about when we are circling and when we are gliding. I'm not sure how much of that is worth doing on this tiny screen.
 I suspect route navigation should come first. then glide angle to home can become glide angle to goal, preferably calculated for the course distance round turn points (hang gliders are often on final glide well before the last turn point these days).
