### ISSUE TITLE
firmware 910

### ISSUE THREAD

**Issue by geri34** [fhorinek/SkyDrop#76]
since the latest update, i can't read the display. with an older firmware my skydrop works .

**Comment by RomanKreisel** [comment]
Hi geri34,

i've read of such problems in the past - it was always a contrast issue.

Here's a note how to reset to factory settings again: then you should be able to re-set the contrast:

  *** Contrast note ***
     If you manage to set wrong contrast values you will need to open the vario and
     short RST and GND pads near gps module to restart factory test. 
     
     Alternativly you can place RST_FT on sd card
     or via Settings->Debug->Reset factory test



this note was taken from https://github.com/fhorinek/SkyDrop/blob/master/updates/0789/Warning.txt


Regards
Roman
