### ISSUE TITLE
Bluetooth output to UART

### ISSUE THREAD

**Issue by leachim1** [fhorinek/SkyDrop#79]
Next Step is Bluetooth Support, so my suggestion is to implement an option to send the same informations on the UART. Should be pretty easy if the UART drivers already work (early debug..?).

I am planing to connect some longrange telemetry system and this would make a lot of things easier.
Thx

**Comment by fhorinek** [comment]
sure why not

**Comment by fhorinek** [comment]
do do done ...

**Comment by leachim1** [comment]
Big Thx!
