### ISSUE TITLE
load config from 910 failed on 1098

### ISSUE THREAD

**Issue by jarda-manana** [fhorinek/SkyDrop#80]
After (successful) update on 1098 I lost my personalized screen. So I load old CFG.EE to  http://vps.skybean.eu:8080/configurator and save generated UPDATE.EE to skydrop. After restart skydrop shows a message "UPDATE.EE is not compatible!"

Files: https://www.dropbox.com/sh/wnq9z6ehtxvngb1/AACxcNS71FC9jVK2TwQnT-nma?dl=0

**Comment by fhorinek** [comment]
Yes I know about it, it is because the configuration structure is different from release to release. There will be tool to convert old cfg to newer format soon

**Comment by jarda-manana** [comment]
Ok, I thought so. I changed issue name to be little more descriptive.

**Comment by fhorinek** [comment]
Ok one last question, did you update the normal way or did you use workaround from #78

**Comment by jarda-manana** [comment]
Normal way, but after uploading FW file I unmount device and disconnect usb cable.

(I have had some issues during upgrade to 910 last week - maybe broken file, I don't know... So I was little bit more careful today (md5 check  and so)).

**Comment by fhorinek** [comment]
there is "Upgrade to newest build" option in configurator for next release
