### ISSUE TITLE
factory test didn't finish on 1112

### ISSUE THREAD

**Issue by jarda-manana** [fhorinek/SkyDrop#83]
BT: ERR keeps flashing (I have an old one with 1322 bt). After downgrade to 1098, I am able to finish the factory test

**Comment by fhorinek** [comment]
The bt support is broken in 1112, because of the system rework

**Comment by fhorinek** [comment]
Please do not try to do factory test in 1112
also you do not need to run factory test if contrast is ok

**Comment by fhorinek** [comment]
The 1112 is history now, no point to have it open
