### ISSUE TITLE
configurator: old config - "Unknown macro name" warnings

### ISSUE THREAD

**Issue by jarda-manana** [fhorinek/SkyDrop#84]
after upload 987 CFG.EE into configurator you have to click on enormous "Unknown macro name WIDGET_GLIDE_RATIO" alerts

**Comment by fhorinek** [comment]
fixed in next release, thank you for the catch!

**Comment by jarda-manana** [comment]
I passionately clicked all these alerts and load config from 987. Hit and experimental upgrade button and load new config on 1112. And strange things start happen - missing or nonsense (uninitialised(?)) numbers and so on. That's how I caught never endings factory test (#83) on 1112 - trying to do factory reset.

This happened on Thursday, feature was marked as experimental, so that's why I don't want to open new issue ;)

Could you please try CFG.EE from https://www.dropbox.com/sh/wnq9z6ehtxvngb1/AACxcNS71FC9jVK2TwQnT-nma?dl=0 in next - alert free - release? There should be custom layout with 6 fields (vario, avg vario, alts1-4). Thanks!
