### ISSUE TITLE
Update.EE is not compatible

### ISSUE THREAD

**Issue by Cloudmaker** [fhorinek/SkyDrop#85]
Hello,
I've got the SkyDrop from my Daugther and she said it doesn't work.
The Screen was dark and we where not able to see anything.
So I've done the steps in this post
https://github.com/fhorinek/SkyDrop/issues/57
and reset to Firmware 0789
Everything is ok, we can read the signs on the screen.
Now I want to Update to the newest FW, 
but after copying the files from the 0910 Folder to the SkyDrop 
I get the messege "update.EE is not compatible".

**Comment by colignym** [comment]
After you copy it to your skydrop, press and hold the right arrow.  Then it will work.  If you press and hold the middle button, you will get that message.

**Comment by fhorinek** [comment]
@Cloudmaker did you solve your issue?

**Comment by fhorinek** [comment]
new update method will prevent this
