### ISSUE TITLE
dead after 1278 update

### ISSUE THREAD

**Issue by pturri** [fhorinek/SkyDrop#91]
Tried to update (build 1278 rev. 1506) with usual procedure, this is SD content BEFORE reboot:
![cattura](https://cloud.githubusercontent.com/assets/13049568/10246785/8d187756-6914-11e5-908b-08b3192db15b.JPG)

When I reboot the devide or I disconnetct USB, it's stays on for a short while (about 3sec) and then it swithes off. 

![foto 02-10-15 14 35 59](https://cloud.githubusercontent.com/assets/13049568/10246676/abd9a314-6913-11e5-8671-af80b271c936.jpg)

Now Drop is dead. 
Any idea?

**Comment by fhorinek** [comment]
Can you still go into the usb mode?

**Comment by pturri** [comment]
I just managed to recover the device through RST_FT. Now it seems to work with 1278 build. 

But I suggest to find a way to make updates way more easier and flawless, I did 5-6 updates so far and I had different problems with most of them. Not all people is skilled enough to follow actual update procedure (update page itself is quite geek and very ppor user friendly) and even less to recover the device in case of issues..

Besides this, Drop is getting more exciting every day ;)

**Comment by fhorinek** [comment]
There is single file method already implemented in this release. From now
the updates will be much more simpler.

**Comment by jarda-manana** [comment]
I had problems with update from 1186beta on hw 1504: device seems to by totally bricked after copying files, unmount operation failed. (See dmesg output here: http://pastebin.com/d8w11NuT) No usb mode, no lights, nothing. RST_FT doesn't help.
So I  downgraded to 0910 and device started. Upgrade to 1278 (via copying files directly to microSD) was  successful. Red led still lights during first run, but turn it on and off again solve this issue ;)

**Comment by fhorinek** [comment]
I guess I can close this now
