### ISSUE TITLE
BT module not recognized during FT

### ISSUE THREAD

**Issue by bluearcus** [fhorinek/SkyDrop#92]
I'm on 1098beta. This was the first stable version I managed to get to after having difficlty updating to the version which introduced the new firmware format.

Attempting the update from 1098 to 1278 fails everytime with an 'Incompatible update.ee format' message.

Any ideas?

**Comment by fhorinek** [comment]
Copy update files and then hold right button instead of middle one.
I promise that this release is the last one with this update method :)

**Comment by bluearcus** [comment]
Ok, success. Now on latest...
I ran factory reset to adjust my screen contrast calibration. Unfortunately now I have a bluetooth error and can't exit the calibration.
Argh! :-/
On 2 Oct 2015 22:43, František Horínek <notifications@github.com> wrote:Copy update files and then hold right button instead of middle one.
I promise that this release is the last one with this update method :)

**Comment by fhorinek** [comment]
hat module do you have?

--
František Horínek

2015-10-03 1:00 GMT+02:00 bluearcus <notifications@github.com>:

**Comment by bluearcus** [comment]
Not sure, the device won't come out of factory reset mode for me to find out. I can't power it off, have to wait for the battery to run flat, then power on with USB lead, after which it goes back into calibrate :-(
On 3 Oct 2015 08:27, František Horínek <notifications@github.com> wrote:hat module do you have?

--
František Horínek

2015-10-03 1:00 GMT+02:00 bluearcus <notifications@github.com>:

**Comment by fhorinek** [comment]
when you plug the usb during the factory test it should return to usb mode,

**Comment by fhorinek** [comment]
And the bt module is still ERR? you can disassemble the vario and then
reconnect battery, or short GND and RST pin on the bottom

--
František Horínek

2015-10-03 10:24 GMT+02:00 bluearcus <notifications@github.com>:

**Comment by colignym** [comment]
Audio configuration does not seem to work anymore.  Does not load cfg it seems.

**Comment by bluearcus** [comment]
Re-applied the same update again via USB mode. This time, factory test passes for the bluetooth. Weird.

**Comment by jarda-manana** [comment]
I can confirm, that bluetooth test in factory test passes only when drop is connected to usb. Build 1278, hw rev. 1504.

**Comment by mennodenhollander** [comment]
Running the FT with the usb cable plugged in was not enough for me. You need to copy the 1278 firmware files again via the USB connection to make the bluetooth factory test pass.

**Comment by fhorinek** [comment]
I was able to locate bug in Factory test for release 1278 with pan1026. It will be fixed in next release
