### ISSUE TITLE
bluetooth only occasional visibility

### ISSUE THREAD

**Issue by jarda-manana** [fhorinek/SkyDrop#94]
I have problems with device visibility on bluetooth (build 1278, hw 1504). Other devices see skydrop only time to time. So I am unable to pair/connect it. Tested with 3 different devices. When everything succeeds, connection works, skydrop communicates with XCTrack without problems. But next "flight" (power off and on both devices) I am not able to connect device, or pair it again. Time to time is device visible, but pairing fails. I succeeded only once to set up complete connection to XCTrack, tried it aprox 30 times.

**Comment by fhorinek** [comment]
what bt module do you have? Settings->bluetooth

**Comment by jarda-manana** [comment]
pan1322 v2.1

**Comment by Kapiness** [comment]
Hallo, i have similar problem, I have pan 1026 v 4.0 and i also cant find skydrop from two iphones, and macbook.

**Comment by fhorinek** [comment]
iPhones are not supported yet. We did not test SkyDrop on os x. But it is working on standard protocol so it should work and you should see it on os x. Also the Bluetooth is not enabled by default, please make sure it is on.

**Comment by Kapiness** [comment]
Yes, i tried on my friends android, and he could find skydrop immediately. But it is not visible from iOS. And if i understand it right, bluetooth icon on the main screen will stop blinking when xc application will communicate  with skydrop? or when its connected to the phone ? I am using Flyskyhy xc app for iOS. Cant wait to pair them :)

**Comment by fhorinek** [comment]
@jarda-manana I cannot replicate the bug, what devices (exactly) are you using?

**Comment by jarda-manana** [comment]
Tested with Samsung YPG-70, Lenovo A660 and dell latitude laptop

**Comment by fhorinek** [comment]
Android version, operating system?

**Comment by jarda-manana** [comment]
Samsung: Android 2.3.6, Lenovo: Android 4.0.4, laptop: ubuntu 14.04LTS

**Comment by jarda-manana** [comment]
just tested (no success) on my colleague’s Samsung SM-G360F, android 5.0.2

**Comment by jarda-manana** [comment]
persists on 1449beta

**Comment by jarda-manana** [comment]
seems slightly better on 1714beta: I see device often, but it refuses pair or connect. Definitively not usable for flying :( Maybe a hw issue? (I would expect that more people confirm problems, if this was a fw problem...)

**Comment by fhorinek** [comment]
Please update, it should restore the bluetooth
http://vps.skybean.eu:8080/repo/updates/1773beta/

**Comment by jarda-manana** [comment]
Still no luck - now I am unable to search the device during pairing  phase. Logs: https://www.dropbox.com/sh/89rpwhy08gk9wf8/AAA5yAKJH1clgXu4d3zMAndwa?dl=0
