### ISSUE TITLE
Factory test not passed, GPS not working

### ISSUE THREAD

**Issue by msaraceno** [fhorinek/SkyDrop#95]
I run for a while fw 0910 without problems, all seemed to work fine and GPS was able to get the fix.
I updated to 1278 and the G was blinking and I was not able to get a fix anymore (I waited more than an hour outside).

I run the factory test and GPS did not passed. I tried to downgrade to 0910 and still it not pass the GPS factory test. 

![wp_20151011_19_00_51_pro](https://cloud.githubusercontent.com/assets/15076851/10417864/ed50a5d4-704a-11e5-888e-602395942253.jpg)

Now I am not able to skip the test and use the vario, every times I unplug the device from the USB it restart and run the factory test where I am stuck...
I can not shut down the device and I have to wait the battery run fully out.

**Comment by msaraceno** [comment]
It may be related to issue #12 .... My board is 1504 ... if this is the case I need support.
Thanks

**Comment by fhorinek** [comment]
Did you ever havegps fix? When did you buy the SkyDrop?

**Comment by msaraceno** [comment]
Yes, i got a gps fix with fw 0910.I bought my sky drop back in January, in pre order.






On Sun, Oct 11, 2015 at 10:43 AM -0700, "František Horínek" <notifications@github.com> wrote:












Did you ever havegps fix? When did you buy the SkyDrop?

**Comment by msaraceno** [comment]
A picture of my circuit board.

----- Messaggio originale -----
Da: "František Horínek" <notifications@github.com>
Inviato: ‎11/‎10/‎2015 19:43
A: "fhorinek/SkyDrop" <SkyDrop@noreply.github.com>
Cc: "msaraceno" <marcosaraceno@gmail.com>
Oggetto: Re: [SkyDrop] Factory test not passed, GPS not working (#95)

Did you ever havegps fix? When did you buy the SkyDrop?

**Comment by msaraceno** [comment]
Tonight, after downgrade to 09, I upgraded the fw again to 1280. I left the device outside and I got the GPS fix (I do not know how Lon it took, I was watching a movie).
I run the factory test and it passed all steps flawless. 
I have no idea what went wrong before.
In the next days I will run some,additional tests.



----- Messaggio originale -----
Da: "František Horínek" <notifications@github.com>
Inviato: ‎11/‎10/‎2015 19:43
A: "fhorinek/SkyDrop" <SkyDrop@noreply.github.com>
Cc: "msaraceno" <marcosaraceno@gmail.com>
Oggetto: Re: [SkyDrop] Factory test not passed, GPS not working (#95)

Did you ever havegps fix? When did you buy the SkyDrop?

**Comment by fhorinek** [comment]
your device should work correctly since you have fixed module. I will try to replicate this bug

**Comment by msaraceno** [comment]
I tried the vario few times driving (no good condition to fly right now) and it looks it work fine: gps is detected and Gspeed is shown correctly (the speed reading is accurate but it is updated with a 1-2 seconds delay thought)

**Comment by fhorinek** [comment]
civil gps update rate is 1Hz = 1 time per second

**Comment by whu4411** [comment]
same problem here
no fix at all
really buggy product
started to think that i should buy some other vario
waste of time and money

**Comment by fhorinek** [comment]
What verizon of the firmware are you using?

**Comment by whu4411** [comment]
2097beta

**Comment by fhorinek** [comment]
what it says on settings->gps->status?

**Comment by whu4411** [comment]
bunch of 0s
and no fix
waiting for fix
tried upgrade and downgrade so many times but still no gps
this morning just tried 0322 in the top of the mountain for 1 hour but
still nothing
once i tried the factory test
it said gps: err
2015/12/26 17:55 "František Horínek" <notifications@github.com>:

**Comment by fhorinek** [comment]
I have the proposal for you:

We will send you a new unit after the holiday break.
Then please, send the old unit back for further evaluation.

--
František Horínek

2015-12-26 12:35 GMT+01:00 whu4411 <notifications@github.com>:

**Comment by whu4411** [comment]
thanks!
2015/12/26 21:16 "František Horínek" <notifications@github.com>:
