### ISSUE TITLE
Build 1278 does not Start

### ISSUE THREAD

**Issue by leachim1** [fhorinek/SkyDrop#96]
After flashing the Build 1278 my Skydrop just dont start. The loading screen appears but then it just shut down. When i flash back to 0910 everything works fine.

**Comment by fhorinek** [comment]
this can be caused by wrong revision detection.
can you specify the board revision on boot screen and on the pcb?

**Comment by jarda-manana** [comment]
both 1504

**Comment by leachim1** [comment]
Jeah seems so.
Software: rev 1506.
PCB: rev 1504.

**Comment by fhorinek** [comment]
I have reworked the detection a bit, please wait for next beta release and try it again. If ti works please close the issue

**Comment by fhorinek** [comment]
@leachim1 did you update the firmware?

**Comment by leachim1** [comment]
Jeah, you can close this Bug. THX
