### ISSUE TITLE
bug: GPS records are imperfect in IGC log

### ISSUE THREAD

**Issue by tomasz13** [fhorinek/SkyDrop#97]
some value does not change in the GPS coordinates

B121318481**0000**N01709**000**EA0011000117
B121320481**0000**N01708**000**EA0011000117

example

AXSBDRP:314A36353233060D000700
HFDTE1510-208
HFDTEDATE:1510-208,05
HFPLTPILOTINCHARGE:
HFCM2CREW2:
HFGTYFLIDERTYPE:
HFGIDGLIDERID:
HFRFWFIRMWAREVERSION:build 1449
HFRHWHARDWAREVERSION:drop_1504
HFFTYFRTYPE:SkyBean,SkyDrop
HFGPSRECEIVER:Quectel,L80,22cm,18000m
HFPRSPRESSALTSENSOR:Measurement specialties,MS5611,25907m
HFFSP:AL4
HFALGGEO
HFALPISA
B1212594810000N01709000EA0011000091
B1213014810000N01709000EA0011000091
B1213034810000N01709000EA0011000092
B1213044810000N01709000EA0011100092
B1213064810000N01709000EA0011000094
B1213084810000N01709000EA0011000094
B1213104810000N01709000EA0011000095
B1213124810000N01709000EA0011000095
B1213144810000N01709000EA0011000096
B1213164810000N01709000EA0011000096
B1213184810000N01709000EA0011000117
B1213204810000N01708000EA0011000117
B1213224810000N01708000EA0011000123
B1213244810000N01708000EA0011000123
B1213254810000N01708000EA0011000123
B1213274810000N01708000EA0011100122
B1213294810000N01708000EA0011100122
B1213314810000N01708000EA0011100123
B1213334810000N01708000EA0011100123
B1213354810000N01708000EA0011100125
B1213374810000N01708000EA0011000125
B1213394810000N01708000EA0011100104
B1213414810000N01708000EA0011100104
B1213434810000N01708000EA0011100106
B1213454810000N01708000EA0011200106
B1213474810000N01708000EA0011200106
B1213494810000N01708000EA0011200106
B1213504810000N01708000EA0011200112
B1213524810000N01708000EA0011200112
B1213544810000N01708000EA0011300117
B1213564810000N01708000EA0011200117
B1213584810000N01708000EA0011200117
B1214004810000N01708000EA0011200117
B1214024810000N01708000EA0011200118
B1214044810000N01708000EA0011200118
B1214064810000N01708000EA0011200120
B1214084810000N01708000EA0011200120
B1214104810000N01708000EA0011100122
B1214124810000N01708000EA0011000122
B1214144810000N01708000EA0011100124
B1214164810000N01708000EA0011100124
B1214184810000N01708000EA0011100125
B1214194810000N01708000EA0011100125
B1214224810000N01708000EA0011100125
B1214234810000N01708000EA0011100127
B1214254810000N01708000EA0011100127
B1214274810000N01708000EA0011100128
B1214294810000N01708000EA0011100128
B1214314810000N01708000EA0011000128
B1214334810000N01708000EA0011000128
B1214354810000N01708000EA0011000127
B1214374810000N01708000EA0011000127
B1214394810000N01708000EA0011000128
B1214414810000N01708000EA0011000128
B1214434810000N01708000EA0011100130
B1214454810000N01708000EA0011100130
B1214474810000N01708000EA0011000131
B1214494810000N01708000EA0011000131
B1214504810000N01708000EA0010900132
B1214524810000N01708000EA0010900132
B1214544810000N01708000EA0010900135
B1214564810000N01708000EA0011000135
B1214584810000N01708000EA0011000135
B1215004810000N01708000EA0011100135
B1215024810000N01708000EA0011100137
B1215044810000N01708000EA0011000137
B1215064810000N01708000EA0011000138
B1215084810000N01708000EA0011000138
B1215104810000N01708000EA0011100138
B1215124810000N01708000EA0011100138
B1215144810000N01708000EA0011100139
B1215164810000N01708000EA0011100139
B1215184810000N01708000EA0011200141
B1215194810000N01708000EA0011200141
B1215214810000N01708000EA0011300141
B1215234810000N01708000EA0011300144
B1215254810000N01708000EA0011300144
B1215274810000N01708000EA0011300146
B1215294810000N01708000EA0011400146
B1215314810000N01708000EA0011400148
B1215334810000N01708000EA0011400148
B1215354810000N01708000EA0011400150
B1215374810000N01708000EA0011400150
B1215394810000N01708000EA0011300151
B1215414810000N01708000EA0011300151
B1215434810000N01708000EA0011300154
B1215454810000N01708000EA0011300154
B1215474810000N01708000EA0011300157
B1215494810000N01708000EA0011300157
B1215504810000N01708000EA0011200158
B1215524810000N01708000EA0011200158
B1215544810000N01708000EA0011100158
B1215564810000N01708000EA0011000158
B1215584810000N01708000EA0010900158
B1216004810000N01708000EA0010900158
B1216024810000N01708000EA0010900159
B1216044810000N01708000EA0010900159
B1216064810000N01708000EA0010900160
B1216084810000N01708000EA0010900160
B1216104810000N01708000EA0010900161
B1216124810000N01708000EA0010900161
B1216144810000N01708000EA0010900163
B1216164810000N01708000EA0010900163
B1216184810000N01708000EA0010900163
B1216194810000N01708000EA0010900164
B1216214810000N01708000EA0010900164
B1216234810000N01708000EA0011000165
B1216254810000N01708000EA0010900165
B1216274810000N01709000EA0011000166
B1216294810000N01709000EA0011000166
B1216314810000N01709000EA0011000166
B1216334810000N01709000EA0010900166
B1216354810000N01709000EA0011000165
B1216374810000N01709000EA0011000165
B1216394810000N01708000EA0011000165
B1216414810000N01708000EA0011000165
B1216434810000N01708000EA0011000165
B1216444810000N01708000EA0011000165
B1216464810000N01708000EA0011000166
B1216484810000N01708000EA0011000166
B1216504810000N01708000EA0011000166
B1216524810000N01708000EA0011000166
B1216544810000N01708000EA0011000167
B1216564810000N01708000EA0011000167
B1216584810000N01708000EA0011000166
B1217004810000N01708000EA0011000166
B1217024810000N01708000EA0011000164
B1217044810000N01708000EA0011000164
B1217064810000N01708000EA0011000164
B1217084810000N01708000EA0011000164
B1217104810000N01708000EA0011000164
B1217124810000N01708000EA0011000164
GAF62042745E6BB2784F8A31AEEE98A472F7B9A1A

**Comment by fhorinek** [comment]
I know :)
fixing it right now

**Comment by tomasz13** [comment]
also the filenames could be nicer... :) timestamp or something humad readable thing not like current 5AFXDRP5.IGC
151015152501.IGC is much more U.frendly :D

**Comment by fhorinek** [comment]
It is IGC standard. Unfortunately we have only 8.3 filenames available due
memory constraints.

**Comment by tomasz13** [comment]
...and with directory....

../LOG/%Y/%m%d%H%M.IGC
../LOG/2015/10151541.IGC

the logs shorter like 1min in same minute could be repleaced. (I think they are still useless )

**Comment by fhorinek** [comment]
fixed in next release
your suggestions are now in separate issue #100
