### ISSUE TITLE
bug: I can lockup Alt2 with Alt3 vice versa

### ISSUE THREAD

**Issue by tomasz13** [fhorinek/SkyDrop#98]
if i set Alt2 relative to Alt3 & Alt3 relative to Alt2, then I can see funny thing on the screen when i look at the Att2 & Alt3 widgets :)

apropo...  is there any easteregg in the system? every awesome gadget must have some :D and this is a MAJESTIC machine

**Comment by fhorinek** [comment]
I thought that it was fixed in #32.
I will prevent this from happening

**Comment by fhorinek** [comment]
fixed in next release
