### ISSUE TITLE
Button membrame 'addon'

### ISSUE THREAD

**Issue by SergeantAsh** [fhorinek/SkyDrop#99]
I personally don't get on particularly well with the SkyDrop buttons - I find them to be awkward to press with gloves and even without gloves they are not very easy to use/press.

I would like to see a plastic cover that fits over SkyDrop and provides proper raised rubber buttons which press the buttons underneath.

**Comment by fhorinek** [comment]
We want make addon since we are working with our suppliers right now to get better buttons in the first place.
partially duplicate #61
